### PR TITLE
Profile fields repeating whenever you select the Profile type on Register page.

### PR DESCRIPTION
**Pull request by dipskakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

Create a 'Profile type' field for register page.
Select the profile type while registering.
See error

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
@dipskakadiya looks good!

https://prnt.sc/uln3xp
https://prnt.sc/uln4ik

**Comment by ankitguptaindia** [comment]
@dipskakadiya @mehulkaklotar @sourabhmatolia 

**Status-** Issues has been fixed. 
**Proof-**https://www.loom.com/share/97eebc10a6e14b7fa0c7f610a2927864

**Review by ankitguptaindia — APPROVED** [review]
**Closing Remark-** 

- [ ] Read PR description

- [ ] Checked Description on related Issue

- [ ] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [ ] Tested negative test scenario

- [ ] Updated Labels as per current status

**Final Update-**. Ready to Merge 🚀

**Comment by sergiolucianojr** [comment]
Hey guys,

I tested the solution that you approved, changing the code directly in my php, but the problem persists. It is important to say that I have conditional fields related to the type, that shows depending on the selected type.

You can see it here:
https://jogogrok.com/usuario/registro/

**Review by sergiolucianojr — COMMENTED** [review]
I tried these changes in my website, but it didn't solve the problem.

https://jogogrok.com/usuario/registro/

**Pull request merged**
