### PR TITLE
Profiles/Groups > Cover Photo Cropper

### LINKED ISSUE #561: Profiles/Groups > Cover Photo Cropper
**Is your feature request related to a problem? Please describe.**
When you upload a profile photo, you can crop it.
When you upload a cover photo, you cannot crop it. But the cover photo has a really wide dimension and so most the photos you upload look terrible. If you could crop the photo vertically it would be much nicer. This is a highly requested feature.

**Describe the solution you'd like**
Do some research to find the best script for doing this, then experiment with that script in Platform. We will need to add support for it in the theme later also. Consider mobile also.
https://www.loom.com/share/f97b41de9e954704bcaff99d9133bc75

**Support ticket links**
https://secure.helpscout.net/conversation/1111922914/1512/

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #561 

### How to test the changes in this Pull Request:

1. Go To Profile page / group page while logged in
2. Hover over cover photo
3. Click on the move icon
4. Adjust the visible image by dragging up or down and click on save button

### Proof Screenshots or Video
(In progress)

### PR connected in theme
https://github.com/buddyboss/buddyboss-theme/pull/444

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Ability to control what area should be visible of the cover photo on profile page.

### CODE REVIEW

**Comment by eisenwasser** [comment]
@amincdev 

Providing feedback for cover photos here:

1. UI Improvements:
https://www.loom.com/share/c1fc4b7ed69c436fa8d5cf0b627f178a

2. Minimum size and file size concerns:
https://www.loom.com/share/6b322a50a96c4636814d236a8a195792

3. Crop size in mobile
https://www.loom.com/share/c02bfe8b0dfa42398b11991ed32f7cb0

**Comment by amincdev** [comment]
@mehulkaklotar @chetansatasiya, One of you please review the code changes?

**Review by chetansatasiya — APPROVED** [review]
@KartikSuthar @amincdev changes looks good to me.

@mehulkaklotar can you check once and let me know if you have any changes or suggestion for the same.

@ankitguptaindia Need to test this in all the devices to make sure crop works fine.

**Comment by mohit-buddyboss** [comment]
@amincdev Tested this on the branch "feature/profile-cover-photo-cropper".
Issues:
1. Change recommended size to 1300px and 330 px instead of 230 px. As per mentioned by mich.
2. When I tested this with other themes like 2017,2019 and 2020 then found minor issues like tooltip getting hide and button design and hover issue. So kindly look into this.

Video: https://www.loom.com/share/7d0f6e869aab4ed4892f82e48e3ee054

**Comment by amincdev** [comment]
@mohit-buddyboss Both issues are fixed now. Please take pull in theme branch also.

**Comment by mohit-buddyboss** [comment]
@amincdev @sourabhmatolia 
Tested this on platform branch ` feature/profile-cover-photo-cropper` and theme branch `feature/profile-cover-photo-cropper`.
Tested this functionality for the BB theme as well as for other themes. Image cropping functionality is working fine on Firefox, chrome, edge, and safari browser.

Here, I have 2 suggestions regarding this functionality.
1) Currently, we are not showing any preview of the cover image on the Change cover image page so, it will be nice if we show a preview of newly uploaded cover image.
2) Activity which gets generate of cover or profile image upload mention only that "User change their photo" and not specify exactly which photo cover or profile? Also, not show a preview of the photo. So, it will be user friendly if we specify which photo like Profile or Cover in activity and also shows a preview of change or uploaded image.

Video: https://www.loom.com/share/0ac3012c2e03489c9ba87eea49008e8e

@sourabhmatolia Please provide your thoughts on the above suggestions. Should we implement these or not?

**Comment by mohit-buddyboss** [comment]
@amincdev 
FIXED. Tested this using both `feature/profile-cover-photo-cropper` branch.
All issues are fixed now . Video: https://www.loom.com/share/0ac3012c2e03489c9ba87eea49008e8e

connected PR : buddyboss/buddyboss-theme#444

cc @chetansatasiya

**Review by mohit-buddyboss — APPROVED** [review]
Feature is implemented successfully and PR is ready to merge.

cc @chetansatasiya

**Comment by chetansatasiya** [comment]
@mehulkaklotar Can you review once?

**Review by sourabhmatolia — APPROVED** [review]

**Pull request merged**
