### PR TITLE
#531 - Added buddypanel menu fix for group, forums, photos when WPML is active

### LINKED ISSUE #531: Menus in groups and forums under Profile page are missing - WPML
**Describe the bug**
When BuddyBoss Platform and WPML are both activated, the BuddyPanel, TitleBar and footer menus are missing in GROUPS, PHOTOS, and FORUMS under Profile Page.

**To Reproduce**
1. Activate WPML, BuddyPress Multilingual plugins together with BuddyBoss Platform
2. In WPML > Languages, make sure that Language URL format is set to Different languages in directories, please see below:
langugae_url
3. Make sure that you have already set menu links on both BuddyPanel and titlebar
3. On the frontend, go to the profile page and navigate on groups and forums

**Expected behavior**
Menus should display on GROUPS, PHOTOS, and FORUMS under Profile Page

**Screenshots**
wpml-missing-menus

**Support ticket links**
https://secure.helpscout.net/conversation/1112031720/9694/
https://secure.helpscout.net/conversation/1112029122/9508/
https://secure.helpscout.net/conversation/1111935339/2453/
https://secure.helpscout.net/conversation/1127812593/66929/
https://secure.helpscout.net/conversation/1136280364/68633/
https://secure.helpscout.net/conversation/1138657882/69114
https://secure.helpscout.net/conversation/1164333433/73381
https://secure.helpscout.net/conversation/1134655135/68272

Related issue: https://github.com/buddyboss/buddyboss-platform/issues/396

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #531 .

### How to test the changes in this Pull Request:

1. Activate WPML, BuddyPress Multilingual plugins together with BuddyBoss Platform
2. In WPML > Languages, make sure that Language URL format is set to Different languages in directories.
3. Make sure that you have already set menu links on both BuddyPanel and titlebar
4. On the frontend, go to the profile page and navigate on groups and forums

### Proof Screenshots or Video
https://www.loom.com/share/85bf4895e7da44c7b59407f5e985a236

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

>  Added buddypanel menu fix for group, forums, photos when WPML is active

### CODE REVIEW

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @mehulkaklotar 
Fixed. Tested this issue with both WPML and BuddyPress Multilingual Plugin. This issue is resolve now and side panel menu items are now appearing when user clicks on Groups, Photos and Forums tabs.
For proof see this [Vidoe](https://www.loom.com/share/ee644c5763654167b3dcf835b1012e5d)

**Comment by eisenwasser** [comment]
@mohit-buddyboss @janakkaneriya007 

This is NOT fixed. I can see it broken in your video @mohit-buddyboss 
All the links go the wrong place now. 

https://www.loom.com/share/d59502367c8c4e4982d2d60b64917a07

**Comment by eisenwasser** [comment]
@KartikSuthar Please take over and fix this properly.

**Comment by KartikSuthar** [comment]
@eisenwasser I have fixed the issue.
http://somup.com/cY1V1ujSII

Please have a look.

**Pull request merged**
