### PR TITLE
When you copy paste from the clipboard, the image do not appear in forum

### LINKED ISSUE #1606: When you copy paste from the clipboard, the image do not appear in forum.
**Describe the bug**
 If you paste an image in a forum from clipboard, that posts it visually however when the post is saved and reopened the image is missing. 

**Screenshots**
[pasting images.zip](https://github.com/buddyboss/buddyboss-platform/files/5346018/pasting.images.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1298100968/101522/

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1606

### Proof Screenshots or Video
http://somup.com/cYXqIxId9V

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@KartikSuthar LGTM 🚀 

Fix the conflict and merge in dev and put in testing.

**Review by chetansatasiya — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Tested on the dev branch of the platform.
As discussed with @KartikSuthar we are restricting users to copy/paste image from the clipboard because we already have options for the users to upload different medias.

Issue > Implemented restrictions are working on News Feed post, Group Post, Forums discussions and replies and in messages but not working for the user post comments and group post comments . So kindly implement same restrictions for the comments also.

Video: https://www.loom.com/share/abecb8a7702c49a9afe31b9803f345b3

cc @chetansatasiya @sourabhmatolia

**Comment by KartikSuthar** [comment]
> @KartikSuthar
> 
> Tested on the dev branch of the platform.
> As discussed with @KartikSuthar we are restricting users to copy/paste image from the clipboard because we already have options for the users to upload different medias.
> 
> Issue > Implemented restrictions are working on News Feed post, Group Post, Forums discussions and replies and in messages but not working for the user post comments and group post comments . So kindly implement same restrictions for the comments also.
> 
> Video: https://www.loom.com/share/abecb8a7702c49a9afe31b9803f345b3
> 
> cc @chetansatasiya @sourabhmatolia

@mohit-buddyboss I have fixed this issue. Please retest.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

FIXED>tested on dev branch of the platform.
Now copy/paste image functionality is also restricted for user post and group post.
Video: https://www.loom.com/share/3597fc4c01a246a5b339083c55856861

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya

**Pull request merged**
