### PR TITLE
PROD-952 Remove Google+ from Social Networks profile field

### LINKED ISSUE #757: Remove Google+ from 'Social Networks' profile field
**Describe the bug**
When using Social Networks profile field options we allow for adding Google+.
However Google+ was shut down in 2019.
https://www.theverge.com/2019/4/2/18290637/google-plus-shutdown-consumer-personal-account-delete

So the field is unusable. Let's remove it.

**To Reproduce**
1. Go to BuddyBoss > Profiles > Profile Fields
2. Add Social Networks field
3. Notice you can select Google+

**Expected behavior**
Remove Google+ option.

**Support ticket links**
@AiratHalitov commented in:
https://github.com/buddyboss/buddyboss-platform/issues/684#event-3190552887

### PR DESCRIPTION
**Pull request by annrra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #757 

### How to test the changes in this Pull Request:

1. Go To BuddyBoss Profiles
2. Add new field
3. Confirm Google+ is not present in the list

### Proof Screenshots or Video
(In progress)

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Remove Google+ from social networks profile field

**Jira issue** : [PROD-952]

[PROD-952]: https://buddyboss.atlassian.net/browse/PROD-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by annrra** [comment]
Google+ removed from social networks list - http://i.imgur.com/V3UplbU.png

**Comment by annrra** [comment]
@chetansatasiya thanks for the feedback. 
I will reassign task for the back end part. Please take over..

**Comment by eisenwasser** [comment]
@chetansatasiya This is for you to finish.

**Comment by mckdlrs** [comment]
Retested in the QA ongoing branch
Status: Not yet fixed

Proof Screenshots or Video: https://www.loom.com/share/cd3d1c652ce5485887bbea8a07fc830d

**Pull request closed without merging**
