### PR TITLE
Fixed-Repeater fields - if you add too many at once it will duplicate the fields in the admin

### LINKED ISSUE #1082: Repeater fields - if you add too many at once it will duplicate the fields in the admin
**Describe the bug**
"It is an issue where a regular user adds a basic repeater field (one text field) from the front end enough times (like 10 times) and it actually duplicates those fields inside the admin panel. I was able to replicate it on your demo."

**To Reproduce**
1. Create a repeater field
2. In your profile, add a basic repeater field (one text field) from the front end enough times (like 10 times) 
3. Save your profile
4. View the field group in the admin

**Expected behavior**
It should not create any extra fields in the admin

**Support ticket links**
Posted in Youtube by user "Anna DiTommaso"
https://www.youtube.com/watch?v=ofIf0VTQxok&lc=Ugz6p7u-ShTD1GaSfl94AaABAg&feature=em-comments

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1082.

### How to test the changes in this Pull Request:

1. Create a repeater field
2. In your profile, add a basic repeater field (one text field) from the front end enough times (like 10 times)
3. Save your profile
4. View the field group in the admin
5. No duplicate extra field on the admin side

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crVXqzPCrL

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@jitendrabanjara1991 Looks good awesome.

Merge in dev and add in testing

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

Issue >
Still, I'm facing the same duplicate filed issue for the proof please check the below issue video. 

**Issue video:**
https://www.loom.com/share/74a29814f6c0447d9fbf623f15b24900

**Comment by jitendrabanjara1991** [comment]
@sumitbuddyboss 
Please check below video and test it this issue again. I have explained in detail there.
https://screencast-o-matic.com/watch/cre0FZVVDGz
Please check it and let me know if you have any question.
Thanks.

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

Fixed >
I have checked in the dev branch and the related issue is resolved for proof please check the below video.

https://www.loom.com/share/7757538636e34485921f8a8bbb4798d8

@chetansatasiya 
Ready for release

**Pull request merged**
