### PR TITLE
Group Description html encoding

### LINKED ISSUE #2615: Group Description html encoding
**Describe the bug**
Updating group description with HTML content encodes the content

**To Reproduce**
1. Go to Group Manage Screen
2. Update Group Desc with HTML content
3. Go to activity feeds screen

**Expected behavior**
HTML content should be encoded and decoded properly while view

**Screenshots**
https://www.loom.com/share/8844621c775b4ed3ab3b612c8687a51d

**Environment**
https://bb-app-platform.flywheelsites.com/

**APP ISSUE**
https://github.com/buddyboss/buddyboss-app-native/issues/1334

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2615  .

### How to test the changes in this Pull Request:

1. Go to Group Manage Screen
2. Update Group Desc with HTML content
3. Go to activity feeds screen

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@krunal-buddyboss merge in dev and put in testing.

**Comment by krunal-buddyboss** [comment]
Thanks @chetansatasiya , I have merged it to Dev.
@sumitbuddyboss @mohit-buddyboss  please test it. Thanks.

**Comment by sumitbuddyboss** [comment]
Hello @krunal-buddyboss 

**Issue**
I check this issue and it's looking good to me but apart from this, I found another issue that <p> tag is removed when we save the group description in editore,

@sourabhmatolia Do we need to resolve in this pr or need to create another issue? 
Look like This is exists issue I can reproduce on the demo site as well


Issue video:
https://www.loom.com/share/01ea6a3fbb2a4f47b20e0b05fc43e690


cc @chetansatasiya @KartikSuthar

**Comment by krunal-buddyboss** [comment]
@sumitbuddyboss 
- we remove structural tags intentionally at some place. We are removing all structural tags i.e `<p>` , `<div>` , `<section>`  etc..
- If we have added new line ('`<br>`', '`\n`') it will be show as it is as it is not considers as structural.
- Other formatting tags will show with formatting at group description but in the activity feed it will be shown as a plain text only.
Thanks
@sourabhmatolia @KartikSuthar

**Comment by sumitbuddyboss** [comment]
Hello @krunal-buddyboss 

Fixed > All the related issues are resolved for the proof please check the below video.

Video:
https://www.loom.com/share/5fb44e36e8aa42988a03a3a5ba3aee09

Also, @harshalQA has confirmed in the app side
IMG_20210721_165046

cc @sourabhmatolia @chetansatasiya 
Ready for release 🚀 

Thank you

**Pull request merged**
