### PR TITLE
Message Query Enhancement

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### How to test the changes in this Pull Request:
https://docs.google.com/spreadsheets/d/1YZbSeSj3wNRJ_M7oVO2Xt13mgTS6lEucXDlQI1460tQ/edit#gid=1767785629

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
looks good! 👍 

@KartikSuthar let's test it.

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@KartikSuthar 👍 Approved good work.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar As discussed in a scrum with @dipskakadiya 
We are not including this in upcoming release. So pausing testing of this PR due to other prioroty.

cc @sourabhmatolia

**Comment by ankitguptaindia** [comment]
@KartikSuthar @mehulkaklotar 




When Group Admin sending a Group message to all group members then many blank messages appearing in group from each member of the group. https://prnt.sc/w2bz49

https://www.loom.com/share/eba34607bb2b4ce38c41974edd2c57d8

**Comment by KartikSuthar** [comment]
> @KartikSuthar @mehulkaklotar
> 
> When Group Admin sending a Group message to all group members then many blank messages appearing in group from each member of the group. https://prnt.sc/w2bz49
> 
> Refer video for more details -
> 
> https://www.loom.com/share/eba34607bb2b4ce38c41974edd2c57d8

@ankitguptaindia As discussed on the call, I have checked with my DB but can not reproduce the issue. 
Also, I have checked and try to reproduce by your DB as well but seems can't reproduce for the same.

**Comment by ankitguptaindia** [comment]
> > @KartikSuthar @mehulkaklotar
> > When Group Admin sending a Group message to all group members then many blank messages appearing in group from each member of the group. https://prnt.sc/w2bz49
> > Refer video for more details -
> > https://www.loom.com/share/eba34607bb2b4ce38c41974edd2c57d8
> 
> @ankitguptaindia As discussed on the call, I have checked with my DB but can not reproduce the issue.
> Also, I have checked and try to reproduce by your DB as well but seems can't reproduce for the same.

I checkd on new setup and looks fine. Couldn't reproduce this on new setup.

**Comment by ankitguptaindia** [comment]
@KartikSuthar @sourabhmatolia 

Tested this PR with all possbile scenario. Also tested with creating personal message thread and group message thread with 1.5.4 version of Platform plugin and  then updating Platform with Dev branch code.
Plugin functionality works similear as master branch.

This is ready to merge 👍

**Pull request merged**
