### PR TITLE
#1278 Fix - LearnDash Group Memberships - BB Platform conflict

### LINKED ISSUE #1278: LearnDash Group Memberships - BB Platform conflict
**Describe the bug**
When you have Learndash & BuddyBoss group integration enabled. If Learndash group is paid then you will join the group via BuddyBoss group then you will join automaitaclly Learndash Group without paying anything and access the course.

**To Reproduce**
1. Enable the integration of Learndash & BuddyBoss LearnDash groups → Social groups & Social groups → LearnDash groups sync via BuddyBoss > Integration > Learndash
2. Create a Paid Group in Learndash and it will create a group in BuddyBoss group as well.
3. You are able to join the LearnDash group without paying anything via BuddyBoss groups

**Expected behavior**
You should not able to join the group without paying.

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1278 

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@sourabhmatolia @ankitguptaindia This needs testing.

**Comment by ankitguptaindia** [comment]
@chetansatasiya Please check concerned shared by @sumitbuddyboss related to this task.

https://www.loom.com/share/fde0da7b3b234f3eac8ec027655632d8

**Comment by chetansatasiya** [comment]
> @chetansatasiya Please check concerned shared by @sumitbuddyboss related to this task.
> 
> I checked and group created in BB Groups section via LD group, is PRIVATE but in sumit's video that group is public.
> 
> https://www.loom.com/share/fde0da7b3b234f3eac8ec027655632d8

@ankitguptaindia @sumitbuddyboss Good Catch 👍 Fixed the issue

**Comment by sumitbuddyboss** [comment]
Fixed. it's working as expected, This issue is resolve now. For proof please check the below.
*Proof Video*
https://www.loom.com/share/9e0c346c4e404a69b48f59d716e78eb6

@amincharoliya 
Design and alignment issues.
https://www.loom.com/share/1f30491f29b04092afe6087ee65ad1bf

**Comment by amincdev** [comment]
@sumitbuddyboss Please test the above UI issues here: https://github.com/buddyboss/buddyboss-theme/pull/888

**Comment by amincdev** [comment]
@sumitbuddyboss Please check above issue when you get chance.

**Comment by sumitbuddyboss** [comment]
> @sumitbuddyboss Please test the above UI issues here: [buddyboss/buddyboss-theme#888](https://github.com/buddyboss/buddyboss-theme/pull/888)

Fixed.
Fixed. I have tested on BB theme fix/887 and BB Platform fix/bp-ld-group-sync and it's working as expected, this issue is resolve now. For proof please check the below video.

Video:
https://www.loom.com/share/45a39b68ce2d4c71a1495361fe794134

CC @ankitguptaindia

**Review by KartikSuthar — APPROVED** [review]

**Comment by 007ke** [comment]
@sourabhmatolia any status update on the #1357 issue ??

**Comment by 007ke** [comment]
Has your yesterday's buddyboss theme release v1.6.0 fixed this issue?

**Comment by sourabhmatolia** [comment]
PR: https://github.com/buddyboss/buddyboss-platform/pull/1280
This was already released a month back.

THIS ONE: https://github.com/buddyboss/buddyboss-platform/issues/1357
Is still ongoing

Thanks.

**Comment by 007ke** [comment]
Thanks Sourabh

Thanks for the update and trust you and family are well and keeping safe!

I was following the wrong issue #   :-)


Best Regards,

Ketan

**Comment by 007ke** [comment]
@eisenwasser 
This #1357 LD layout issue is pending since August 2020. 
Does it take this long????????????? Seriously!!!

**Comment by 007ke** [comment]
@eisenwasser @sourabhmatolia 
The #1357 LD layout issue is pending since August 2020. This is now almost 8 months and all we need is a styling issue fixed

**Comment by 007ke** [comment]
@chetansatasiya @eisenwasser @sumitbuddyboss 
There is no update to my message past 8 days. Also this issue is pending past 8 months.
Your customer support team has no idea when this will be resolved.

**Pull request merged**
