### PR TITLE
#1255 - Login Information screen, password should get an "eye" to toggle it on and off.

### LINKED ISSUE #1255: Login Information screen, password should get an "eye" to toggle it on and off.
**Describe the bug**
On the login screen there is an eye to toggle it on/off - https://prnt.sc/sptj2v
But our Login information screen does not - https://prnt.sc/tnopcu

**Expected behavior**
We should add the "eye" on the password field/s on Profile > Account > Login Information screen.

**Screenshots**
https://prnt.sc/sptj2v
https://prnt.sc/tnopcu

**Support ticket links**
Reported on Youtube video:
https://www.youtube.com/watch?v=p196OOrAF-A&lc=UgxxxsCqwh8GxteWxot4AaABAg&feature=em-comments

**Related Issue**
https://github.com/buddyboss/buddyboss-platform/issues/944

### PR DESCRIPTION
**Pull request by sagarjadhav**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1255 .

### Proof Screenshots or Video

https://prnt.sc/u2t37b

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@sagarjadhav 🚀 

@ankitguptaindia Need to test this.

**Comment by ankitguptaindia** [comment]
@sagarjadhav 
this newly added icon needs some improvements.:

- Make in center of textbox
- Hover behaviour is not matching other icons which we using on signup and signin page
- If password is long then overlapping the icon in mobile layout.  https://i.imgur.com/COtRgaB.jpg

Refer -  https://www.loom.com/share/f27a9de1111540cface3a18c01d82817

**Comment by sagarjadhav** [comment]
@ankitguptaindia Plz check with theme branch PR as well - https://github.com/buddyboss/buddyboss-theme/pull/937

**Comment by ankitguptaindia** [comment]
@sagarjadhav 

**Status-** Done. Ready to Merge 🚀 
**Proof-** https://i.imgur.com/jaZgsYw.jpg

**Review by ankitguptaindia — DISMISSED** [review]
**Status-** Done. Ready to Merge 🚀 
**Proof-** https://i.imgur.com/jaZgsYw.jpg

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
