### PR TITLE
Non-admin have HTML tags showing on forum replies

### LINKED ISSUE #867: Non-admin have HTML tags showing on forum replies
**Describe the bug**
Non-admin have HTML tags showing on forum replies if they copy the content from a web page

**To Reproduce**
1. As a Subscriber, go to Discussions and reply to one 
2. Copy your content from a web page
3. Paste the content and reply this in the discussion
4. See error, HTML Tags are showing

**Expected behavior**
When subscribers are posting replies that they copy from a web page, HTML tags are showing.
For admins however, this is working fine. 

**Screenshots**
https://drive.google.com/open?id=1kteSXP6Rgq0kulSpB5lCUv8dLgEtUfZC

**Support ticket links**
https://secure.helpscout.net/conversation/1158427048/72424?folderId=3701258

### LINKED ISSUE #1226: Broken HTML in forum replies breaks whole page
When we copy and paste things from internet, and that copied content contains invalid HTML, then replies page is all broken.

**Steps to reproduce the behavior:**
1. Go to any discussion.
2. Reply with some invalid HTML content. ( I have shared my local DB and shared video as well. You can have that invalid HTML from backend. )
3. Refresh the page.

**Expected behavior**
Replies page should not be broken.

**Video**
https://www.loom.com/share/6e92c3cca70e42c1a0f8728c7e7feab1

**My Local DB**
[wp_bbplatform-2020-07-17-3443e94.sql.zip](https://github.com/buddyboss/buddyboss-platform/files/4938993/wp_bbplatform-2020-07-17-3443e94.sql.zip)

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #867
Fixes #1226

### How to test the changes in this Pull Request:

1. As a Subscriber, go to Discussions and reply to one
2. Copy your content from a web page
3. Paste the content and reply this in the discussion
4. See HTML Tags are showing or not.

### Proof Screenshots or Video
http://somup.com/cY1oiqQYiS

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
@KartikSuthar I tried same steps in dev branch but I could not reproduce this issue in dev branch too. 
Could you please share steps how you reproduce this issue?

https://www.loom.com/share/bfab1dda3e30468d9cb8d7a5bb8394ec

**Comment by KartikSuthar** [comment]
@ankitguptaindia Please try this and check its reproducible with the dev branch: 
http://somup.com/cYiQjGQ7bT

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia Please try this and check its reproducible with the dev branch:
> http://somup.com/cYiQjGQ7bT

@KartikSuthar I tied again but this is not reproducible in my system. It looks like this may be due to any plugin conflict.
https://www.loom.com/share/cba9a3d9b3bf41859a24c07a2003e851
We can have a call and discuss this.

**Comment by KartikSuthar** [comment]
@ankitguptaindia As discussed, you need to enable "Post Formatting" from settings. http://prntscr.com/tf4lu7

**Comment by ankitguptaindia** [comment]
@KartikSuthar Div tag is not appearing now.
But other tag like table, td, tr, etc are appearing..

https://prnt.sc/tf4sib

https://www.loom.com/share/6f2c52dab3de4281ab3ceef492594f08

**Comment by KartikSuthar** [comment]
@ankitguptaindia Can you please retest again? I have fixed the table issue.

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

If you try some different types of tags then some tags still appearing https://prnt.sc/tgoboe

I tried some content with Subscriber user and those broken markup appearing in reply.

1. Copt the Group Header content like this and some markup will appear in reply https://prnt.sc/tgocso
2. Copy BuddyPanel content, you will see all broken markup  https://prnt.sc/tgoijh
3. Copy Content from group Listing https://prnt.sc/tgonnj
4. Copy whole page content from Google Home page https://prnt.sc/tgopai
5. Copy and paste Github PR content in reply https://prnt.sc/tgopmp

**Comment by KartikSuthar** [comment]
> @KartikSuthar
> 
> If you try some different types of tags then some tags still appearing https://prnt.sc/tgoboe
> 
> I tried some content with Subscriber user and those broken markup appearing in reply.
> 
> 1. Copt the Group Header content like this and some markup will appear in reply https://prnt.sc/tgocso
> 2. Copy BuddyPanel content, you will see all broken markup  https://prnt.sc/tgoijh
> 3. Copy Content from group Listing https://prnt.sc/tgonnj
> 4. Copy whole page content from Google Home page https://prnt.sc/tgopai
> 5. Copy and paste Github PR content in reply https://prnt.sc/tgopmp

@ankitguptaindia , I have added more tags to clean while pasting. We can not clean all HTML tags while pasting.
I have fixed all the above issues excerpt 2 as you just copied the li tags without ul and the medium editor was not able to auto-generate ul tags.

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

I understand, we can not clean all HTML tags. Thanks For fixing above listed tags.. 
Hope, these cleaned tags will solve problem of Users.

I noticed, above listed 5th point i.e. Github markup is still appearing for me. Other are fixed. If this is okay, let me know I will close this PR for merging.

Plz Refer- https://www.loom.com/share/0cc69e80d2ec480f8d82e68a2e503017

> > @KartikSuthar
> > If you try some different types of tags then some tags still appearing https://prnt.sc/tgoboe
> > I tried some content with Subscriber user and those broken markup appearing in reply.
> > 
> > 1. Copt the Group Header content like this and some markup will appear in reply https://prnt.sc/tgocso
> > 2. Copy BuddyPanel content, you will see all broken markup  https://prnt.sc/tgoijh
> > 3. Copy Content from group Listing https://prnt.sc/tgonnj
> > 4. Copy whole page content from Google Home page https://prnt.sc/tgopai
> > 5. Copy and paste Github PR content in reply https://prnt.sc/tgopmp
> 
> @ankitguptaindia , I have added more tags to clean while pasting. We can not clean all HTML tags while pasting.
> I have fixed all the above issues excerpt 2 as you just copied the li tags without ul and the medium editor was not able to auto-generate ul tags.

**Comment by mehulkaklotar** [comment]
@ankitguptaindia Yes we can not have support for whole website content into editor. This is not a Website editor.

**Pull request merged**
