### PR TITLE
Forums page and Group Discussions are not working with non-english

### LINKED ISSUE #1159: Forums page and Group Discussions are not working with non-english
**Describe the bug**
Forum page and the Group discussion tab is not working when the slugs for the forum component page, single forums, and topics are written in Non-English characters.

**To Reproduce**
1. Create a page with non-English characters
2. Set it as the main forum page
3. Go to BuddyBoss > settings > Forums > and change the slugs in Single Forum Slugs and Forum Profile Slugs with Non-English characters as well.
4. Go to any forums, topics, or group discussions and notice that it will redirect to 404 page.

**Screenshots**
https://i.ibb.co/ZxSq7gR/ssss.png
https://i.ibb.co/t3QWfMJ/ss.png
https://i.ibb.co/fN7k1sV/404.png

**Support ticket links**
https://secure.helpscout.net/conversation/1214540802/81564
https://secure.helpscout.net/conversation/1373036252/115828

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1159 .

### How to test the changes in this Pull Request:

1. Create a page with non-English characters
2. Set it as the main forum page
3. Go to BuddyBoss > settings > Forums > and change the slugs in Single Forum Slugs and Forum Profile Slugs with Non-English characters as well.
4. Go to any forums, topics, or group discussions and notice that it will redirect to 404 page.

### Proof Screenshots or Video
http://prntscr.com/tj0wxx
http://prntscr.com/tj0x5u
http://prntscr.com/tj0xdb
http://prntscr.com/tj0xls

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
@KartikSuthar Looks good!

@ankitguptaindia needs testing!

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Tested this on the `fix/1159` branch of the platform.
Tested this by creating new page in another language and setting it as forum directory page. Also, changed slugs of other Single forum and Forum Profile.

Issue: 
 When we create a new page in any another language and if we set as a Forum directory page from component pages settings then that page stops appearing in front end and when user try to access that page it redirects user to homepage.
Also, merge dev branch code into this branch to resolve user profile design related issue.

Video: https://www.loom.com/share/523ee53dac654310a6e3b905de0002e5

**Comment by KartikSuthar** [comment]
@mohit-buddyboss I have fixed the issue with the forum directory page in a non-English language,
http://prntscr.com/vmp75j

Can you please restest it?

**Review by chetansatasiya — APPROVED** [review]
@KartikSuthar LGTM 🚀 

Merge in dev and add in testing.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

FIXED> This issue is resolve now. Tested on dev branch. Tested this by creating new page in another language and setting it as forum directory page. Also, changed slugs of other Single forum and Forum Profile.

Proof : https://www.loom.com/share/85d659f044414466a6438117fbdd1073

Related issue is resolve now and PR is ready to merge.

@chetansatasiya @sourabhmatolia @mehulkaklotar

**Pull request merged**
