### PR TITLE
Removed SQL query and saved via function

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@chetansatasiya Works for me! 

@mohit-buddyboss Can you please test it?

**Review by mehulkaklotar — APPROVED** [review]
@chetansatasiya this looks good! fantastic work!

**Comment by chetansatasiya** [comment]
@mehulkaklotar @KartikSuthar merged to dev done.

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

Tested on Dev branch.

Issue 1> Document Directory page
Des: All the folders are getting create default with Public privacy doesn't matter what privacy logged in user selects also folder privacy is not getting change via edit privacy option.
Video: https://www.loom.com/share/1fd324d485d54b7e8371b6c703bd4e0a

Issue 2 > User Profile> Document tab
After successfully moving folder or document when user try to load documents via click on load more option then "No documents available" notification msg gets display . Load more functionality starts working once user refresh the page again after moving folder or doc.
Video: https://www.loom.com/share/69bc7cccad004b12a24c79a4f71232b2

Issue 3> User Profile >Document tab> Folder privacy is not getting change via edit privacy option.
a) At the time of creation if users selects any other privacy option except PUBLIC then in that case folders are getting create with 'Public " privacy doesn't matter what privacy user selected. It happens Sometimes (1 out of 7 times).
b) If user change privacy of folder using edit privacy option then it is not getting change. 
Video: https://www.loom.com/share/0c7f6ad3fba14db7a35161b0761e1e57

cc @mehulkaklotar @KartikSuthar

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Tested on Dev branch.
> 
> Issue 1> Document Directory page
> Des: All the folders are getting create default with Public privacy doesn't matter what privacy logged in user selects also folder privacy is not getting change via edit privacy option.
> Video:
> 
> https://www.loom.com/share/1fd324d485d54b7e8371b6c703bd4e0a
> 
> Issue 2 > User Profile> Document tab
> After successfully moving folder or document when user try to load documents via click on load more option then "No documents available" notification msg gets display . Load more functionality starts working once user refresh the page again after moving folder or doc.
> Video:
> 
> https://www.loom.com/share/69bc7cccad004b12a24c79a4f71232b2
> 
> Issue 3> User Profile >Document tab> Folder privacy is not getting change via edit privacy option.
> a) At the time of creation if users selects any other privacy option except PUBLIC then in that case folders are getting create with 'Public " privacy doesn't matter what privacy user selected. It happens Sometimes (1 out of 7 times).
> b) If user change privacy of folder using edit privacy option then it is not getting change.
> Video:
> 
> https://www.loom.com/share/0c7f6ad3fba14db7a35161b0761e1e57
> 
> cc @mehulkaklotar @KartikSuthar

@mohit-buddyboss all of issues are fixed and merged in dev.

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED> All 3 issues are fixed now.
Video : https://www.loom.com/share/6c45996923ba471a9668889566f9ac44

Tested this on dev server. Document Privacy, Update, Move and delete functionality is working fine.
This PR is ready to merge. 

cc @mehulkaklotar @KartikSuthar

**Pull request merged**
