### PR TITLE
PROD-721 Fix - Few strings are not translatable

### LINKED ISSUE #3048: Few strings are not translatable
**Describe the bug**
Check these below strings, those are hardcoded and not added the translation function with it.
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593851/
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593850/
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593853/

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to loco translate
2. BB platform plugin translation
3. Find the strings and translate those
4. See the strings on the frontend

**Expected behaviour**
The given string should be translatable

**Screenshots**
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593851/
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593850/
https://secure.helpscout.net/file/0c6c1f9d7be4e7d7/548143/4836927233/400593853/

**Environment**
Customer site
Local dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1656393764/168169?folderId=3709082

**Jira issue** : [PROD-721]

[PROD-721]: https://buddyboss.atlassian.net/browse/PROD-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Fixes #3048 

### How to test the changes in this Pull Request:

1. Go to loco translate
2. BB platform plugin translation
3. Find the strings and translate those
4. See the strings on the frontend

### Proof Screenshots or Video
1. Code: https://prnt.sc/1vtbref
Front End: 
Got to Move document popup : https://ibb.co/d6WF61D
Click on "create new folder": https://ibb.co/sQjkssh

2. Code: https://prnt.sc/1vtbt0d
Front End: 
Cancel uploading file to see message: https://ibb.co/jgbW3qk

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by amincdev** [comment]
@chetansatasiya I have made suggested changes.

**Review by chetansatasiya — DISMISSED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Issue >
I am not able to test this PR because when I select buddyboss plugin in loco translate at that time gives a fatal error. Can you please make sure about this?

Issue video:
https://www.loom.com/share/ca36466bf9af450eaeb0d6c8972e84da


cc @chetansatasiya @KartikSuthar

**Comment by amincdev** [comment]
> Hello @amincdev
> 
> Issue > I am not able to test this PR because when I select buddyboss plugin in loco translate at that time gives a fatal error. Can you please make sure about this?
> 
> Issue video: https://www.loom.com/share/ca36466bf9af450eaeb0d6c8972e84da
> 
> cc @chetansatasiya @KartikSuthar

@chetansatasiya @KartikSuthar Can you please check if this fatal error is because of the platform plugin or loco plugin has issue?

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed >
With the help of @krunal-buddyboss I've verified on the qa-ongoing branch and Now the new string is translatable for the prof please check the below video.

https://www.loom.com/share/a3254571f1ae4338aab59b22138bcf8f

Ready for release 🚀 

Thank you

**Comment by sumitbuddyboss** [comment]
Hello @amincdev


With the help of @krunal-buddyboss I've verified on the qa-approved branch and Now the new string is translatable for the prof please check the below video.

https://www.loom.com/share/e68bc1dc4d204e5695fd753130834dff

**Added comment here**
https://buddyboss.atlassian.net/browse/PROD-721?atlOrigin=eyJpIjoiODQ5NTg3ZWFhODdlNGU3ODkxNzhmMWM0ZGQ4ODZhNWQiLCJwIjoiaiJ9

Thank you

**Pull request merged**
