### PR TITLE
Fixed - Album title removed when we upload errored photos

### LINKED ISSUE #1636: Album title removed when we upload errored photos
**Describe the bug**
Album title is removed when photos uploaded below has some errors.

**To Reproduce**
1. Go to Album Create popup, type the title of the album
2. Upload some photos with more than the size limit provided by the server. usually 4 mb
3. Error will be shown about size close the popup of error.
4. See error that album title is gone.

**Expected behavior**
Album title should be as it is.

**Screenshots**
https://www.loom.com/share/83fcbb3e06ca432a9d659415b85fe4b2

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1636 

### How to test the changes in this Pull Request:

1. Go to Album Create popup, type the title of the album
2. Upload some photos with more than the size limit provided by the server. usually 4 mb
3. Error will be shown about size close the popup of error.
4. See now that album title is not reset.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
LGTM :rocket:

**Comment by chetansatasiya** [comment]
@ankitguptaindia Need to test

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

**Issue 1**
Still, the issue is as it is, the Album title is removed when photos uploaded below have some errors.

**Issue 2**
By mistake without entering the album name and If we create an album it'll give the validation error, then we enter the name then validation should be removed.
 
**Video proof for both of the issue**
https://www.loom.com/share/b2d8693111a74d5281efc27ce4b73ba2


CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss Issues are fixed and merged in `dev`, Please check it.

**Comment by amincdev** [comment]
@sumitbuddyboss 
This PR closed by mistake, Please follow progress on newly created PR: https://github.com/buddyboss/buddyboss-platform/pull/1761

**Pull request merged**
