### PR TITLE
Profile and Group Cover Image scaling

### LINKED ISSUE #1536: Profile and Group Cover Image scaling
**Is your feature request related to a problem? Please describe.**
Scale image of maximum resolution by 1950x450.

**Describe the solution you'd like**
IF image size upload is: 2700 x 900
Then cropped version will be 1950 x 650 (Proportionally)
IF image size upload is: 5000 x 900
Then cropped version will be 2500 x 450 (Proportionally)
2000x2000 will become 1950x1950
5000x200 no scaling possible
1200x1000 no scaling possible

https://github.com/buddyboss/buddyboss-theme/pull/444#issuecomment-693913759

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1536 

### How to test the changes in this Pull Request:

1. Go to profile > Cover Photo
2. Formed cover image upload as per the sizes below. 
IF image size upload is: 2700 x 900
Then cropped version will be 1950 x 650 (Proportionally)
IF image size upload is: 5000 x 900
Then cropped version will be 2500 x 450 (Proportionally)
2000x2000 will become 1950x1950
5000x200 no scaling possible
1200x1000 no scaling possible

### Proof Screenshots or Video
Original : http://prntscr.com/unnri5
Uploade: http://prntscr.com/unnrpf

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
@KartikSuthar approved!

@ankitguptaindia needs testing!

**Comment by sumitbuddyboss** [comment]
@sourabhmatolia @KartikSuthar 

I've checked above given all the resolution, but I've one query regarding that.

**Query:**
If we upload the image 5000x900 then we can not reposition the cover image but if we change the setting (BB theme option > Cover image > Cover Image Width - Full width and Height - Large then we can reposition the cover image so we need to keep as it is or can give change it?

For more detail please check the below video.

**Video:**
https://www.screencast.com/t/dM7gamLd

CC @ankitguptaindia

**Comment by sourabhmatolia** [comment]
@sumitbuddyboss 

Watched the video you shared above.
The way it is working right now in your video is good.
That's how it suppose to work.

Thanks.

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

Fixed!
I have Tested this on a branch buddyboss-platform fix/1536 and it's working as expected, This issue is resolved now. For proof please check the below video.

**Video:**
https://www.screencast.com/t/8bHozqPbw


CC @ankitguptaindia

**Review by sumitbuddyboss — APPROVED** [review]
@chetansatasiya  The related issue is resolved now and PR is ready to merge.

**Pull request merged**
