### PR TITLE
Fix mention usernames in comments when saving

### LINKED ISSUE #1229: Strange behavior in 'Post update' textarea focus when you post a particular type of comment.
**Describe the bug**

Ok, you want to publish some new content.
You click *once* on the text box.
Perfect. You're now able to write your content and publish it.
However, if you comment u@bug at any post (must be a comment, not a post) the bug happens.
So you want to publish any other post.
Um click on the text box once and you're not able to write your content as in the first time. You need to click again. And some times one more time.
And finally you're able to write your message.

It will happen even in the comments field as well as the post box, and to every user that try to post something.

**To Reproduce**
https://www.dropbox.com/s/0ubaclpr5ejf1dz/buddyboss.mov?dl=0

**Screenshots**
https://www.dropbox.com/s/0ubaclpr5ejf1dz/buddyboss.mov?dl=0

**Support ticket links**
https://secure.helpscout.net/conversation/1167195211/73826?folderId=3701249

### PR DESCRIPTION
**Pull request by mehulkaklotar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1229 

### How to test the changes in this Pull Request:

1. In activity comment, try to reply with mentioned username which is not in users at all and post it.
2. Now try to post activity update it should be posting without delay.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@ankitguptaindia need testing

**Comment by ankitguptaindia** [comment]
@mehulkaklotar @chetansatasiya 

When you perform same set of action in forums reply then you will see same issue.
Need to fix for other editor like Forums reply as well.

Please refer for details - https://www.loom.com/share/8e1991c88eba40a1979be376fb741d46

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar @chetansatasiya
> 
> When you perform same set of action in forums reply then you will see same issue.
> Need to fix for other editor like Forums reply as well.
> 
> Please refer for details - https://www.loom.com/share/8e1991c88eba40a1979be376fb741d46

@ankitguptaindia that whole thing is fixed in this PR https://github.com/buddyboss/buddyboss-platform/pull/1441

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

I am checking same issue after merging the branch but this not working for me.
Please refer - https://www.loom.com/share/45e62f03bd204fa38c3c71fcfbca8a29

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

**Issue /  Title-**.  Fix mention usernames in comments when saving

**Issue Link-** https://github.com/buddyboss/buddyboss-platform/issues/1229
**Status-** Issue has been fixed. Tested on Site wide activty, User specific activity, Group activity, Forums Reply etc.
**Proof-** https://www.loom.com/share/7e18ad7378e647df950babe17f554434

**Review by ankitguptaindia — APPROVED** [review]
**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [x] Tested negative test scenario

- [x] Updated Labels as per current status

**Final Update-** Ready to Release. 🚀

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
