### PR TITLE
fix/3090 - Add/fix object caching for dozens of objects, reducing redundant queries significantly

### LINKED ISSUE #3090: Many WP_Object_Cache groups are missing or have some bugs in them
**Describe the bug**
1. There are many instances in which functions try to add data to an object cache group, but the group was never created with wp_cache_add_global_groups.

2. In another instance (bp-friends-template.php), the group is created but the reference to it is missing in the wp_cache_get statement.

3. The function get_group_ids, which is called VERY often by groups_get_user_groups, does not cache its results, which creates considerable duplicate queries (14 for every search, for example). 

I will be submitting a pull request shortly to fix all of this.

**To Reproduce**

1 & 2 - Nothing needed to reproduce - just look at the submitted changes, search in the codebase for the group names, and you will see that they are called but have never been created.

3 - Install query monitor, do a full network search, and look at the 28 (14 twice) duplicate queries, run twice each by 7 different search helper files. 

**Expected behavior**
I would expect Object Caching to be made use of to its fullest capacity.

**Screenshots**
### 17 instances in 15 files where groups_get_user_groups is called, which never gets cached. 
image

One example is in a search, which creates 28 duplicate queries.
### Before fixing # 3
image

**Environment**
Which site did you replicate this issue on?

On both local development and webserver sites.

**Support ticket links**
Helpscout #170160

**Jira issue** : [PROD-711]

[PROD-711]: https://buddyboss.atlassian.net/browse/PROD-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by nickchomey**
Signed-off-by: nixsee <nick_chomey@hotmail.com>

### All Submissions:

* [x ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Various functions try to cache data, but about 20 cache groups that they refer to were never created. It would be nearly impossible to estimate how many duplicate queries are performed as a result of these caching groups not existing.

Also added a cache group and caching mechanism for the groups_get_user_groups() and get_group_ids () functions, which are called 17 different times in 15 different files, including 28 times in each network search, resulting in an enormous amount of duplicate database queries.

Fixes #3090 

### How to test the changes in this Pull Request:

1. Do a global search for the cache groups that have been added to confirm that functions are trying to use them
2. Install Query Monitor and do a network search. Look at the duplicate queries to see 28 (14 of two types) duplicate queries related to getting a user's groups. 
3. Apply these code changes and see that the duplicate queries disappear. 

### Proof Screenshots or Video

image

image

### Other information:

* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x] Have you written new tests for your changes, as applicable?
* [x ] Have you successfully run tests with your changes locally?

### Changelog entry

Added/fixed object caching for many BB components, dramatically reducing redundant database queries.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@sadrul Take a look into the changes and check once in all the places and add the groups in missing places.

**Comment by chetansatasiya** [comment]
> I should also mention that, other than the new user groups caching, I have only fixed the functions that have a caching mechanism but no cache group to actually use.
> 
> But there appear to be many other functions that could (should?) be cached as well. I hope that you will review the code and add caching where applicable.

@nickchomey Thank you for your contribution here. We will take a look and will work on missing places as also we are working on the performance improvement in many places so we will surely consider making all of the changes you suggested and also will work on the missing places.

**Comment by nickchomey** [comment]
@chetansatasiya It's my pleasure to be able to contribute, especially to something that you are currently focusing on. Please see the other issue (#3092) that I created - there are considerable duplicate queries as a result of the check_suspended_content cache being bypassed by every function that calls it. 

There also appear to be other checks throughout the codebase that don't even have caching yet, I mentioned some in that issue. I'm happy to help identify them more thoroughly if that would be helpful?

**Comment by sadrul** [comment]
Note: Merged into PR https://github.com/buddyboss/buddyboss-platform/pull/3055

**Pull request merged**
