### PR TITLE
Fixed - Duplicate New Reply Notification

### LINKED ISSUE #1880: Duplicate "New reply" Notification
**Describe the bug**
When someone replies to a discussion thread, the creator of the discussion receives 2 new reply notification with exact same time. 

**To Reproduce**
1. Create a new discussion
2. Reply to the discussion using different account ex: John (The creator of the discussion will receive 1 new reply notification) 
3. Again, switch to another user account ex: Maverick
4. Reply to John's reply 
5. Check the discussion creator notification. It will show 2 new notification which says "You have 1 new reply from Maverick" and "You have 1 new reply from John (again)"  Both notifications shows the exact same time (when Maverick replied).

**Expected behavior**
Will only receive one notification for the new reply

**Screenshots**
Screenshot_1

**Support ticket links**
https://secure.helpscout.net/conversation/1337221978/108674?folderId=3709080

### PR DESCRIPTION
**Pull request by nitishkaila**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?

### Changes proposed in this Pull Request:
I have updated the reply author id instead of the topic author id to fix multiple notifications.

Fixes #1880 .

### How to test the changes in this Pull Request:

1. Create a new discussion
2. Reply to the discussion using different account ex: Jessica (The creator of the discussion will receive 1 new reply notification)
3. Again, switch to another user account ex: Arianna
4. Reply to Jessica reply
5. Check the discussion creator notification. Only 1 notification should be display now.

### Proof Screenshots or Video

https://www.loom.com/share/4913ebaf072c4b77bc9909fc235608f3

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@nitishkaila Looks good to me.

Merge the branch into `dev` and add in testing.

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

Fixed > 

I have checked with the release branch and reproduced the issue (https://prnt.sc/12r9ljs) and then checked with dev branch and now  there is no any duplicate notifcation for discussion for the proof please check the below video

Video:
https://www.loom.com/share/e9c85ee1a1c14d9a8330fc4736a6bcfc

Ready for release 🚀 

Thank you

**Comment by chetansatasiya** [comment]
@sumitbuddyboss Can you retest this as I made some changes so?

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

I have rechecked from my end and it's working as expected for proof please check the video

Video:
https://www.loom.com/share/a78564c31a844e3f9bf09ea924950d89


Thank you

**Pull request merged**
