### PR TITLE
Fix - Redundant container when Creating a new Album

### LINKED ISSUE #2462: Redundant container when Creating a new Album
When we try to Create an Album from the Photos section, a redundant container can be seen in the backend

1. Go to 'Photos'
2. Click on 'Create Album'
3. The redundant container can be seen there behind the popup

Screenshot: https://prnt.sc/14eyz6x

**Expected behavior**
The container should not be there. .

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2462 

### How to test the changes in this Pull Request:

1. Go to 'Photos'
2. Click on 'Create Album'
3. There should be no uploader popup visible in the background

### Proof Screenshots or Video
https://ibb.co/R6gvQPK

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@amincdev Merged to dev and pass to QA.

**Comment by amincdev** [comment]
@sumitbuddyboss @mohit-buddyboss Merged in `dev` and ready for testing.

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

**Fixed >**

The related issue is resolved, Now create album popup looks proper. for the proof please check the below video.

Video:
https://www.loom.com/share/daaea689aa4b40f9aa5744296e23be9d

Ready for release 🚀 

Thank you

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA approved branch and it is working fine.
Here, I attached video for reference.
https://loom.com/share/7964b0da67564e8a89029e925a6e3eaa

Thanks!
CC : @sumitbuddyboss

**Pull request merged**
