### PR TITLE
PROD-954 #657 Change content of Forum, Reply and Discussion when user remove from system

### LINKED ISSUE #657: Change content of  Forum, Reply and Discussion when user remove from system
**Is your feature request related to a problem? Please describe.**
When a user is deleted from the system then all the data of the forum he/she created remain as it is.

**Describe the solution you'd like**
We will update the text of each forum, discussion and reply he/she created and will change the content to `This content was deleted.`

**Support ticket links**
If applicable, add Zendesk link or ticket number where the issue was originally reported.

**Jira issue** : [PROD-954]

[PROD-954]: https://buddyboss.atlassian.net/browse/PROD-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #657  .

### How to test the changes in this Pull Request:

1. Create a Forum, Discussion OR reply.
2. Now delete the user

### Proof Screenshots or Video

https://prnt.sc/rizz70

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by mehulkaklotar** [comment]
@chetansatasiya we need to implement something like asking user before deleting account if they want to delete their forum's data or not. something like that. 

Ref. https://bbpress.trac.wordpress.org/ticket/3116
https://buddypress.org/support/topic/delete-user-what-happens-with-his-data/
https://bbpress.org/forums/topic/deleting-users/

**Comment by AquaByteUK** [comment]
Be far better to leaving replies in place, as removing would make rest of thread possibly very disjunct. Also loss of threads could be a great lose to the community.

Would be better IMHO to copy what Facebook does here and leave in place with this user has left / no longer member or similar.

**Comment by nickchomey** [comment]
Agreed with @AquaByteUK. It would be catastrophic for my site - which is focused on communal knowledge generation/curation - if someone's posts were removed if they delete their account. it should just change any references to the user's name/profile to some placeholder {user no longer registered} or something like that.

**Comment by mehulkaklotar** [comment]
I agree with the suggestion of @AquaByteUK here.

@chetansatasiya I think we should not delete the content of topic or reply if user is deleted. We show Placeholder for user displayed name like `Deleted User` and for avatar we show placeholder image, the content will be as it is.

**Comment by AquaByteUK** [comment]
Alternatively at least an option, possibly granular but at least global to
set an option - delete or make anonymous / deleted user

**Pull request closed without merging**
