### PR TITLE
#2582 - fixed video button display issue on message compose page base…

### LINKED ISSUE #2582: video access control does not work in private message compose page
PR in buddyboss-platform-pro https://github.com/buddyboss/buddyboss-platform-pro/pull/176

**Describe the bug**
video access control does not work in private message compose page https://i.imgur.com/My7wkRY.png 

**To Reproduce**
1. Go to backend, buddyboss > settings > media > Media access
2. Set upload videos option
3. check frontend in private message compose page

**Expected behavior**
should work in private message

**Screenshots**
https://i.imgur.com/My7wkRY.png 

**Environment**
localhost

**Support ticket links**
n/a

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
added condition so that it checks the video access control settings

Fixes #2582 

### Related BuddyBoss Platform Pro PR
https://github.com/buddyboss/buddyboss-platform-pro/pull/176

### How to test the changes in this Pull Request:

1. Go to backend, buddyboss > settings > media > Media access
2. Set upload videos option
3. check frontend in private message compose page

### Proof Screenshots or Video
https://www.loom.com/share/da38d72c9137468ab399acd81e905363

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
Code LGTM 🚀 

@sadrul Merge in dev branch and put in testing.

**Comment by sadrul** [comment]
@sumitbuddyboss merged in dev and ready for testing
cc: @sourabhmatolia

**Comment by sadrul** [comment]
@chetansatasiya done with the changes requested by @mohit-buddyboss, ready for review code
cc: @sourabhmatolia

**Review by chetansatasiya — APPROVED** [review]

**Comment by sadrul** [comment]
@mohit-buddyboss merged in dev and ready for testing

**Comment by mohit-buddyboss** [comment]
@sadrul 

Tested on dev branch of the platform , Theme and Platform pro.
Now, user who don't have access to upload personal videos as per access settings that user when go to Group message thread on messages listing page then on clicking 'Video' icon in editor now drop down are to upload videos is appearing also user is able to send message successfully and other users of the group are able to receive that message successfully.

Video: https://loom.com/share/406469085fd54ae3b0263689089173dc

Related issues is resolve now and PR is ready for release. 

connected PR: buddyboss/buddyboss-platform-pro#176

cc @sourabhmatolia @chetansatasiya @KartikSuthar

**Pull request merged**
