### PR TITLE
#800 - BuddyBoss Email Header > can't select entire Logo

### LINKED ISSUE #800: BuddyBoss Email Header > can't select entire Logo
**Describe the bug**
While I am added Logo on BuddyBoss Email Header > can not select the entire logo and also there is no option to skip image crop.

**To Reproduce**
1. Go to 'Admin Dashboard - Buddyboss - Email'
2. Click on 'Customize Layout - Header - Upload logo'
3. See error

**Expected behavior**
Can select the entire logo or have a button to skip the image crop functionality.

**Screenshots**
https://www.loom.com/share/4f5021d4029d460eb141ceee7efabf71

### PR DESCRIPTION
**Pull request by sagarjadhav**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #800 .

### Proof Screenshots or Video

Added Skip Cropping button - https://prnt.sc/s5csiz
Fixed Logo width not working issue. https://prnt.sc/s5cs1c
Fixed User name alignment issue.

Email - https://prnt.sc/s5cunx

### Other information:

* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by eisenwasser** [comment]
@sagarjadhav 

The emails that get sent out look terrible if the logo has not been cropped.

Look at how a tall logo overlaps all of the content, and does not match the previewer at all.

email

**Comment by eisenwasser** [comment]
@ankitguptaindia 

Can you deep test this as Sagar fixes issues please.
The admin interface is good, I am more worried about the actual emails.

**Comment by ankitguptaindia** [comment]
@sagarjadhav 

When Checking preview in customizer  Setting. it looks good  - https://prnt.sc/s6p29f
But Real email sent like this - https://prnt.sc/s6p4nl

**Comment by ankitguptaindia** [comment]
@sagarjadhav 
After Deep Testing and playing with different-different use cases. I found issue is happening when Emails are getting sent related to WordPress core like: 
- Change of password, 
- Change of site admin email id, 
- Forgot user Password. 

IN such types of actions, Cropping image feature and image view is not working fine in email client.
https://prnt.sc/s6qlrc

If Emails are getting sent related to BuddyBoss/BuddyPress actions like group invitation, Personal Message, etc then logo are appearing fine in emails.
https://prnt.sc/s6qlex

Refer below video for more details.
https://www.loom.com/share/c854628bd5a642a296d2b85bdf0fa2ab

I created this fresh site to test this real email. you can use this-
http://ankit-qa.flywheelsites.com/
UN - salman
PW- salman@123

**Pull request merged**
