### PR TITLE
PROD-731 Fix - 404 error for "video-js-rtl.min.css" when using RTL site language

### LINKED ISSUE #3000: 404 error for "video-js-rtl.min.css" when using RTL site language
**Describe the bug**
Console error 404 error for "video-js-rtl.min.css" when using RTL site language
There is no rtl css files for buddyboss-platform/src/bp-core/css/vendor/video-js.css file. 

**To Reproduce**
1. With only BB Platform plugin active and default theme, change to any language with RTL format.
2. Visit any page on the frontend. See Error: https://prnt.sc/1u84pc6

**Expected behavior**
Should not show 404 error

**Screenshots**
https://prnt.sc/1u84pc6

**Environment**
dev site, demo site

**Support ticket links**
https://secure.helpscout.net/conversation/1641508321/165776?folderId=3709082

**Jira issue** : [PROD-731]

[PROD-731]: https://buddyboss.atlassian.net/browse/PROD-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #3000 

### How to test the changes in this Pull Request:

1. With only BB Platform plugin active and default theme, change to any language with RTL format.
2. Visit any page on the frontend. No, Missing file now.

### Proof Screenshots or Video
https://prnt.sc/1uq9k7d

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Comment by basil-buddyboss** [comment]
Retested in the QA ongoing branch.
Status: Not Fixed

Proof Screenshots or Video:
https://prnt.sc/1zryjsg

**Comment by amincdev** [comment]
> Retested in the QA ongoing branch. Status: Not Fixed
> 
> Proof Screenshots or Video: https://prnt.sc/1zryjsg

@basil-buddyboss Earlier fix branch was not merged in `qa-ongoing` but it is merged now. Please check it.

**Comment by basil-buddyboss** [comment]
Retested in the QA ongoing branch.
Status: Fixed

Proof Screenshots or Video:
https://watch.screencastify.com/v/I3q0YeWvLpvq7xJ0FDLr

**Comment by joeytoribio** [comment]
Hi @amincdev,

This has been tested in the qa-ongoing branch without any issues.

### Test Case:
404 error for "video-js-rtl.min.css" when using RTL site language

**Pre-Requisite:**
1] BuddyBoss Platform Plugin

**To Reproduce**
Steps to reproduce the behavior:

1] In your Dashboard, go to Settings > Site Language
2]  change to any language with RTL format.
2] Visit any page on the frontend

**Video:** 
https://www.loom.com/share/4b92af03ce2041a58e77c180fe1be6e8 

**Status: PASSED**

**Comment by basil-buddyboss** [comment]
Hi @amincdev 

This has been tested in the QA-approved branch and there were no issues encountered.

Result: Passed

**Pull request merged**
