### PR TITLE
#391 Fixed underscore "_" does not allow users to register

### LINKED ISSUE #391: Adding underscore "_" does not allow users to register
**Describe the bug**
Adding underscore "_" does not allow users to register gives 'Error: Sorry, Nickname may not contain the character ""!

**To Reproduce**
1. Place '_' in nickname.
2. Register. 
3. Error appears.

**Support ticket links**
https://secure.helpscout.net/conversation/1111985977/6372/
https://secure.helpscout.net/conversation/1111910557/507/

### PR DESCRIPTION
**Pull request by jaydeeprami**
### All Submissions:

* [X] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [X] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Allowed User to enter `_` or only numeric value in the `Nickname` field on Registration. Default Registration of WordPress does not prevent Users by validating it. 

- I have tested below Modules after removing this validation and works fine.
-  [X] Message
-  [X] Group
-  [X] Forum
-  [X] Register
-  [X] Xprofile
-  [X] Acivity
-  [X] Mention
-  [X] Email Invite

Fixes #391 

### How to test the changes in this Pull Request:

1. Place `_` or numeric value in Nickname
2. Register now
3. No Error appears now

### Proof Screenshots or Video

https://www.loom.com/share/eb2e872936ff4743b5392548951306dd

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?

@Anve-sri Please test it

### Changelog entry

> Fixed: underscore "_" does not allow users to register

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@ankitguptaindia Need to test this.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @jaydeeprami 

Tested via creating different-different types of users with  `dot` `hyphen` `underscore` `@` `numeric` listed as here https://prnt.sc/s96tmi 
Users are getting created successfully. Also tested with some basic feature of Plateform like messaging, join group, mentions, join forums changing nickname via edit profile.

Proof- 
https://www.loom.com/share/580d7b5962aa47788385f250df317401

-----

**Question related to same functionality -**  

If user is getting created from registration and user is using NickName with space like `Salman Khan Mumbai`  then this user is creating succcessfully with no space between text and All letters in small. Is this expected? 

Please check this video for detailed info - https://www.loom.com/share/7c4b89e0357b4dc7b905b73f75341160

**Comment by jaydeeprami** [comment]
@ankitguptaindia ,

Regarding your question,
`
If user is getting created from registration and user is using NickName with space like Salman Khan Mumbai then this user is creating succcessfully with no space between text and All letters in small. Is this expected?
`
> No it's not expected behavior. It's cause issue in `mention` functionality. I will fix this in PR.

**CC:** @chetansatasiya 

Thanks

**Comment by jaydeeprami** [comment]
@chetansatasiya , @ankitguptaindia 

I have fixed issues in registration validation.

- `test@`, `test 1` like Username not allowed. As it's cause issue in mention functionality tag feature.
https://www.loom.com/share/85c0f2f5f53b4280ab228357cf65a48f
___

- Also, there is one existing issue which not show error on the registration page if entered invalid Username and redirect the user to registration page without 
https://www.loom.com/share/e01ae05babec4fd0b2d12f77289127a6
- **[Fixed]**

**Comment by chetansatasiya** [comment]
@ankitguptaindia need to check again

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss  Pleas test this from scratch.
Thanks!

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @jaydeeprami 
Tested this by creating multiple users with `valid characters`   See this [Screenshot](https://prnt.sc/sc745k). It is working fine and now username/nickname field not accepting `@` , `Space` as valid characters. 

Also, tested related functionality like edit profile and tagging. Related functionality also working fine. Please check this [Video](https://www.loom.com/share/cff5034f3d094a44a30315b8e6669cc1)


**Suggestion :** 
Currently username can start with number. 

Expected : Username/nickname must not start with digit (Ex :- 01ugO) it must start with letter (Jay10) .

Effects :- If username starts with a number then it can effect order of user listing in back end. Because username which starts with digit (0-9) will remain top in the list. 

**CC** @ankitguptaindia

**Comment by jaydeeprami** [comment]
@mohit-buddyboss , 

Thank you for your suggestion but will allow only a `numeric` username. WordPress default registration also allows only a `numeric`  username.

CC @chetansatasiya

**Comment by mohit-buddyboss** [comment]
@jaydeeprami ,

May be we can consider it for future enhancement well, it's up to the team. 
#391 is Fixed. 

Thank you

**CC @ankitguptaindia**

**Pull request merged**
