### PR TITLE
The Preview appearing twice after posting on activity feed.

### LINKED ISSUE #830: The Preview appearing twice after posting on activity feed.
**Describe the bug**
The preview for the links appearing twice. 

**To Reproduce**
1. Go to 'Activity' page.
2. Post a link there. 
3. Click on 'Post Update'.
4. The previews appear twice. 

**Expected behavior**
Only one preview should appear.

**Screenshots**
https://prnt.sc/s8kgcu

**Support ticket links**
https://secure.helpscout.net/conversation/1149365511/70971?folderId=3709080

### LINKED ISSUE #843: Videos are posting twice/duplicated intermittently on Activity Feed
**Describe the bug**
When posting youtube videos, the video preview is showing twice.
This can be replicated on our demo, please post these links
https://www.youtube.com/watch?v=YEhW-rSaUmk&t=3s
short version: https://youtu.be/YEhW-rSaUmk

**To Reproduce**
1. On our demo, go to Activity feed
2. Paste youtube videos: https://youtu.be/YEhW-rSaUmk or https://www.youtube.com/watch?v=YEhW-rSaUmk&t=3s
3. Please try also posting  different youtube links

**Expected behavior**
Preview must not be shown twice

**Screenshots**
duplicate-vid

**Support ticket links**
https://secure.helpscout.net/conversation/1154621325/71786?folderId=3701258

### PR DESCRIPTION
**Pull request by mehulkaklotar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #830  .
Fixes #843
### Proof Screenshots or Video

https://prnt.sc/s8oap2

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@ankitguptaindia Need to test this.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @mehulkaklotar 

**Regression Issue-** 

1.  If using **Link + Text** in post then video preview is not working expected. Only text appears with lots of blank space. https://prnt.sc/saiss5
https://prnt.sc/saisy8
https://prnt.sc/saj1r2

2. If pressing enter then text and preview getting overlapped.  https://prnt.sc/saj2u7
3. If adding Text then Video link and after successful posting, on clicking Read more link on post, Preview becomes quotes text.   https://prnt.sc/saj8on



https://www.loom.com/share/de0f4e7790fe4f3f9d85dcb3e86b80c8

**Comment by mehulkaklotar** [comment]
> @chetansatasiya @mehulkaklotar
> 
> **Regression Issue-**
> 
> 1. If using **Link + Text** in post then video preview is not working expected. Only text appears with lots of blank space. https://prnt.sc/saiss5
>    https://prnt.sc/saisy8
>    https://prnt.sc/saj1r2
> 2. If pressing enter then text and preview getting overlapped.  https://prnt.sc/saj2u7
> 3. If adding Text then Video link and after successful posting, on clicking Read more link on post, Preview becomes quotes text.   https://prnt.sc/saj8on
> 
> https://www.loom.com/share/de0f4e7790fe4f3f9d85dcb3e86b80c8

@ankitguptaindia I have fixed all the issue above.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar If using ONLY Link then post has no any URL after published. https://prnt.sc/sani8w
BUT if using **Link+Text** then URL appears as a content.  https://prnt.sc/sanix6

Is it expected?

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar If using ONLY Link then post has no any URL after published. https://prnt.sc/sani8w
> BUT if using **Link+Text** then URL appears as a content. https://prnt.sc/sanix6
> 
> Is it expected?

@ankitguptaindia yes that is intended.

**Comment by ankitguptaindia** [comment]
> > @mehulkaklotar If using ONLY Link then post has no any URL after published. https://prnt.sc/sani8w
> > BUT if using **Link+Text** then URL appears as a content. https://prnt.sc/sanix6
> > Is it expected?
> 
> @ankitguptaindia yes that is intended.


Okay.. 👍 

-----------

Closing Remarks:-

The issue mentioned above in description have been fixed and some issues reported by me also got fixed.
- Tested these issues in Site wide activity, Member's Acitivity, and Group activity. 


This PR is ready for merge. 🚀

**Pull request merged**
