### PR TITLE
Fix - Video thumbnail should contain the wrapper rather then cover

### LINKED ISSUE #2816: Video thumbnail should contain the wrapper rather then cover
**Describe the bug**
When uploading a portrait video the generated thumbnail cover the whole video area and it does not look good.

**To Reproduce**
1. Go to Activity
2. Upload a potrait video
3. Check thumbnail

**Expected behavior**
Thumbnail should contain the video area like this: https://prnt.sc/1qf8rs6

**Screenshots**
https://prnt.sc/1qf8t4w

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2816 

### How to test the changes in this Pull Request:

1. Go to Activity
2. Upload a portrait video
3. Check thumbnail

### Proof Screenshots or Video
https://prnt.sc/1qfgtyx

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@amincdev merge in respective branches and give to QA.

**Comment by amincdev** [comment]
Merged in `qa-ongoing`

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I tested this PR in qa-ongoing branch, now portrait video thumbnail looks perfect.
See : https://loom.com/i/3888790128f1481e82846cf6bea6ae95

Ready for Release!

Thanks!

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I did verify this PR in qa-approved branch, now portrait video thumbnail is looks perfect.
--> https://www.loom.com/i/854ffcd1bc5047b3af87d237e096ae35

Thanks!

**Pull request merged**
