### PR TITLE
#1360 - Fix Document/Media/Video capability based on Group settings

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@ankitguptaindia We need to make sure this changes nothing new broke here when it comes to testing.

**IMPORTANT TO TEST:**

1. This change will not to effect anywhere in USER PROFILE functionality in Media and Documents and make sure when user creates folder/files in Profile then nobody have access to manage files other then document owner and same for media.
2. This changes will applied to only on Media and Documents in groups.
3. Need to make sure in any capacity we will not broke the ownership of the album, folder, photos and documents in groups.

**Review by mehulkaklotar — COMMENTED** [review]
@chetansatasiya looks good to me. We can start the testing. please merge it to `dev` and fix conflicts.

@KartikSuthar please check API based on this changes.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @mehulkaklotar 

After latest changes - Below scenario will create problem for Group Documents and Photos..

Say many Member A, B, C open the Group documents page on their screen at the same time. 
Member A moved the File-1 to his folder and on the same time Member B also moved the same File-1 on his folder without refreshing the group page.
In this scenario, Member A found the file has been lost from his folder. He couldn't find file in his folder bcoz File has been moved by Member B to his folder. 

Refer for more details - 

https://www.loom.com/share/46dc155cb3ec482aabfe61c2a202e336


------

Issue - Groups member can not move documents in Folder. It shows No folder available although group already having folder. 
https://www.loom.com/share/f1530cf404c14055b7abab7d507d9b81

-------

Issue - Group have multiple folders but it is showing only 1 folder when trying to move files (Move folder Popup issue)
https://www.loom.com/share/8ee8fc6aa9dc41af8ac06e6f94211495

---

When moving file to another folder then child folder is appearing but main parent folder does not appear. 

Say I have Folder `Father` and another folder `Child` .
Folder `Child` is sitting under Folder `father`
When I try to move document in folder father then father is not appearing only Child folder appearing in popup

https://www.loom.com/share/4b8c760e603147d6a3f6b55d7fcfb9fa

-----

Issue when Renaming Folder at a same time by multiple members. Member will think the folder has been deleted or not renamed properly.

https://www.loom.com/share/3585faa783c64219aa1c3942752a65b0

-----

Although All Group member have access to manage documents But they can not manage files uploaded by others member from activity feed.

If files are uploaded by themself then they can manage from activity page but can not manage if uploaded by other users.
Although can manage same files from Documents page.

https://www.loom.com/share/68e52636c8b94a5bad86b65effb855a5

---

Group member can not move image to another Album although have access to move photos from Group Setting.
It shows, you have not permission to move this files.

https://www.loom.com/share/5f9cd3aa77ad43bd871c234d364164ba

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Issues with Media Components - 



Add photos and Add Album options are appearing to users on global photos page  **for Logged out user.**. User can also see the popup to create album and upload images.
Doesn't make any sense to provide these options to Non logged in users.

https://prnt.sc/viko84
https://prnt.sc/vikozd

https://prnt.sc/vikpet



https://www.loom.com/share/f5ecbf0597a24eda9816bcc1ae0a702a

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Issues with Media Components -
> 
> Add photos and Add Album options are appearing to users on global photos page **for Logged out user.**. User can also see the popup to create album and upload images.
> Doesn't make any sense to provide these options to Non logged in users.
> 
> https://prnt.sc/viko84
> https://prnt.sc/vikozd
> 
> https://prnt.sc/vikpet
> 
> 
> https://www.loom.com/share/f5ecbf0597a24eda9816bcc1ae0a702a

@ankitguptaindia This is fixed and this issue is related `feature/media-document-enhancement` branch. I fixed this in `feature/media-document-enhancement` branch and merged in `dev` So now this is fixed.

**Comment by chetansatasiya** [comment]
> After latest changes - Below scenario will create problem for Group Documents and Photos..

> Say many Member A, B, C open the Group documents page on their screen at the same time.
Member A moved the File-1 to his folder and on the same time Member B also moved the same File-1 on his folder without refreshing the group page.
In this scenario, Member A found the file has been lost from his folder. He couldn't find file in his folder bcoz File has been moved by Member B to his folder.

> Refer for more details - https://www.loom.com/share/46dc155cb3ec482aabfe61c2a202e336

@ankitguptaindia @sourabhmatolia Need your thoughts here what should we can do here.

**Comment by chetansatasiya** [comment]
> Issue - Groups member can not move documents in Folder. It shows No folder available although group already having folder. https://www.loom.com/share/f1530cf404c14055b7abab7d507d9b81

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> Issue when Renaming Folder at a same time by multiple members. Member will think the folder has been deleted or not renamed properly. https://www.loom.com/share/3585faa783c64219aa1c3942752a65b0

@ankitguptaindia @sourabhmatolia Need your thoughts here what should we can do here.

**Comment by chetansatasiya** [comment]
> When moving file to another folder then child folder is appearing but main parent folder does not appear.

> Say I have Folder Father and another folder Child .
Folder Child is sitting under Folder father
When I try to move document in folder father then father is not appearing only Child folder appearing in popup

> https://www.loom.com/share/4b8c760e603147d6a3f6b55d7fcfb9fa

@ankitguptaindia This is fixed now can you retest this please?

**Comment by chetansatasiya** [comment]
> Issue - Group have multiple folders but it is showing only 1 folder when trying to move files (Move folder Popup issue) https://www.loom.com/share/8ee8fc6aa9dc41af8ac06e6f94211495

@ankitguptaindia This is fixed now can you retest this please?

**Comment by chetansatasiya** [comment]
> Group member can not move image to another Album although have access to move photos from Group Setting.
It shows, you have not permission to move this files. https://www.loom.com/share/5f9cd3aa77ad43bd871c234d364164ba

@ankitguptaindia We don't have **Move** functionality still in this branch right now you seeing **Move** button in `dev` branch because of the `feature/media-document-enhancement` branch. If you are in check in current `fix/1360` branch instead of `dev` then you will not see this button.

**Comment by sourabhmatolia** [comment]
@ankitguptaindia @chetansatasiya 

> After latest changes - Below scenario will create problem for Group Documents and Photos..
Say many Member A, B, C open the Group documents page on their screen at the same time.
Member A moved the File-1 to his folder and on the same time Member B also moved the same File-1 on his folder without refreshing the group page.
In this scenario, Member A found the file has been lost from his folder. He couldn't find file in his folder bcoz File has been moved by Member B to his folder.
Refer for more details - https://www.loom.com/share/46dc155cb3ec482aabfe61c2a202e336

> Issue when Renaming Folder at a same time by multiple members. Member will think the folder has been deleted or not renamed properly. https://www.loom.com/share/3585faa783c64219aa1c3942752a65b0

I don’t think we should worry about cases like this.
There will always be confusion if admin gives all access to everybody and all of them make changes to the same content at the same time.
If we give access to multiple members in Google drive Folder also, Members do changes at the same time in the same folder add/delete/move/rename, which will be confusing there as well.

So no problem here. Thanks.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @sourabhmatolia 

Is it possible to remove `feature/media-document-enhancement` branch from `dev`  for now ?
Some in-development things creating confusion here https://i.imgur.com/ZQ2NuUs.jpg

Due to these inprogress things, may be we miss some actual bug due to `fix/1360` changes.

**Comment by chetansatasiya** [comment]
> @chetansatasiya @sourabhmatolia
> 
> Is it possible to remove `feature/media-document-enhancement` branch from `dev` for now ?
> Some in-development things creating confusion here https://i.imgur.com/ZQ2NuUs.jpg
> 
> Due to these inprogress things, may be we miss some actual bug due to `fix/1360` changes.

@ankitguptaindia It's not possible to remove the changes and very tuffest job to do and not sure howmuch days it will take.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

SUGGESTION - Default Radio Button value

Would be great if we make default value of radio button for moderator and organizers only for album, photos and documents like Group messages.https://i.imgur.com/FMzl9MY.jpg

**Comment by ankitguptaindia** [comment]
@sourabhmatolia @chetansatasiya 

Giving access to all group members to manage all group media and documents is dangerous.

If organizer **allow** to manage then they can delete all others docs/media.
If organizer **don't allow** then member can not upload any docs/media.

Suppose, I have a Public group BB. In this group 50 members uploaded 200 files and folders. As this group is public so organizer don't have any restriction to manage joining/leaving the group.

After that a new user `Rock` join the public group and delete all files/folders/media uploaded by others member in that group and leave the group.
In this case, Group organizer and Members will not aware about deletion/changes done by Rock. They will always think where all files gone.
As well as this is public group so Organizer can not restrict anyone to join group. User can join and leave group any time. 

We should only give to manage own files/folders. 


On the other hand, if organizer don't allow to manage files/media to all member then those member can not upload any photos and documents. so this feature is not useful for those types of members who have no access to add media/documents.


Refer for more details - https://www.loom.com/share/d22bbc6545c44da0b20a84eccec814e5

we have same functionality for Activity. But this is managed properly.
Suppose All member is allowed to post activity in group. In this case member can only delete/edit own activity they can not edit others user's activity.
Refer-  https://www.loom.com/share/8d420d406a20464d836fdb10ed72118b


Please check and share your thoughts.

**Comment by sourabhmatolia** [comment]
@ankitguptaindia @chetansatasiya 

Let's discuss this further before proceeding. Thanks.

**Comment by sourabhmatolia** [comment]
@chetansatasiya 

**Task Logic UPDATE**

Here's the update finally on all the concerns here. This should fix permission related to this task properly.
What we had previously was not correct. What we have in this PR will also change little bit.

This is the logic we will go with:

- Media (Photos/Albums/Documents with Folders/Video) all should follow the same privacy logic as Activity.

- Current Logic for Activity is:

	- Group members allowed to Post activity based on Group settings (Allowed for all Members | Moderators | Organizers)

	- If members allowed to Post activity then they can add/edit/delete their own activity posts.

	- IF member group role is "Organizer" they can edit/delete other member's activity posts as well. They can add descriptions for other member uploaded media.

	- IF member group role is "Moderator" they can delete other member's activity posts. They cannot add descriptions for other members ' uploaded media AND they cannot edit other member's activities the way "Organizer" can.

	- Do cross-check this logic thoroughly and correct me if I am wrong. We have to redo everything if we miss out on anything.

- Same logic we will apply for Media:

	- Reword group settings for all media component
	From "Which members of this group are allowed to manage photos?"
	To "Which members of this group are allowed to upload photos?"

	- Group members allowed to Upload photos based on Group settings (Allowed for all Members | Moderators | Organizers)

	- If members allowed to upload photos they can add/delete/Add description for own photos.

	- IF member group role is "Organizer" they can edit description/delete other member's photos as well. 

	- IF member group role is "Moderator" they can delete other member's photos. They cannot add descriptions for other member uploaded media.
	
**Check video explaining the same in more details:**
https://www.loom.com/share/223712625df546899b8f135e981872bb

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Task Logic UPDATE**
> 
> Here's the update finally on all the concerns here. This should fix permission related to this task properly.
> What we had previously was not correct. What we have in this PR will also change little bit.
> 
> This is the logic we will go with:
> 
> * Media (Photos/Albums/Documents with Folders/Video) all should follow the same privacy logic as Activity.
> * Current Logic for Activity is:
>   
>   * Group members allowed to Post activity based on Group settings (Allowed for all Members | Moderators | Organizers)
>   * If members allowed to Post activity then they can add/edit/delete their own activity posts.
>   * IF member group role is "Organizer" they can edit/delete other member's activity posts as well. They can add descriptions for other member uploaded media.
>   * IF member group role is "Moderator" they can delete other member's activity posts. They cannot add descriptions for other members ' uploaded media AND they cannot edit other member's activities the way "Organizer" can.
>   * Do cross-check this logic thoroughly and correct me if I am wrong. We have to redo everything if we miss out on anything.
> * Same logic we will apply for Media:
>   
>   * Reword group settings for all media component
>     From "Which members of this group are allowed to manage photos?"
>     To "Which members of this group are allowed to upload photos?"
>   * Group members allowed to Upload photos based on Group settings (Allowed for all Members | Moderators | Organizers)
>   * If members allowed to upload photos they can add/delete/Add description for own photos.
>   * IF member group role is "Organizer" they can edit description/delete other member's photos as well.
>   * IF member group role is "Moderator" they can delete other member's photos. They cannot add descriptions for other member uploaded media.
> 
> **Check video explaining the same in more details:**
> 
> https://www.loom.com/share/223712625df546899b8f135e981872bb
> 
> **Note**
> IF Group members have access to Upload Media then they are allowed to upload media into their own or other member's Album/Folder.

@sourabhmatolia This is done accordingly you mentioned above.

**IMPORTANT** for @sumitbuddyboss & @mohit-buddyboss to test below things.

1. User Profile / Single Group & All the directory pages like Photos, Documents & Videos

>  Add/Edit/Delete/Download buttons in Photos/Albums/Documents/Folder to check based on access coming or not.

**Review by KartikSuthar — APPROVED** [review]

**Pull request merged**
