### PR TITLE
PROD-712#3088 Fix Video upload progress bar showing 100% and still it does not allow post update due to confusion

### LINKED ISSUE #3088: Video upload progress bar showing 100% and still it does not allow post update
**Describe the bug**
when we have the video upload progress bar showing the 100% and if the user clicks on post update the video does not get in the activity, actually it works only after the progress bar is removed so its the confusion many times as many times the progress bar is there on 100% for some time may due to processing/network delay

**To Reproduce**
1. Goto activity feed and upload the video
2. As soon as the progress bar shows 100%, click post update button
3. See error

**Expected behavior**
Post update button should be disabled until progress bar disappear completely

**Screenshots**
http://somup.com/cr6oX433Sq at time 6:20

**Environment**

**Support ticket links**

**Jira issue** : [PROD-712]

[PROD-712]: https://buddyboss.atlassian.net/browse/PROD-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by bb-yudhisthir**
Its the confusion with the actual file data been send to server shows "100% uploaded" but after that it takes time for our background process to save the attachment and create DB record etc. and then throws the response in the success event, so another approach is to move the lines of code for showing 100% uploaded from the "uploadprogress" event to the actual completion "success" event handler

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3088 .

### How to test the changes in this Pull Request:

1. Please check on server not on localhost
2. Goto activity feed and upload the large video, so it takes time to upload
2. Earlier as soon as the progress bar shows 100%, if clicked post update button it gave error, now check with this PR it will be no such issue
3. See error

### Proof Screenshots or Video
http://somup.com/cr6oX433Sq at time 6:20

After fix
https://somup.com/crX0Qa0FrU

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Moved "100% uploaded" display condition on the success event instead of uploadprogress event handler

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
LGTM 🚀 

@amincdev Need you review here

**Comment by amincdev** [comment]
@bb-yudhisthir 

**One scenario we need to work on:**
When progress will stuck before 99, like on 98 then the circle progress will indicate 100 but progress text will be 98.
https://ibb.co/fHN12W2

Need to sync both indications like this :
https://ibb.co/GRxW8CN

**Comment by bb-yudhisthir** [comment]
> @bb-yudhisthir
> 
> **One scenario we need to work on:** When progress will stuck before 99, like on 98 then the circle progress will indicate 100 but progress text will be 98. https://ibb.co/fHN12W2
> 
> Need to sync both indications like this : https://ibb.co/GRxW8CN

@amincdev Please check the progress is been also synced properly now
https://screencast-o-matic.com/watch/crXTeKVIpsN

**Comment by amincdev** [comment]
> > @bb-yudhisthir
> > **One scenario we need to work on:** When progress will stuck before 99, like on 98 then the circle progress will indicate 100 but progress text will be 98. https://ibb.co/fHN12W2
> > Need to sync both indications like this : https://ibb.co/GRxW8CN
> 
> @amincdev Please check the progress is been also synced properly now https://screencast-o-matic.com/watch/crXTeKVIpsN

@bb-yudhisthir Perfect now 👍

**Review by dipskakadiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Comment by kashimira8** [comment]
Retested in QA-ongoing branch
Status: Fixed
Screen Recording: https://www.loom.com/share/fdee2d6ceec046ff93ccefb5d98830de

**Comment by bb-yudhisthir** [comment]
> Retested in QA-ongoing branch Status: Fixed Screen Recording: https://www.loom.com/share/fdee2d6ceec046ff93ccefb5d98830de

@kashimira8 Please check the fix was not merged in the qa-ongoing branch, I have merged now. Please check again

**Comment by sumitbuddyboss** [comment]
@bb-yudhisthir 

One question here,

As mentioned in the issue **Expected behavior** https://github.com/buddyboss/buddyboss-platform/issues/3088#issue-1032501594
**Post update button should be disabled until the progress bar disappear completely**

Do we need to work on it?

cc @sourabhmatolia @firozwp 

Thank you.

**Comment by bb-yudhisthir** [comment]
> @bb-yudhisthir
> 
> One question here,
> 
> As mentioned in the issue **Expected behavior** [#3088 (comment)](https://github.com/buddyboss/buddyboss-platform/issues/3088#issue-1032501594) **Post update button should be disabled until the progress bar disappear completely**
> 
> Do we need to work on it?
> 
> cc @sourabhmatolia @firozwp
> 
> Thank you.

@sumitbuddyboss the issue was raised by me on my ticket already to @sadrul and I provided the suggestion may be we need any solution to remove the client confusion or either disable the button until but with this solution also it should be resolved now, so its not required now
cc: @sourabhmatolia @firozwp

**Comment by sumitbuddyboss** [comment]
Hello @bb-yudhisthir 

Thank for the update.

I have verified on the qa-ongoing branch and it's working as expected now. 

I have cross-check on 

- Newsfeed
- Album
- Group
- Group album
- Message
- Forums
- Video directory page.

Video proof:
https://www.loom.com/share/91f56d353c8b4ceab268c549c372fd47

Ready for release 🚀 

Thank you

**Comment by basil-buddyboss** [comment]
Hi @bb-yudhisthir 

This has been tested in the QA-approved branch and there were no issues encountered.

Result: Passed

**Comment by sourabhmatolia** [comment]
**UPDATE**

This is not done correctly. I will share more details later. Thanks.

**Review by amincdev — DISMISSED** [review]

**Pull request merged**
