### PR TITLE
Fix topic pagination

### LINKED ISSUE #2711: Forum > topics pagination is not working
**Describe the bug**
In Elementor page builder when insert Elementor Shortcode with  "[bbp-forum-index]", then pagination is not working.
This [bbp-forum-index] shordtcode is working with Add Block shortcode.

**To Reproduce**
1. Go to 'Elementor page'
2. Insert Elementor Shortcode and added "[bbp-forum-index]"
3. Forum topics Pagination is not working

**Expected behavior**
It should work after when [bbp-forum-index] use in Elementor Shortcode page builder.

**Screenshots**
https://www.loom.com/share/337055ce60a2498a93c2155b86a2e395

**Environment**
Dev site (https://dev-shyam.flywheelsites.com/)

**Support ticket links**
https://secure.helpscout.net/conversation/1573751911/153861?folderId=4265312

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2711

### How to test the changes in this Pull Request:

1. Go to 'Elementor page'
2. Insert Elementor Shortcode and added "[bbp-forum-index]"
3. Forum topics Pagination will be working now

### Proof Screenshots or Video

https://www.loom.com/share/d2467564c422429f9421108a2a39a711

### App Native issue

https://github.com/buddyboss/buddyboss-app-native/issues/1572

### CODE REVIEW

**Comment by shakilAshraful** [comment]
@varunqa I guess we can test in the app whether topic pagination on forum single screen is working properly or not, just to stay on the safe side.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@ngolwalkar I just tested and it's not working expected when the page has only topic shortcode.

**Review by chetansatasiya — APPROVED** [review]

**Comment by harshalQA** [comment]
Fixed added comment against the App native ticket.
Kindly check comment here: https://github.com/buddyboss/buddyboss-app-native/issues/1572#issuecomment-911472476

**Comment by mohit-buddyboss** [comment]
@ngolwalkar 

Tested on QA going branch of the platfrorm.
Now Topic pagination is working fine on directory page as well as page build by Elementor.
Video: https://loom.com/share/f23bee642c044116be6f03fff76b79b1

cc @sourabhmatolia @harshalQA @chetansatasiya

**Comment by JetalDobariya** [comment]
Hello, @ngolwalkar 

I did verify this PR in qa-approved branch, now topic pagination is working as expected.
Page number 2 : https://www.loom.com/i/08dd9f58464f4964b4461600c021ce16
Page number 4 : https://www.loom.com/i/b7b54a0a881f43c4aa598cefdaae53e8

Thanks!

**Pull request merged**
