### PR TITLE
#2006 add filter to skip strip out script

### LINKED ISSUE #2006: 3rd party js generated content does not show on privacy policy popup in login page
**Describe the bug**
If the below content is added to the privacy policy page, then the popup for the privacy policy link does not show any content on login page

`<div id="policy" data-policy-key="VGpkMGVpc3ZVSFlyVlVwMlRWRTlQUT09" data-extra="h-align=left&amp;no-title=true"></div><script src="https://app.termageddon.com/js/termageddon.js"></script>`

**To Reproduce**
1. Create a privacy policy page using the above content
2. Set this page as privacy policy page from BuddyBoss settings in backend
3. Check mark "Private Website" option in backend BuddyBoss > Settings > General > Privacy
4. Go to login page and click privacy policy link below the login form
5. See popup does not display any content

**Expected behavior**
The popup should display the content

**Screenshots**
https://www.loom.com/share/372a376d40c145788436ac1d5975c2b9

**Support ticket links**
https://secure.helpscout.net/conversation/1379272232/116745

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
- A sanitization function was protecting display js generated content but its not safe to remove the function
- So, a filter has been added to allow users to skip the sanitization function at their own risk which allows js generated content 

Fixes #2006

### How to test the changes in this Pull Request:

1. Use the filter "bp_privacy_policy_content" to skip using "wp_kses_post" function
2. Go to login page and click privacy policy link below the login form
3. See popup displays the content

### Proof Screenshots or Video
https://www.loom.com/share/d7b89a891e034308baa7044bcab6d4e3

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — DISMISSED** [review]
@sadrul This looks good to me!

Merge to dev and put it in testing!

**Comment by sadrul** [comment]
@ankitguptaindia @sumitbuddyboss @mohit-buddyboss Merged in `dev` and ready for testing.

**Comment by JetalDobariya** [comment]
Hello @sadrul 

I tested this PR in qa-ongoing branch, ow Privacy policy pop up content is visible.
See in the Video : https://www.loom.com/share/91413e1ca16a4f17b5789e8ec8f35f69
SS : https://www.loom.com/i/5664a63575d04703bfa17137d8b7abd9

Thanks!

**Review by chetansatasiya — DISMISSED** [review]

**Comment by JetalDobariya** [comment]
Hello @sadrul 

I did verify this PR in qa-approved branch, now privacy policy page pop up is appear with content.
--> https://www.loom.com/i/925b1415c49549fe848dd41c0e869efa

Thanks!

**Pull request merged**
