### PR TITLE
Set actual IDs for component pages

### LINKED ISSUE #2216: WooCommerce Memberships Restricted is not working for the Buddyboss default Pages
**Describe the bug**
Every single page in the BuddyBoss Component Pages is being bypassed. I've double-checked every page in incog and then did pages that aren't shown here and those remain protected. Buddyboss bypasses the protected status.

**To Reproduce**
https://www.loom.com/share/0d91addface64c3f9dd46f8ecacb44b8

**Support ticket links**
https://secure.helpscout.net/conversation/1430258440/126052?folderId=3955985

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2216 #1371 

### How to test the changes in this Pull Request:
**For the issue 1371**
    1. Install Yoast SEO plugin and buddyboss-platform
    2. Try to customize SEO description of some buddyboss page
    3. Open the page and see source code of page (CTRL+U)
    4. You should see description meta tag. It should be looks like this:
    5. `<meta name="description" content="Custom description of your page..." />`
    6. But you will not see the description meta tag.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by mehulkaklotar — DISMISSED** [review]
@krunal-buddyboss this looks good to me. please merge to dev and put it in testing.

**Comment by krunal-buddyboss** [comment]
Thanks @mehulkaklotar  Merged to Dev.
@mohit-buddyboss @sumitbuddyboss  
Please test all compoments page properly here as here it is major change. Thanks.
@chetansatasiya @mehulkaklotar @sourabhmatolia

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss

Meta title and description for /forums/ page is not getting change when we set Title and description through Yoast Plugin.
Tested on Dev branch. Used Yoast SEO Plugin.
Video : https://www.loom.com/share/8543441c94c24714a7d5c8a92966745b

**Comment by krunal-buddyboss** [comment]
@mohit-buddyboss 
Meta title and description for /forums/ page is getting change now when we set Title and description through Yoast Plugin. Please check once and confirm from your side as well. Thanks
@sourabhmatolia @chetansatasiya

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

Fixed> All 2 issues are resolved now.

FIXED > Now Title and description set by Yoast option are appearing for BuddyBoss default pages.
Video: https://www.loom.com/share/d6b284798bce43008bc2f4eb21848a8e

FIXED> WooCommerce Membership Restrictions are now working for BuddyBoss Default pages.
Video: https://www.loom.com/share/ac2a1e59d98a422eb54056fdb9c6f052

Related issue is resolved now and PR is ready to merge.

cc @chetansatasiya

**Pull request merged**
