### PR TITLE
Forums > Support @mentions

### LINKED ISSUE #269: Forums > Support @mentions
**Is your feature request related to a problem? Please describe.**
BuddyBoss Platform does not properly support using @mentions in forums. Currently if you type an @mention it will actually function once you publish the reply. However while typing the reply you will not see the dropdown auto-suggest box as you do in activity feed.

**Describe the solution you'd like**
We will add the ability to @mention users in Forums, with a dropdown auto-suggest box just like when mentioning users in activity feed. This does not require any new options; it will be a default functionality as long as Forums component is enabled. When you @mention a user in a forum, the user will receive a notification, same like if you mention them in an activity post. If Activity component is also enabled, then a new activity post will display as well, showing the user that they were mentioned in a forum post.

**Describe alternatives you've considered**
There are no plugins that allow for this currently.
Somehow WordPress.org is doing this already, maybe they open sourced their code?
https://wptavern.com/wordpress-support-forums-add-mentions-with-auto-complete

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/50168
https://buddyboss.zendesk.com/agent/tickets/53126
https://buddyboss.zendesk.com/agent/tickets/53423

### PR DESCRIPTION
**Pull request by mehulkaklotar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #269  .

### How to test the changes in this Pull Request:

1. Go to forums -> Add new topic
2. Type topic content in the editor and type @mention_user_name
3. It should show suggestion list of users

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Forums > @mentions support added.

### CODE REVIEW

**Comment by eisenwasser** [comment]
@mehulkaklotar 

If I disable Activity Feeds component, then go anywhere on frontend, entire site is a WordPress error now. https://prnt.sc/radp8h

**Comment by eisenwasser** [comment]
@mehulkaklotar 

Also, I'm not sure if this is intended to work when Activity component is disabled? That is what I was trying to test.

If so, that is broken also even after you fix the WP error. All the notifications from this link you to an activity permalink. Which would not work if Activity is disabled. It's also weird. I am being mentioned in a forum and the notification takes me to an activity post. That is not a nice experience, very confusing and makes me click around to find the forum reply where I was mentioned. The notification should take me directly to the forum reply where I was mentioned, with the hash in the URL to scroll me down to the specific reply.

**Comment by mehulkaklotar** [comment]
@eisenwasser All the topic and reply mentions will have now their own links instead of activity.

**Comment by eisenwasser** [comment]
@mehulkaklotar 

If you mention someone while in a hidden group or hidden forum, they get a notification which sends them to a 404. They should not get a notification.

https://www.loom.com/share/3a1da52848124a0fb66c7d7e0a554c7b

**Comment by eisenwasser** [comment]
@mehulkaklotar 

If activity component is disabled, mentions work but they send no notification at all. But logically, I don't understand why they would depend on activity component at all.

https://www.loom.com/share/8a9a466e0a2f48cb9f0e94355dc550a1

**Comment by eisenwasser** [comment]
@mehulkaklotar 

If a user changes their Nickname, all links to them in forums stop working.

But in activity all links to them continue to work fine.

**Comment by eisenwasser** [comment]
@mehulkaklotar 

All timestamps are off by 7 hours. https://prnt.sc/rdxure
Video - https://www.loom.com/share/e4f567eca5af4054a7325d9e54eb4e80

Every time.

**Pull request merged**
