### PR TITLE
#1406 - Fix private network issue

### LINKED ISSUE #1406: Public content option doesn't work when a page is created with WPML
**Describe the bug**
The public content option of Platform Privacy doesn't work when a page is created with the WPML plugin. 

**To Reproduce**
Steps to reproduce the behavior: https://www.loom.com/share/eba3491a3c7e47b4a7b1ec64da6fcadd

**Expected behavior**
The WPML translated page should remain publicly visible always. 

**Screenshots**
https://prnt.sc/u68fxx

**Support ticket links**
https://secure.helpscout.net/conversation/1257252943/88800
https://secure.helpscout.net/conversation/1302177831/102194/

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1406

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@mehulkaklotar This is Ready for you to review.

**Review by mehulkaklotar — APPROVED** [review]
approved!

@ankitguptaindia Needs testing here

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @mehulkaklotar 

This issue is appearing when user selects - This language URL format (https://prnt.sc/vijpl3). 
Verified this issue on **dev** and **fix/1406** branch. 
On dev branch this issue is still exist may be code not successfully merge into dev. So, Kindly check and verify code successfully merge or not. On **fix/1406** branch this issue is resolve.

Video: https://www.loom.com/share/daeac893531c4a5aa9ea230c8e7029ec

cc @ankitguptaindia

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED> Tested this on dev branch by creating page translated page through WPML . Enable Private network and added URL's into Public content. This issue is resolve now and PR is ready to merge.

Video: https://www.loom.com/share/7350ca4057fa44cc9afafc389e8d3691

cc @mehulkaklotar @ankitguptaindia

**Comment by tdx79** [comment]
Hi.
I can confirm problem is fixed with #1760

**Pull request merged**
