### PR TITLE
Text formatting editor issues

### LINKED ISSUE #855: Text formatting editor issues in forums.
**Describe the bug**
1) When you highlight a word before posting, click on the formatting button, then clicking on a selected format (e.g. Bold), it will de-highlight the word, then you need to highlight it again before you can click to apply the selected format.

2) "...in order for the text formatting tool to work, your insertion cursor cannot be in front of the text. Once moving the insertion cursor right one, it then works."

**To Reproduce**
1. Go to 'Forums'
2. Create a new 'Discussion'.

**Screenshots**
[format.zip](https://github.com/buddyboss/buddyboss-platform/files/4585915/format.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1152352783/71441/

### LINKED ISSUE #964: Discussion formatting elements not working properly.
**Describe the bug**
When you click once, the formatting do not apply and the option remains inactive. 

**Screenshots**
https://www.loom.com/share/a046d870296d4132b0760b19a2ff1fc4

**Support ticket links**
https://secure.helpscout.net/conversation/1154059146/71676?folderId=3701249

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #855
Fixes #964

### How to test the changes in this Pull Request:

1. Go to 'Forums', Activity, group message and Message screen
2. Check Editor

Follow this Video instruction: https://www.loom.com/share/a046d870296d4132b0760b19a2ff1fc4
### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by mohit-buddyboss** [comment]
@amincdev 

Tested this issue on branch `fix/855`. 

I have noticed two issues in 2 different browser firefox (78.0.2 (64-bit) and chrome (Version 83.0.4103.116).

**Chrome Browser Issue**: If the user posts text using the medium editor and turn that post into the BOLD and ITALIC format and along with it if selects blockquote or preformatted text option and post the update. Then after that, if the user tries to make a second update without a refreshing page then BOLD and ITALIC format get default selected in Medium editor due to which text appears default in BOLD and ITALIC format.

**Firefox Browser issue:** When the user highlights the text and then click on the formatting button then in firefox medium editor lets users select only one formatting option at a time. If the user wants to select multiple formatting options then the user requires to select text after clicking on the formatting button. 

Video Description of issues: https://www.loom.com/share/1f45b9efd186412c89078d8c662083b1

cc @chetansatasiya @mehulkaklotar

**Comment by amincdev** [comment]
@mohit-buddyboss Above issues are fixed now.

**Comment by mohit-buddyboss** [comment]
@amincdev 

The Firefox issue is resolved now. But the chrome browser issue is still appearing on forum discussions. Kindly see this video: https://www.loom.com/share/3012638d438545dc90d5e0c4c34c45c8


cc @chetansatasiya @mehulkaklotar

**Comment by amincdev** [comment]
@mohit-buddyboss Forum discussion is related to the theme and won't be possible to fix here. I will create a separate issue and PR in theme for you to test this.

**Comment by amincdev** [comment]
@mohit-buddyboss Apart from Forum discussion, if everything is fixed here then please approve this.
Thank you.

**Comment by mohit-buddyboss** [comment]
> @mohit-buddyboss Forum discussion is related to the theme and won't be possible to fix here. I will create a separate issue and PR in theme for you to test this.

@amincdev Okay, Kindly create a new issue for the theme. Yes, Apart from that Forum discussion issue on chrome browser rest is working fine.

cc @chetansatasiya @mehulkaklotar

**Review by chetansatasiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
