### PR TITLE
Wrong Nicknames generating after migrating to buddyboss-platform

### LINKED ISSUE #1308: Wrong Nicknames generating after migrating to buddyboss-platform
**Describe the bug**
When you go to buddyboss-platform from buddypress, some users will have the wrong auto-generated nickname.

**To Reproduce**
0. User should be registered in BuddyPress. 
1. Before migrating username (nickname) and user's Name (Fist and Last name) should be different
2. Try to migrate from buddypress to buddyboss-platfrom
3. See wrong Nicknames for some users.

**Note**
- The bug does not appear for all users. Sometimes Nickname looks good, sometimes not.
- Maybe user should have a gravatar account. Maybe user should use Russian language. Or maybe user should be registered from Social Login. I don't know. 
- If user registered in buddyboss-platform nickname will be right.

**Expected behavior**
Nickname should be exact as username in profile URL. (Nickname = Profile URL)

### Screenshots
**Example 1**
Username should be `airathalitov`, but it is `ajrat-halitov` (automatically generated from name "Айрат Халитов").
ajrat

---

**Example 2**
Username should be `mihailaoj13`, but it is `mihail-kratkov` (automatically generated from name "михаил кратков").
mihail

---

**Example 3**
Username should be `airat`, but it is `ajrat` (automatically generated from name "Айрат").
airat

---

Result for previous user (`airat`) in activity feed:
Ping with `@airat` nickname (which should be right) isn't working. 
act

---

In both cases, the nickname will not be available.
airat:
nickname
ajrat:
nickname2

### Solution
Add to **Tools > Repair Community** section (URL: `/wp-admin/admin.php?page=bp-repair-community&tab=bp-repair-community`) option to repair nicknames (copy from profile URL to Nickname) for all users. 
It will take a very long time to manually search for who have generated the correct Niсkname and who have not. It's easier to fix them automatically for everyone.

---

buddyboss-platfrom 1.4.7
_I saw this bug in early versions of buddyboss-platform and it is still relevant._

### PR DESCRIPTION
**Pull request by asaquzzamanbb**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1308 .

### How to test the changes in this Pull Request:

1. User should be registered in BuddyPress. 
2. Before migrating username (nickname) and user's Name (Fist and Last name) should be different
3. Try to migrate from buddypress to buddyboss-platfrom
4. See wrong Nicknames for some users.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@asaquzzamanbb Please merged to dev and pass to QA.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 

Merge with QA-ongoing branch.

**Comment by JetalDobariya** [comment]
Hello,

I did verify this PR related issue has been done , now nick name is appear as expected.

See Proofs : https://www.loom.com/share/972e4c11d9784c44946f0dacfba7910c

Thanks!

**Comment by JetalDobariya** [comment]
Hello ,

I did verify this PR in qa-approved branch, now username is not changing while we move BuddyPress to BuddyBoss plugin.
Buddypress plugin with default theme : https://www.loom.com/i/99b00af244784a3a9e24b090bf30c26a
Buddyboss platform plugin with Buddyboss theme : https://www.loom.com/i/380f619a83c64fc0ae47dd4dde60ef31

Thanks!
Jetal Dobariya!

**Pull request merged**
