### PR TITLE
872 - Added suggested label when user search for a blank string

### LINKED ISSUE #872: All results in search for blank string shows the quotation marks.
**Describe the bug**
If you click on search with no string mentioned , it shows double quotation marks in 'All results'.

**Expected behavior**
Should not show the quotation marks. 

**Screenshots**
[search.zip](https://github.com/buddyboss/buddyboss-platform/files/4602891/search.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1140460465/69444?folderId=3701249

### LINKED ISSUE #906: Using apostrophe(') in search displays backslash(\) on the result page
**Describe the bug**
Using apostrophe(') in search displays backslash(\) on the result page

**To Reproduce**
1. Go to front page
2. Search any keyword with apostrophe(')
3. Notice in the result page that there are backslashes added before the apostrophe(').

**Expected behavior**
There should be no backslashes

**Screencast**
https://drive.google.com/file/d/1hv9u05rXvzQcpwrXSUAQ5odSStGFT9_G/view

**Screenshots**
b2
b1

**Support ticket links**
https://secure.helpscout.net/conversation/1163576561/73270?folderId=3701263

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #872 
Fixed #906

### How to test the changes in this Pull Request:

1. click on search with no string mentioned

### Proof Screenshots or Video

https://www.loom.com/share/d87aab3be322406d86785057cbcad78b

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by janakkaneriya007** [comment]
Connected PR:  https://github.com/buddyboss/buddyboss-theme/pull/665

**Comment by mohit-buddyboss** [comment]
**@janakkaneriya007** 

Fixed . For proof see this [Video](https://www.loom.com/share/0458da9acf5e44a5a634e68254390181)

**CC @ankitguptaindia**

**Comment by janakkaneriya007** [comment]
@mohit-buddyboss 
Changes of https://github.com/buddyboss/buddyboss-platform/issues/906 issue has been added. Please retest it with latest changes.

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 
Fixed. For Proof kindly check this [Video](https://www.loom.com/share/5be8a04a97524851acb8cf97fe4c5c84)

**Comment by eisenwasser** [comment]
@mohit-buddyboss 

The PR is supposed to fix two issues, both are not fixed at all.

@KartikSuthar Please take over and fix this for real.

Video, showing very clearly that nothing is fixed even kind of. 
I can switch between this branch and dev, results are 100% identical in both branches.
https://www.loom.com/share/ae948523bcec4f51a453921affa569e1

**Comment by mohit-buddyboss** [comment]
@eisenwasser 

Sorry, i forgot to mention in my comment that this PR also have one connected PR : https://github.com/buddyboss/buddyboss-theme/pull/665 . 
So to check this issue we need fix version of both platform and theme. 

I have tested this issue with fix version of both platform and theme and as you can see in this [Video](https://www.loom.com/share/015a556a1d3e4522b3eb226b56a6d99b). Both the issues are resolved.

Thanks.

CC @KartikSuthar

**Comment by eisenwasser** [comment]
@mohit-buddyboss Thanks! Thats an important piece of info!

**Pull request merged**
