### PR TITLE
Fix - Unable to post a forum if page has a pop up from elementor

### LINKED ISSUE #3076: Elementor pro > Adding popup on pages throwing JS error by editor/medium-editor
**Describe the bug**
Adding a popup for all pages using elementor pro throwing js error on browser console in forum > reply page
when we typing something on the reply editor.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add elementor pro
2. Create popup > templates > popop> new (apply for all pages)
3. Save the popup settings
4. Open any forum topic and try to reply

https://www.awesomescreenshot.com/video/5666471?key=402cc2bf57152debde5ffd86d86b974e

**Expected behaviour**
Need to fix the js error.

**Screenshots**
https://ibb.co/rm95SDg
https://prnt.sc/1wlecw2

**Environment**
Customer site and local dev stage

**Support ticket links**
https://secure.helpscout.net/conversation/1657738589/168356?folderId=3709082

### LINKED ISSUE #3106: Unable to post a forum if page has a pop up from elementor
**Describe the bug**
Unable to post a forum if page has a pop up from elementor. Please see this video: https://www.loom.com/share/2b45131c5f5d444bb4259181005c10cf

**To Reproduce**
1. disable all other plugin except elementor, elementor pro, and bb platform
2. go to forums, stand alone or group forum
3. create new discussion - it will post as expected
4. go to dashboard, then templates > theme builder
5. create a pop-up template, add any content
6. conditionals - entire site, trigger - page load, advanced - show on browsers/ show on devices then publish
7. go to forum, stand alone or group forum
8. create new discussion - notice the console with editor error
9. submit the discussion only to return as no content on the discussion editor

**Environment**
Demo, local, dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1672631552/170439?folderId=3709082

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3106 
Fixes #3076

### How to test the changes in this Pull Request:

1. Create new elementor popup with page onload trigger add it for entire website
2. Go to any forum discussion
3. Create new discussion with dummy content, It should work without any error
4. Create new reply in any discussion with dummy content, It should work without any error

### Proof Screenshots or Video
https://www.loom.com/share/b44d6f9b68cb4c9f8ae160c7714956d6

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by KartikSuthar** [comment]
@amincdev 
`window.forums_medium_forum_editor = [];` L13
`window.forums_medium_reply_editor = [];` L114
`window.forums_medium_topic_editor = [];` L215
I think we need to remove this as well and define it globally.

**Comment by amincdev** [comment]
> @amincdev `window.forums_medium_forum_editor = [];` L13 `window.forums_medium_reply_editor = [];` L114 `window.forums_medium_topic_editor = [];` L215 I think we need to remove this as well and define it globally.

@KartikSuthar I have moved assignments to global scope.

**Review by KartikSuthar — APPROVED** [review]

**Comment by joeytoribio** [comment]
Hi @amincdev,

This has been tested without any error. Below is the steps were taken during the test.

Steps to reproduce the behavior:

1. Add Elementor Pro plugin and activate it
2. Under Template click Popup > Click Add New
3. Input the Details then click Create Template
4. Create your popup by adding text or images then Click Publish
5. Under Condition > add Include ""Enter Site"" 
6. Under Triggers turn on > On Page Load, On Scroll, On Scroll To Element, and On Click
7. Click Save and Close
8. Go to your site Forum
9. Popup should show, just click close or click anywhere to remove the popup
10. Create a new Discussion then click Post

Expected behavior: 
Should be able to submit a discussion or post a reply to a discussion

Video: 
https://www.loom.com/share/cc8a765afbf245a781663f47ecfa4519

Thank you!

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I did verify this PR in qa-approved branch, now if Elementor POP up is created for entire site then now user can able to create discussion and reply easily.
Site Discussion : https://prnt.sc/219rf9j
Backend Pop up : https://prnt.sc/219ro0d
Front Pop up : https://prnt.sc/219rvjz

Thanks!
CC : @joeytoribio @sourabhmatolia

**Pull request merged**
