### PR TITLE
Fixed Numbered list formatting issue

### LINKED ISSUE #1138: Numbered list formatting issue
**Describe the bug**
Numbered list formatting is not displaying well when there are multiple sub-lists. Video explanation:  https://drive.google.com/file/d/1OKzHcX-9D864Zfa-kP_zFZl-gsXFyxCA/view

**Expected behavior**
Main and sub list should intend well

**Screenshots**
Edit: Edit Entry
View: View

**Support ticket links**
- https://secure.helpscout.net/conversation/1211771504/80862
- https://secure.helpscout.net/conversation/1149650605/71022

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1138  .

### How to test the changes in this Pull Request:

1. Follow Video Explanation: https://drive.google.com/file/d/1OKzHcX-9D864Zfa-kP_zFZl-gsXFyxCA/view

### Proof Screenshots or Video

https://prnt.sc/te3ffs

### This PR is connected in Theme
https://github.com/buddyboss/buddyboss-theme/pull/833

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by sumitbuddyboss** [comment]
Fixed.  I have tested on platfrom -> fix/1138 and in theme -> fix/832 branch this issue is resolve now. For proof please check the below video.

**Video:**
https://www.loom.com/share/be49d910e4ea4562b362bbc2caf6524d

CC @ankitguptaindia

**Comment by amincdev** [comment]
@mohit-buddyboss JS file minified, Please test it now.

**Comment by mohit-buddyboss** [comment]
@amincdev 

Tested this on platform branch` fix/1138` and theme branch `fix/832` . Tested issue on pages and tabs where we are using medium editor Newsfeed page, Group Feed, a User profile feed, Forums replies, and discussion and for messages. 

But I've found new issue:

**Issue:** If numbered list number gets to enter in double-digit then the first digit of number gets hide on newsfeed page, group feed, and on user profile timeline. Screenshot: https://prnt.sc/tjoslj
Video: https://www.loom.com/share/63ff70e9e67e4431850f0a23d6327317

**Comment by amincdev** [comment]
@mohit-buddyboss This above issue is fixed now. Please take pull in theme branch `fix/832` and check.

**Comment by chetansatasiya** [comment]
@mohit-buddyboss @ankitguptaindia Can anyone take a look into this please?

**Review by chetansatasiya — APPROVED** [review]
@amincdev Code looks good to me.

@ankitguptaindia This need to be tested

**Comment by amincdev** [comment]
@ankitguptaindia This needs testing.

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss Your reported issue have been fixed. https://github.com/buddyboss/buddyboss-platform/pull/1169#issuecomment-660164877

Please verify this PR.

**Comment by mohit-buddyboss** [comment]
@amincdev FIXED. 
Tested this on platform branch fix/1138 and theme branch fix/832. Tested issue on pages and tabs where we are using medium editor Newsfeed page, Group Feed, a User profile feed, Forums replies, and discussion and for messages.

This issue is resolve now.

Proof : https://www.loom.com/share/cbb9a42a00ac4e5f82d0618761bef31e

Related PR : buddyboss/buddyboss-theme#833

cc @chetansatasiya @ankitguptaindia

**Review by mohit-buddyboss — APPROVED** [review]
Related Issue is resolved now and PR is ready to merge. 
cc @chetansatasiya

**Pull request merged**
