### PR TITLE
When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group

### LINKED ISSUE #1302: When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group.
**Describe the bug**
When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group. 
This issue occurs if you change the /forum/ slug to something else.

**To Reproduce**
1. Go to 'BuddyBOss >> Settings >> Forums' and change the forum slug.
http://prntscr.com/ttlkbq
2. Now open a Public group without joining the group and navigate to Discussion tab.
3. See, you can add a reply to the discussion without joining the group.

**Expected behavior**
If the user has not joined the group he should not be able to post to a discussion.

**Screenshots**
http://prntscr.com/ttlkbq

**Support ticket links**
https://secure.helpscout.net/conversation/1237485299/85307?folderId=3701248

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1302

### How to test the changes in this Pull Request:

1. Go to 'BuddyBOss >> Settings >> Forums' and change the forum slug.
http://prntscr.com/ttlkbq
2. Now open a Public group without joining the group and navigate to the Discussion tab.
3. See, you can add a reply to the discussion without joining the group.

### Proof Screenshots or Video
http://prntscr.com/ttr4op

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@KartikSuthar 👍 

@ankitguptaindia Need to test

**Review by mehulkaklotar — DISMISSED** [review]
@KartikSuthar 👍 

@ankitguptaindia needs testing!

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 
FIXED>Tested this the branch `fix/1302` of the platform.
Tested by changing slug of all items under forum settings, joining and leaving group. This issue is resolve now.
Video : https://www.loom.com/share/0b20eb196125478a8fdac231cdfeb82f

@mehulkaklotar

**Review by mohit-buddyboss — DISMISSED** [review]
Related issue is resolve now and this PR is ready to merge.

@mehulkaklotar

**Review by chetansatasiya — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
@KartikSuthar Approved! 🚀

**Pull request merged**
