### PR TITLE
Fix #1196 Group members can't see their hidden group on the Group Dir

### LINKED ISSUE #1196: Group members can't see their hidden group on the Group Directory.
**Describe the bug**
Group members can't see their hidden group on the Group Directory page. It works when the group privacy is public and private.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/006b8e3741e841bbbcbdf1fbab087e7e

**Expected behavior**
Group members should see their hidden groups.

**Support ticket links**
https://secure.helpscout.net/conversation/1218549643/82261

### PR DESCRIPTION
**Pull request by dipskakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The hidden group will be visible into the group directory for members also.

### How to test the changes in this Pull Request:

Steps to reproduce the behavior: https://www.loom.com/share/006b8e3741e841bbbcbdf1fbab087e7e

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
@dipskakadiya looks good to me!

Needs testing here.

**Comment by sumitbuddyboss** [comment]
Hello @dipskakadiya 

Fixed! 
Now The Group members can see their hidden group on the Group directories. The issue is resolved and it's working as expected
**Video**
https://www.loom.com/share/9a85552226e34eb78e889704c59b486f

**Invitation Issue**
But there is some issue in the group invitation section. Invitation section not seen.
https://www.loom.com/share/0fa1029a43954d5088417d25390c8764 


CC @ankitguptaindia

**Comment by dipskakadiya** [comment]
@sumitbuddyboss I fixed the issue. Please check it and let me know if anything wrong.

**Comment by sumitbuddyboss** [comment]
Hello @dipskakadiya 
Fixed! Tested on BB-Platform fix/1196-hidden-groups

The group invitation issue is resolved.
https://www.loom.com/share/047ae9e004854975afcd4d7fa825ab96



> @sumitbuddyboss I fixed the issue. Please check it and let me know if anything wrong.

**Review by sumitbuddyboss — APPROVED** [review]
@mehulkaklotar 
The related issue is resolved now and PR is ready to merge.

**Pull request merged**
