### PR TITLE
Fixed #770 Profile widget is not updated when we use Gravatar setting.

### PR DESCRIPTION
**Pull request by dipskakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes [#770](https://github.com/buddyboss/buddyboss-theme/issues/770) 

### How to test the changes in this Pull Request:

1. Register a user using the email address that is connected with Gravatar 
2. Open the profile page
3. Check the Complete your profile widget

### Proof Screenshots or Video

Screenshot 2020-09-04 at 8 37 38 PM

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@dipskakadiya Code looks good.

@ankitguptaindia Need to test on below places.

1. WP Widget
2. Elementor Widget.

**Comment by mohit-buddyboss** [comment]
@dipskakadiya 
Tested this on the branch `Fix/770`.

Tested this by registering three new users.

1) One who has a profile photo on email.
2) One who doesn't have a profile photo on email.
3) One who has a gravatar.

**Issue:**

1)The profile completion wizard Profile photo section is showing complete for the newly registered users who don't have any profile photo. See below video recording for an explanation from (2.13 to 5.20)
Video: https://www.loom.com/share/9d9b8c1546ec4646b6d463fba94bacda


2) Also, when I get login then on the page where the Profile widget is appearing below listed notices are appearing.

Notice: Undefined index: query in C:\laragon\www\mohitktest\wp-content\plugins\buddyboss-platform\src\bp-xprofile\bp-xprofile-functions.php on line 2081
Notice: Undefined index: d in C:\laragon\www\mohitktest\wp-content\plugins\buddyboss-platform\src\bp-xprofile\bp-xprofile-functions.php on line 2083

So, Kindly look into this.

**Comment by mohit-buddyboss** [comment]
@dipskakadiya 
Tested this on the branch `Fix/770` of the platform.
Issue : Now Profile completion widget not showing Profile section complete for user not having Profile photo. But when I registered email which have Gravatar then on registration it is not fetching Profile Photo. Previously for the same email Profile Gravatar was getting fetch. 
Video: https://www.loom.com/share/d9e516a885de4ca78b003fad92e95fa6

**Comment by mohit-buddyboss** [comment]
@dipskakadiya 
Tested this on the branch `Fix/770`.
Tested this by registering new users with or without gravatar.  Profile complete widget is working fine.
Video: https://www.loom.com/share/fc4c970249bd4a678eaf4dd4304d8778

@chetansatasiya  @mehulkaklotar

**Review by mohit-buddyboss — APPROVED** [review]
Related issue is resolve now and PR is ready to merge.

cc @chetansatasiya  @mehulkaklotar

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
