### PR TITLE
#1578 - Fix - Documents Download - Invalid file

### LINKED ISSUE #1560: Download media doesn't work when the media url contains "?" (signed url)
**Describe the bug**
I do use WP Offload Media to offload medias to S3 and I've configured the plugin in order to use private link for each media (url needs to be signed in order to be accessed and displayed).

The link "download" doesn't work on the image theater because some characters in the file url are replaced (for example, "?" is replaced by "_".

**To Reproduce**
- Use signed URL to access your media
- Go to "Photos" page
- Click on one photo to display the theater
- Click on the "Download" link (at the right bottom)

**Expected behavior**
- User should be able to download media even if the url is signed

**Screenshots**
image

image

**Support ticket links**
none

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fix #1560

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@chetansatasiya Approved. Please merge this PR to `dev` and assign for final review to @mehulkaklotar

**Review by mehulkaklotar — APPROVED** [review]
Looks good! 🚀

**Comment by ExoGeek** [comment]
@chetansatasiya maybe I'm wrong but don't you also have to update the function **bp_media_download_file** in the php file located in **bp-templates/bp-nouveau/includes/media/functions.php** ?

**Comment by ExoGeek** [comment]
@chetansatasiya If I understand correctly your changes, with strtok, you remove from the attachment URL, all the text after '?'.

But with a CDN using signed URL, if you try to access a file without a valid Key-Pairs, the file can't be accessed. 
When you try to download the file using bp_document_download_file_force, you have to use the full attachment URL.

`bp_document_download_file_force( wp_get_attachment_url( $attachment_id ) , $file_name );`

**Pull request merged**
