### PR TITLE
Fix - On Photos tab - text & dropdown is overriding

### LINKED ISSUE #2488: On Photos tab - text & dropdown is overriding
**Describe the bug**
After changing the tab https://prnt.sc/15citel from "Upload" to "Select Photo" and then change it back to "Upload", then the Dropdown and text are overriding 

**To Reproduce**
1. Go to 'Profile > Photos tab'
2. Click on 'Album > Select any album > Upload any image in the album'
3. After uploading an image, please change the tab  https://prnt.sc/15citel from "Upload" to "Select Photo" and "Select Photo" to "Upload" 
4. See error: https://prnt.sc/15cibpg

**Expected behavior**
Like: https://prnt.sc/15cjeka

**Screenshots**
https://prnt.sc/15cibpg

**Video**
https://www.loom.com/share/0e858a2747694a6180324c9c18556cd6

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2488 

### How to test the changes in this Pull Request:

1. Go to 'Profile > Photos tab'
2. Click on 'Album > Select any album > Upload any image in the album'
3. After uploading an image, please change the tab https://prnt.sc/15citel from "Upload" to "Select Photo" and "Select Photo" to "Upload"
4. Check UI

### Proof Screenshots or Video
https://ibb.co/G0n7tYz

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
LGTM 🚀 

@amincharoliya Merge in dev and add in testing.

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Please merge it to the dev branch.


Thank you

**Comment by amincdev** [comment]
@sumitbuddyboss Merged in `dev` and ready for testing.

**Comment by sumitbuddyboss** [comment]
Hello @amincdev

Fixed >
A related issue is resolved and now the Dropdown and text are display properly for proof please check the below video.

Video:
https://www.loom.com/share/b7bce41c9f994798a6a6164c59f861ba

Ready for release 🚀

Thank you

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch , now Create Album text UI is not break.
Here, I attached video for the reference.
https://www.loom.com/share/7cb51905b82547a3a76c76c0e31facea

Thanks!

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch , now Create Album text UI is not break.
Here, I attached video for the reference.
https://www.loom.com/share/7cb51905b82547a3a76c76c0e31facea

Thanks!

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch , now Create Album text UI is not break.
Here, I attached video for the reference.
https://www.loom.com/share/7cb51905b82547a3a76c76c0e31facea

Thanks!

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch , now Create Album text UI is not break.
Here, I attached video for the reference.
https://www.loom.com/share/7cb51905b82547a3a76c76c0e31facea

Thanks!

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch , now Create Album text UI is not break.
Here, I attached video for the reference.
https://www.loom.com/share/7cb51905b82547a3a76c76c0e31facea

Thanks!

**Pull request merged**
