### PR TITLE
Fix for showing empty space at the top of link preview and link is not hide when there is additional text

### LINKED ISSUE #2442: Showing empty space at the top of link preview and link is not hide when there is additional text
**Describe the bug**
1. There is an empty space showing up at the top of link preview when posting a single link.
2. The link is not hide when there an additional text along with link.

Please see the video in order to replicate the issue.
https://www.loom.com/share/e5d86bd0fbd44c68970790d66e8fc077

**Support ticket links**
https://secure.helpscout.net/conversation/1518295986/143098?folderId=4314898

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2442 #866 

### How to test the changes in this Pull Request:

1. Add link in the activity post area and create a post with link preview. You should not see any empty space at the top.
2. Create another activity post - this time add a link then add some additional text. The link should be hide from the activity post.
3. Youtube, vimeo video link will also work this way.
4. If there is multiple link added in the activity post then all links will be visible.

### Proof Screenshots or Video
https://www.loom.com/share/6d8cabc992f24cd08ef8ed323fc51037

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Removed empty space at the top of link preview.
> Improved link preview functionality

### CODE REVIEW

**Comment by mahedihasannoman** [comment]
@krunal-buddyboss 
Applied the following below changes as we have discussed.

1. Remove duplicate loop
2. update variable name to camel case
3. apply proper code formatting

Thanks

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@mahedihasannoman This is not working as expected. See the examples of how Facebook is doing.

1. Single URL with text - https://prnt.sc/1qvoiay
2. Single URL - https://prnt.sc/1qvokwo
3. Multiple URLs with additional text -  https://prnt.sc/1qvontg
4. Starting with text with multiple URLs - https://prnt.sc/1qvoq56

Multiple cases going fail.

**Comment by mahedihasannoman** [comment]
@chetansatasiya 
Link preview is now working like Facebook.

Single URL with text - https://prnt.sc/1qvxc8d
Single URL - https://prnt.sc/1qvxapv
Multiple URLs with additional text - https://prnt.sc/1qvxhld
Starting with text with multiple URLs - https://prnt.sc/1qvx09t

@KartikSuthar @krunal-buddyboss  @sourabhmatolia

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@mahedihasannoman I think we need to make the changes here as per this Trello card.
 https://trello.com/c/NHPwB1dn/776-link-embeds-dont-display-link-if-there-is-no-extra-text

This -- http://prntscr.com/o3ony7

Don't post the actual link to the video, unless the post contains additional text, then you can display the full post. If it's just a video link alone, then the post should be the video but not the text.

For link embeds that display as link cards, you can show the full link URL.

**Comment by mahedihasannoman** [comment]
@chetansatasiya I understand. I'm doing it.

**Comment by mahedihasannoman** [comment]
@chetansatasiya can you please check now and confirm.
`Don't post the actual link to the video, unless the post contains additional text, then you can display the full post. If it's just a video link alone, then the post should be the video but not the text.` - Done
https://prnt.sc/1qxsw6t
https://prnt.sc/1qxsx7h

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@mahedihasannoman Run the grunt so the minified file will generate.

**Review by chetansatasiya — APPROVED** [review]

**Comment by JetalDobariya** [comment]
Hello @mahedihasannoman 

I did test this PR's issues in the qa-ongoing branch but point number 2 issue is not resolved yet.
--> Link is not hide when i add few text with single link. (Link should be hide with additional text) 
See in the video : https://www.loom.com/share/395c58f915e0447fa99852b1efb3b158

Thanks!

**Comment by mahedihasannoman** [comment]
Hi @JeanDavidDaviet ,
It has been done according to facebook. Please see the comments here: https://github.com/buddyboss/buddyboss-platform/pull/2443#pullrequestreview-743605707

@chetansatasiya @KartikSuthar @krunal-buddyboss

**Comment by JetalDobariya** [comment]
Hello @mahedihasannoman 

Thanks for correcting!
I have checked this issue as per Added comment according to Facebook so it is working fine as expected.
See Proof : https://www.loom.com/share/0560d46c1e8046b4a48685f3f56e11b0

Thanks!  CC : @krunal-buddyboss

**Comment by JetalDobariya** [comment]
Hello,

I did verify this PR in qa-approved branch and it is working as expected : 
Single URL with text - https://www.loom.com/i/31141ec9a58a483e90bfd7a73b58f063
Single URL - https://www.loom.com/i/04f600a57d2c4226b93d8cd02a2a1fa9
Multiple URLs with additional text - https://www.loom.com/i/2a64816063bb42beb436b35b551f8993
Starting with text with multiple URLs : https://www.loom.com/i/a895f37f80ea4f32a1f2723954b24982

Thanks!

**Review by dipskakadiya — APPROVED** [review]

**Pull request merged**
