### PR TITLE
1566 - Fixed the issue with content, subject and link when Wishlist Member plugin is activated

### LINKED ISSUE #1566: Export Personal Data Confirmation email link is redirecting to 404
**Describe the bug**
When Requesting Data export, we receive a confirmation email like this https://prnt.sc/uprhr7
The confirmation link redirects to a 404 error.

The Wishlist Member Plugin https://www.buddyboss.com/resources/docs/integrations/wishlist-member/ is conflicting.
When WishList Member Plugin is active the email confirmation link is being converted into Uppercase.
Like this:
https://www.yourwebsitedo.com/WP-LOGIN.PHP?ACTION=CONFIRMACTION&REQUEST_ID=6477&CONFIRM_KEY=J6T3RXEJHFCAHWNVH3G7#%23%23
That is causing the 404 error.

**To Reproduce**
1. Go to '.Admin Dashboard' and activate the WishList Member Plugin.
2. Now go to profile account >> export data 
3. Request to Export Data.
4. You will receive an Email Confirmation.
5- Click on the confirmation link and See error.

**Screenshots**
https://prnt.sc/uprmag
https://prnt.sc/uprmne
https://prnt.sc/uprmww
https://prnt.sc/uprncy

**Support ticket links**
https://secure.helpscout.net/conversation/1288104972/99857?folderId=3701248

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1566.

### How to test the changes in this Pull Request:

1. Go to '.Admin Dashboard' and activate the WishList Member Plugin.
2. Now go to profile account >> export data
3. Request to Export Data.
4. You will receive an Email Confirmation.
5. Click on the confirmation link and See error.

### Proof Screenshots or Video
https://www.loom.com/share/b375f695db074b63b6258812ca8776b5?from_recorder=1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by janakkaneriya007** [comment]
@chetansatasiya @dipskakadiya 

Please review this PR.

**Review by dipskakadiya — APPROVED** [review]
@janakkaneriya007 Approved. @ankitguptaindia Ready for testing. PR merged in dev

**Comment by mohit-buddyboss** [comment]
Hello @janakkaneriya007 

Tested this on QA-ongoing branch of the platform when Wishlist member plugin is activate and deactivate.
Now correct link is appearing in email and user is able to confirm successfully.

Video: https://loom.com/share/832a33e501f64cdebee276bcf12e4e25
Video from requesting to downloading data : https://loom.com/share/3944d5ab5c234f6fbae339934a6f10f5

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @KartikSuthar @chetansatasiya

**Comment by JetalDobariya** [comment]
Hello @janakkaneriya007 

I did verify this PR in qa-approved branch, now confirmation link is working fine.

Thanks!

**Pull request merged**
