### PR TITLE
PROD-961 Added Followers tab into member directory page and profile page

### LINKED ISSUE #303: Add users Following me tab in site member page
Add "users Following me” tab (show member list whose "Following me” ) on the members page and when the user clicks on more link from “users Following me” widget will go to this tab.
Screenshot:- https://prnt.sc/q0j3xz
Video:-  https://www.loom.com/share/a59ea41175d34f8a845989028d14e369

**Jira issue** : [PROD-961]
 

[PROD-961]: https://buddyboss.atlassian.net/browse/PROD-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### LINKED ISSUE #871: Members Following Me widget setting is not working properly
**Describe the bug**
When using **(BB) Members Following Me** widget, setting the "**Max members to show**" is not working when more than 20 is set to be displayed. Also, more button only redirects to members page.

**To Reproduce**
1. Try to use **(BB) Members Following Me** widget
2. Set the **Max members to show** to more than 20
3. Go to a member with more than 20 followers

**Expected behavior**
The **Max members to show** setting should work properly

**Screenshots**
set-30
members-followers

**Support ticket links**
https://secure.helpscout.net/conversation/1154430495/71749?folderId=3701263

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #303 

### How to test the changes in this Pull Request:

1. Try to use (BB) Members Following Me widget
2. Set the Max members to show to more than 20
3. Go to a member with more than 20 followers

### Proof Screenshots or Video

https://prnt.sc/sehkpl
https://prnt.sc/sehl6e
### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed the max number arguments in widget

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@janakkaneriya007 `bp_has_members` function have a `$max ` like howmany you want then why we need to change `$max ` to `per_page` ?

**Comment by KartikSuthar** [comment]
> @janakkaneriya007 `bp_has_members` function have a `$max ` like how many you want then why we need to change `$max ` to `per_page` ?

@chetansatasiya, I have changes to `per_page` as `max` will work in case it will be lower than `per_page`. http://prntscr.com/t0ikd6
In the case default `per_page=20` and set `max=30` it will show the 20 results not more than that.

**Comment by ankitguptaindia** [comment]
@KartikSuthar @mehulkaklotar 

Issue- 1 ((BB) Members Following Me ) I can not see next members listing after first list . No Options to move on Next listing.
Same happening with another widget (BB) Members I'm Following. 

Issue -2, when using this fixed branch, many php notices appearing here. 
https://i.imgur.com/3mz70Kn.jpg


Notice: Trying to access array offset on value of type int in /Users/ank/Local Sites/my-qa/app/public/wp-includes/formatting.php on line 904

https://www.loom.com/share/e7f9052d60a240fd81b0fa1bfd6ff2e2

**Comment by mehulkaklotar** [comment]
@KartikSuthar Please fix issues mentioned by @ankitguptaindia here. And then put it to review again.

**Comment by KartikSuthar** [comment]
@ankitguptaindia 

> Issue- 1 ((BB) Members Following Me ) I can not see next members listing after first list . No Options to move on Next listing.
> Same happening with another widget (BB) Members I'm Following.
> 
When you view logged in user's profile you can see the more button. http://prntscr.com/teljx9
and when you click on it it will redirect you on the member's page with appropriate tabs: http://prntscr.com/telklz
But when you view other's profile there is no place to see all Following/Followers of the displayed user.

> Issue -2, when using this fixed branch, many php notices appearing here. And switch to dev then no notices.
> May be those are fixed in Dev branch so please merge dev in this branch as well.
>
Merged dev branch and not getting any errors.

**Comment by KartikSuthar** [comment]
@ankitguptaindia @mehulkaklotar 

I have added Followers and Following tabs on the user profile as well as the member directory. Please review.
http://somup.com/cYioQeQ9k0

Theme PR: https://github.com/buddyboss/buddyboss-theme/pull/855

**Review by mehulkaklotar — DISMISSED** [review]
👍  code looks good.

**Review by mehulkaklotar — DISMISSED** [review]
@ankitguptaindia needs testing here.

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

**Issue:**
Link is not working properly for widget "I’M FOLLOWING" and "MY FOLLOWERS" Please check the below video for more detail.
https://www.loom.com/share/c9a843a64cf94b39bb21c34173d135c8

**Comment by KartikSuthar** [comment]
> Hello @KartikSuthar
> 
> **Issue:**
> Link is not working properly for widget "I’M FOLLOWING" and "MY FOLLOWERS" Please check the below video for more detail.
> https://www.loom.com/share/c9a843a64cf94b39bb21c34173d135c8

Hey @sumitbuddyboss Fixed. Please re-test.

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

Issue >
I have checked in fix/871 and dev branch and still, I'm getting the same issue the Link is not working properly for widget "I’M FOLLOWING" and "MY FOLLOWERSfor the proof please check the below video.

Video:
https://www.loom.com/share/22121f4519d449c896bd5bd16e1bd60c


Thank you

**Comment by sourabhmatolia** [comment]
UPDATE

I will get back to you for this task on the new scope.

**Pull request closed without merging**
