### PR TITLE
Add email/password fields to the Profile Fields > Signup tab

### LINKED ISSUE #2359: Add email/password fields to the Profile Fields > Signup tab
**Is your feature request related to a problem? Please describe.**
Site admins can not control where the email, confirm email, password and confirm password fields show in their registration form. 

**Describe the solution you'd like**
Add the fields to the Profile Fields > Signup page as required signup fields, like the First Name, Last Name and Nickname fields are:

Screen Shot 2021-04-22 at 1 07 30 PM

Only show confirm email/password, if those settings are activated:

Screen Shot 2021-04-22 at 1 07 35 PM

### API Issue
https://github.com/buddyboss/buddyboss-platform-api/issues/340

**Jira issue** : [PROD-825]

[PROD-825]: https://buddyboss.atlassian.net/browse/PROD-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2359 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### API PR
https://github.com/buddyboss/buddyboss-platform-api/pull/341

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by janakkaneriya007** [comment]
**Discussion Note:**
As per the discussion with @sourabhmatolia here: https://buddyboss.slack.com/archives/DNP69H739/p1631791965010000
We are moving the hooks as per the requirements.

**Comment by sourabhmatolia** [comment]
**UPDATE**

Talking to Mikey on how we proceed further here.

**Comment by sourabhmatolia** [comment]
**Based on discussion with Mikey sharing further Clarification on scope shared above**

**Check Video:**
https://www.loom.com/share/e19567b7d2ec47d48e457fcb25f3f977

**Comment by krunal-buddyboss** [comment]
@sourabhmatolia 
I am going to close this PR as we have created new PR https://github.com/buddyboss/buddyboss-platform/pull/3073 for this issue.

**Pull request closed without merging**
