### PR TITLE
Fix document and folder privacy

### LINKED ISSUE #1094: Documents - Group Document User Access
**Describe the bug**
When Group Documents setting set to all members then currently all the members are deleting each other memebers documents and folders.

**To Reproduce**
1. Go to Group and click on Manage 
2. Set Document manage to all members
3. Now in Group all the users can delete/edit and move eachother folders and documents.

**Expected behavior**
User can Edit/Delete and Move only his/her documents and folders.

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### LINKED ISSUE #1100: Media - Privacy Issue on User Activity Page
**Describe the bug**
When 2 users friend of eachother  and if 1 user creating a activity with media photo then 2nd user activity page media is not showing.

**Expected behavior**

**Screenshots**
image (3)

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by chetansatasiya**
**Theme Branch** https://github.com/buddyboss/buddyboss-theme/pull/797

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1094 
Fixes #1100 

### How to test the changes in this Pull Request:

1. Go to Group and click on Manage 
2. Set Document manage to all members
3. Now in Group all the users can delete/edit and move eachother folders and documents.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@ankitguptaindia @mohit-buddyboss I need you guys testing here.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar @chetansatasiya 

**Regression Issue 1 -** Any Group member can Delete, Edit, Modify other's person album in Group if set access to 'All group members'.

Refer Video for Detailed info- https://www.loom.com/share/8b7040d7e88b4ad6bbb253dd5ded17a4


**Regression Issue 2 -**  If Uploading Photos from GroupName/photos page then photo NOT HAVING Sidebar options in preview.  (Sidebar Has BLANK while space)

https://www.loom.com/share/5693caa6624b4d7e9868de396b84429a

**Regression Issue 3 -**  Right Navigation arrow in preview is not appearing anymore.

https://www.loom.com/share/bd9f5460f9bb40c9bdf0491e5d6fddea



FYI- 
Theme Branch- Master
Plugin Branch -  fix/group-document-folder-privacy   with up to date code. https://prnt.sc/t8c0xt

**Comment by chetansatasiya** [comment]
> @mehulkaklotar @chetansatasiya
> 
> **Regression Issue 1 -** Any Group member can Delete, Edit, Modify other's person album in Group if set access to 'All group members'.
> 
> Refer Video for Detailed info- https://www.loom.com/share/8b7040d7e88b4ad6bbb253dd5ded17a4
> 
> **Regression Issue 2 -** If Uploading Photos from GroupName/photos page then photo NOT HAVING Sidebar options in preview. (Sidebar Has BLANK while space)
> 
> https://www.loom.com/share/5693caa6624b4d7e9868de396b84429a
> 
> **Regression Issue 3 -** Right Navigation arrow in preview is not appearing anymore.
> 
> https://www.loom.com/share/bd9f5460f9bb40c9bdf0491e5d6fddea
> 
> FYI-
> Theme Branch- Master
> Plugin Branch - fix/group-document-folder-privacy with up to date code. https://prnt.sc/t8c0xt

@ankitguptaindia All of above issues are fixed in Media and also need to test this thing in Document as well.

**Comment by ankitguptaindia** [comment]
@chetansatasiya Above issue have been fixed and working expected. Cross Tested.  

Another regression BUG - User can modify/delete/upload files/ create folder etc in Other's user folder by using 3 dots after reaching in folder inside.
Works fine if user is checking on Documents root folder. 
 https://prnt.sc/t8ijpk

https://www.loom.com/share/ef6f96a439724df59e9f27680b6240ff

**Comment by chetansatasiya** [comment]
> @chetansatasiya Above issue have been fixed and working expected. Cross Tested.
> 
> **Another regression BUG -** User can modify/delete/upload files/ create folder etc in Other's user folder by using 3 dots after reaching in folder inside.
> Works fine if user is checking on Documents root folder.
> https://prnt.sc/t8ijpk
> 
> https://www.loom.com/share/ef6f96a439724df59e9f27680b6240ff

@ankitguptaindia This is fixed now 👍 Good Catch

**Comment by ankitguptaindia** [comment]
@chetansatasiya Thanks for fixed.  Let me cross check once

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**New Regression Issue -** This was not working in this way before.
> When moving file or folder to another newly created folder from popup, it shows not folder I have although I just created new folder on fly and Move button is active. but message if wrong.


https://www.loom.com/share/cdd131eb2bb4431f8b963a66527bb9c1

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**New Regression Issue -** BLANK folder getting downoaded although folder having files and folders

https://www.loom.com/share/d22163fedc48422ab31ec7e7fad68ace

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **New Regression Issue -** This was not working in this way before.
> 
> > When moving file or folder to another newly created folder from popup, it shows not folder I have although I just created new folder on fly and Move button is active. but message if wrong.
> 
> https://www.loom.com/share/cdd131eb2bb4431f8b963a66527bb9c1

@ankitguptaindia This is fixed now

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**NEW REGRESSION ISSUE_**  Site get down (message like This page isn’t working) without informative details when downloading the folder. 
https://prnt.sc/t8xery

Steps are explained in video- 
https://www.loom.com/share/82b64eac72354907a073e848ec508550

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **New Regression Issue -** BLANK folder getting downoaded although folder having files and folders
> 
> https://www.loom.com/share/d22163fedc48422ab31ec7e7fad68ace

@ankitguptaindia This is fixed 👍  Can you verify?

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **NEW REGRESSION ISSUE_** Site get down (message like This page isn’t working) without informative details when downloading the folder.
> https://prnt.sc/t8xery
> 
> Steps are explained in video-
> https://www.loom.com/share/82b64eac72354907a073e848ec508550

@ankitguptaindia This is fixed 👍   Can you verify?

**Comment by ankitguptaindia** [comment]
> > @chetansatasiya Above issue have been fixed and working expected. Cross Tested.
> > **Another regression BUG -** User can modify/delete/upload files/ create folder etc in Other's user folder by using 3 dots after reaching in folder inside.
> > Works fine if user is checking on Documents root folder.
> > https://prnt.sc/t8ijpk
> > https://www.loom.com/share/ef6f96a439724df59e9f27680b6240ff
> 
> @ankitguptaindia This is fixed now 👍 Good Catch

This is Fixed. Woking expected now. 



> @chetansatasiya
> 
> **New Regression Issue -** This was not working in this way before.
> 
> > When moving file or folder to another newly created folder from popup, it shows not folder I have although I just created new folder on fly and Move button is active. but message if wrong.
> 
> 
> https://www.loom.com/share/cdd131eb2bb4431f8b963a66527bb9c1

This is Fixed..

**Comment by ankitguptaindia** [comment]
> > @chetansatasiya
> > **New Regression Issue -** BLANK folder getting downoaded although folder having files and folders
> > https://www.loom.com/share/d22163fedc48422ab31ec7e7fad68ace
> 
> @ankitguptaindia This is fixed 👍 Can you verify?

This is fixed. 👍

**Comment by ankitguptaindia** [comment]
> > @chetansatasiya
> > **NEW REGRESSION ISSUE_** Site get down (message like This page isn’t working) without informative details when downloading the folder.
> > https://prnt.sc/t8xery
> > Steps are explained in video-
> > https://www.loom.com/share/82b64eac72354907a073e848ec508550
> 
> @ankitguptaindia This is fixed 👍 Can you verify?

@chetansatasiya 
This is same as previous for me https://www.loom.com/share/48c680c6924149c88fe97532be90b637

**Comment by chetansatasiya** [comment]
> > > @chetansatasiya
> > > **NEW REGRESSION ISSUE_** Site get down (message like This page isn’t working) without informative details when downloading the folder.
> > > https://prnt.sc/t8xery
> > > Steps are explained in video-
> > > https://www.loom.com/share/82b64eac72354907a073e848ec508550
> > 
> > 
> > @ankitguptaindia This is fixed 👍 Can you verify?
> 
> @chetansatasiya
> This is same as previous for me https://www.loom.com/share/48c680c6924149c88fe97532be90b637

@ankitguptaindia Awesome catch this is fixed now 👍

**Comment by ankitguptaindia** [comment]
UPDATE- Paused testing of this PR as developer is doing some code changes. Will resume Testing again when ready for test.

**Comment by chetansatasiya** [comment]
> **_UPDATE- Paused testing of this PR as developer is doing some code changes. Will resume Testing again when ready for test._**

@ankitguptaindia As discussed in today's call I did all the changes on the Media and Documents and it's ready for you to test tomorrow. 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Issue-1, Previously we have given option to Move files and folder to Group Organizer, Group Moderator and site admin BUT now these users can not move files uploaded bu group members in groups.

Have we restricted Move function only for File/Folder Owner ??


Issue-2, Group Organizer, Group Moderator and site admin CAN NOT rename Files uploaded by other members although RENAME option appearing to all users. When these user try to rename then it show.  `You don't have a permission to rename the document.`
https://prnt.sc/tb3eqe

https://www.loom.com/share/3f9b1fccaea741e69b71597e299bc4df

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Issue-1, Previously we have given option to Move files and folder to Group Organizer, Group Moderator and site admin BUT now these users can not move files uploaded bu group members in groups.
> 
> Have we restricted Move function only for File/Folder Owner ??

@ankitguptaindia Yes, we restricted all the peoples except the owner of that document/folder.

**Comment by chetansatasiya** [comment]
> Issue-2, Group Organizer, Group Moderator and site admin CAN NOT rename Files uploaded by other members although RENAME option appearing to all users. When these user try to rename then it show. `You don't have a permission to rename the document.`
> https://prnt.sc/tb3eqe

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya For album, when **Group Moderator** trying to delete Photo from album, It shows Error.

https://www.loom.com/share/c6a7a80c27f14a6b9da6bdf608f0950c

Issue related to Album - Album creating twice.

https://www.loom.com/share/650572e2de6c4fe6a06cc81ff3e3d82b

**Comment by chetansatasiya** [comment]
> @chetansatasiya For album, when **Group Moderator** trying to delete Photo from album, It shows Error.
> 
> https://www.loom.com/share/c6a7a80c27f14a6b9da6bdf608f0950c

@ankitguptaindia This is fixed now :+1

**Comment by chetansatasiya** [comment]
> Issue related to Album - Album creating twice.
> 
> https://www.loom.com/share/650572e2de6c4fe6a06cc81ff3e3d82b

@ankitguptaindia This is fixed now

**Comment by ankitguptaindia** [comment]
@eisenwasser @chetansatasiya 

All above issues have been fixed.
Ready to Merge 👍

**Pull request merged**
