### PR TITLE
Removed hidden profile type users from search result count

### LINKED ISSUE #1322: Wrong search results count for Hidden Profile Type
**Describe the bug**
When users have the Profile Type is set to hidden, they are not searchable but they are still counted

**To Reproduce**
Issue can be replicated on demo
1. Create 2 Profile Types: one Hide all members of this type from Members Directory is enabled and the other one is not
2. Assign Profile Types to 2 different users. 
3. In the Profile Fields of the two users, enter a value to be searched
4. On frontend, search that value
5. See error on the results

**Expected behavior**
When Profile Type is hidden, this should not be counted in the search results as well

**Screenshots**
https://drive.google.com/file/d/1oprQENMmCP_QwSBVAE2OqIM9Y-2AT8Nr/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1240168203/85761

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1322 .

### How to test the changes in this Pull Request:

1. Create 2 Profile Types: one Hide all members of this type from Members Directory is enabled and the other one is not
2. Assign Profile Types to 2 different users.
3. In the Profile Fields of the two users, enter a value to be searched
4. On frontend, search that value
5. See error on the results

### Proof Screenshots or Video

https://www.loom.com/share/67ca4ab5edb2447aab64b3bc9c9100e1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
LGTM

@janakkaneriya007 Merge in dev and add in testing

**Comment by mohit-buddyboss** [comment]
Hi @janakkaneriya007 

Tested this on dev branch and 'fix/1322' branch of the platform.

Steps:
1) create two profile type show and hide.
2) Hide profile type - Hide this profile type from members directory.
3) Assign each profile type to 2 different users S and H. 
4) Add value in search under profile fields.
5) Go to network search. Select >Members > Select field of the  added value (Biography)
6) Verify result
7) Go to network search. Select >Members > Uncheck field of the added value (Biography)
8) Verify Result.

Issue : Now the counting issue is resolve under 'fix/1322' branch. But I've found other issue in this branch that it search keyword also when are search value field is not checked or selected under network search>members>profile field. This do not happens in Master branch.

Video: https://loom.com/share/6a060fe3150347b3897b332f3b892139

Kindly look into this.

cc @sourabhmatolia @KartikSuthar @chetansatasiya

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Tested this on dev as well as fix/1322 branch of the platform.

Now, we are not getting result of field which is not selected under network search. But it is reproducing another issue now if we unhide profile type from the members directory page then also under network search we are not getting any result. This issue is coming on both dev and fix/1322 branch of the platform.

Video: https://loom.com/share/04fbbcb0b6404eeda8eb324c9c494260

Kindly look into this.

cc @sourabhmatolia @KartikSuthar @chetansatasiya

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Tested on dev branch of the platform.
Above mentioned 2 issues are resolve now.
https://github.com/buddyboss/buddyboss-platform/pull/2205#issuecomment-901766166 - FIXED
https://github.com/buddyboss/buddyboss-platform/pull/2205#issuecomment-897331513 - FIXED

Video:  https://loom.com/share/b302a277e2094cbfba16d3fd1211ff51

Related issue is resolve now and PR is ready to release.

cc @sourabhmatolia @KartikSuthar @chetansatasiya

**Comment by JetalDobariya** [comment]
Hello,

I tested this PR in QA Approved branch and it has been done and working fine.
Here, I attached video for the proof.
https://www.loom.com/share/2de3e52300f842e5b15ea0a659ac11e9

Thanks!
CC : @mohit-buddyboss

**Pull request merged**
