### PR TITLE
Group type is disappearing when an organizer changes any group settings with a profile type

### LINKED ISSUE #1342: Group type is disappearing when an organizer changes any group settings with a profile type
**Describe the bug**
Whenever a group organizer (not admin) with a profile type changes any group settings the Group type is disappearing. It only happens if the group organizer has a profile type and the **Group Type Creation** is set to **None** from the profile type settings.

**To Reproduce**
1. Create a Group Type ex: School from **BuddyBoss > Groups > Group Types**: https://prnt.sc/txtpmx
2. Assign a group type to a group. Make sure the Group Organizer is not an admin: https://prnt.sc/txtr0y
3. Create a Profile Type ex: Student from **BuddyBoss > Profiles > Profiles Types**
4. Set **None** to the **Group Type Creation**: https://prnt.sc/txttyx
5. Assign a profile type to that Organizer: https://prnt.sc/txtus5
6. Go to the group setting as the Organizer.
7. Try to edit any setting: https://prnt.sc/txtwgu
8. See the group type is not there: https://prnt.sc/txtxkl 

**Expected behavior**
Group type should be there.

**Support ticket links**
https://secure.helpscout.net/conversation/1248386265/87188

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1342

### How to test the changes in this Pull Request:

1. Create a Group Type ex: School from **BuddyBoss > Groups > Group Types**: https://prnt.sc/txtpmx
2. Assign a group type to a group. Make sure the Group Organizer is not an admin: https://prnt.sc/txtr0y
3. Create a Profile Type ex: Student from **BuddyBoss > Profiles > Profiles Types**
4. Set **None** to the **Group Type Creation**: https://prnt.sc/txttyx
5. Assign a profile type to that Organizer: https://prnt.sc/txtus5
6. Go to the group setting as the Organizer.
7. Try to edit any setting: https://prnt.sc/txtwgu
8. See the group type is not there: https://prnt.sc/txtxkl 

### Proof Screenshots or Video
http://somup.com/cYjl1y649o

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]

**Review by mehulkaklotar — APPROVED** [review]
@ankitguptaindia we need testing here.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 
tested this on the branch `fix/1342` of the platform.
Issue:  User is not able to select 'None' for Group type creation . None check box is showing disabled.
Video: https://www.loom.com/share/f5eba9dde8c249e4bd6a7bc6027d9a83

**Comment by KartikSuthar** [comment]
@mohit-buddyboss Thanks! I have fixed the issue you mentioned.
When you select "None" other group type selection will be unchecked and disabled. http://prntscr.com/v8lcp5
When you deselect "None" other group types are enabled to select. http://prntscr.com/v8ld72

Please re-test it.

**Review by chetansatasiya — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

FIXED> Tested on 'Dev' branch of the platform.
Now if "group type" selection or creation access revoked from the group organizer "profile type" then on editing any settings previously assigned group type is not getting unassigned.
Video: https://www.loom.com/share/2528597531d240849d98453c25f9b730

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya

**Pull request merged**
