### PR TITLE
Discussion reply notification issue - fixed

### LINKED ISSUE #2948: Notification not working when discussion author replies to user's reply
**Describe the bug**
Notification not working when discussion author replies to user's reply in a discussion. Please see the video: https://www.loom.com/share/ab6c21b4ee384dc9b2f22bf1e139224b

**To Reproduce**
1. Let user1 create a discussion
2. Let user2 reply to the discussion
3. Notice that user1 will receive a notification
4. Let user1 reply to user2 in discussion
5. Notice that user2 will not receive a notification

**Screenshots**

**Environment**
dev, local, demo

**Support ticket links**
https://secure.helpscout.net/conversation/1630096805/163857?folderId=3709082

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2948  .

### How to test the changes in this Pull Request:

1. Let user1 create a discussion
2. Let user2 reply to the discussion
3. Notice that user1 will receive a notification
4. Let user1 reply to user2 in discussion
5. Notice that user2 will receive a notification now.

### Proof Screenshots or Video

https://www.loom.com/share/58c62cb39c794c60bba988735e422e76

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@mahedihasannoman 
Can you make sure https://github.com/buddyboss/buddyboss-platform/pull/2926/files This change not affecting this fix? 
Might be you need to fix both issues in the same PP as it's the same funcationality.

**Comment by mahedihasannoman** [comment]
> @mahedihasannoman
> Can you make sure https://github.com/buddyboss/buddyboss-platform/pull/2926/files This change not affecting this fix?
> Might be you need to fix both issues in the same PP as it's the same funcationality.

Okay I am checking this @dipskakadiya .

**Comment by mahedihasannoman** [comment]
Hi @dipskakadiya , I have checked this PR will not affect https://github.com/buddyboss/buddyboss-platform/pull/2926/files this fix.

**Review by dipskakadiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Comment by gabybeldoro** [comment]
Retested in the QA ongoing branch.
Status: Not yet Fixed

Proof Screenshots or Video: https://www.screencast.com/t/HqwToZ3yO

**Comment by mahedihasannoman** [comment]
Hi @gabybeldoro , I have also tested in qa-ongoing branch it is working fine as expected. See my video: https://share.vidyard.com/watch/DRB8uTpRUXQP7yRLzsbrha?

Please make sure you are on qa-ongoing branch and fetch all the latest changed in qa-ongoing branch and re-check again.

**Comment by basil-buddyboss** [comment]
Hi @mahedihasannoman 

This has been tested in the QA-ongoing branch and the issue is now resolved.

**To reproduce**:
1. Create a new discussion as user 1
2. Reply to the discussion as user 2
3. View as user 1 and will receive a notification
4. Let user 1 add a reply to the reply of user 2 in the discussion
5. View as user 2 and will receive also a notification now.

**Video:**
https://watch.screencastify.com/v/GtGETtsiy6oW33VzNFFn

**Status: Passed**

**Comment by joeytoribio** [comment]
Hi @mahedihasannoman,

This has been tested in the qa-approved branch without any issues.

**Result: PASSED**

Thank you!

**Pull request merged**
