### PR TITLE
Platform Help section consistent with App Plugin help section

### LINKED ISSUE #2376: BB Help > Make Platform Help section consistent with App Plugin help section
**Task**
Similar to App Plugin > Provide option to load links within WP sites instead of redirecting to BuddyBoss resources site. 
Also, there are differences in the flow between both help sections. Need to make that consistent.
Check Video and related PR below.

**Video for more details here:** 
https://www.loom.com/share/65413327ef3243fcb1316f6239e2be0d

**Related App Plugin PR:**
https://github.com/buddyboss/buddyboss-app/pull/1955

### PR DESCRIPTION
**Pull request by asaquzzamanbb**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2376 

### How to test the changes in this Pull Request:

Similar to App Plugin > Provide option to load links within WP sites instead of redirecting to BuddyBoss resources site.
Also, there are differences in the flow between both help sections. Need to make that consistent.
Check Video and related PR below

https://www.loom.com/share/65413327ef3243fcb1316f6239e2be0d

### Proof Screenshots or Video

https://www.loom.com/share/62b83996ce574da7970d22c12f3546d6

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@asaquzzamanbb Approved. Merged to dev and pass to QA.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 
Merge done!

**Comment by sumitbuddyboss** [comment]
Hello @asaquzzamanbb 

Issue >

When we click on any particular tab then the menu goes a little up and hides the menu bar so kindly check the below issue video.

Video:
https://www.loom.com/share/798c49da909a49d6a919e372522273bb

cc @sourabhmatolia 

Thank you

**Comment by asaquzzamanbb** [comment]
@sumitbuddyboss @KartikSuthar 

I have fixed it, please review it again.

**Review by chetansatasiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello  @asaquzzamanbb 

Fixed >
I have checked on the dev branch and the related issue is resolved now please check the below proof video.

Video
https://www.loom.com/share/ce011f854f95414994d51348b7f487c5

Ready for release 🚀 
@chetansatasiya 

Thank you

**Pull request merged**
