### PR TITLE
Forum search issue - fixed

### LINKED ISSUE #2069: Forum search not working properly
**Describe the bug**
When users search in Forum Search box, the search function does not work even if you enter a correct term like a Forum title
When you also search for a term with no available query, after hitting enter, the forum results shows blank

**To Reproduce**
This issue can be reproduced on our demo
1. Go to Forums page
2. Search for a correct query, like forum title
3. See error, this loader shows no result
4. Search again using a term that have no query and hit enter
5. Then remove your search term and hit enter again
6. The results still shows blank

**Expected behavior**
Forum search should work consistently

**Screenshots**
https://drive.google.com/file/d/10GMslo-4yktFAhJgVA97d1gEker1EUM6/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1400222589/120581
https://secure.helpscout.net/conversation/1405186781/121644

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2069  .

### How to test the changes in this Pull Request:

1. Go to Forums page
2. Search for a forum that is connected with a group
3. Also make sure to Group checkbox is enabled from BuddyBoss > Settings > Search page
4. See the ajax search is working properly

### Proof Screenshots or Video

https://www.loom.com/share/2ce5dfec9a034ccc89f362378355440a

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@mahedihasannoman 

Tested on qa-ongoing branch of the platform. 
This issue is not completely resolve yet. 

Note : Now we have search forum search functionality also when forum banner is not enabled and that PR is also merged into qa-ongoing branch. PR : https://github.com/buddyboss/buddyboss-theme/pull/795

Issue > When we search anything using Private group forum name and Private individual forum name and those forum have topics and also logged in user have access to private groups still on search result page user is not getting any result. But if user search directly using discussion/topic name then on search result page results are appearing. This is working fine for Public group forum and public individual forum.

Expected : On search using Private forum name user must get result on search result page if user have access to private group or private individual forum.

Video: https://loom.com/share/359411a204044b7298421a56d47c6be7

cc @sourabhmatolia @chetansatasiya @KartikSuthar

**Review by chetansatasiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @sourabhmatolia @firozwp 

We're bumping this task from sprint -6 to sprint-7 because this task comes with QA on the last day of the sprint.

Thank you

**Comment by JetalDobariya** [comment]
Hello @mahedihasannoman 

I tested this PR in qa-ongoing branch, and related issues has been done and wirking fine as expected.
Now Forum search suggestions results are getting and also Private and public forums topics are appearing properly.
-> https://www.loom.com/share/14e7db84490a42949e66816235d2c05e
-> https://www.loom.com/share/cac2903e6ac040639f18530bad771cbb

Thanks!
CC : @chetansatasiya @sumitbuddyboss

**Comment by JetalDobariya** [comment]
Hello @mahedihasannoman 

I did verify this PR in qaapproved branch, now related issue has been done regarding the Forum Search.
-> https://prnt.sc/1zwhlcy
-> https://prnt.sc/1zwhqno

Thanks!
CC : @firozwp @sourabhmatolia

**Pull request merged**
