### PR TITLE
Fix Redis Cache issues

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — DISMISSED** [review]
@chetansatasiya Approved..! 🚀

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @KartikSuthar 

Tested on dev branch of the platform with redis object cache plugin enabled and also redis enabled on server. 
Video Explanation of Issue exist on release branch > https://www.loom.com/share/03686a7042954ac48bfdd49635d2bff6

Issue 1 > On moving photos in album> 
1. Album preview is not appearing also album count is not getting update.
2. When user go inside the album moved photo gets display count is not coming proper. 
3. If user moves more photos in album then album is not getting update automatically. 
4. User required to flush cache to show correct count, album preview and updated photos in album 

Issue 2> On moving documents in folder
1. On moving first time documents in folder. Number of documents inside and outside folder display correctly. 
2. After that if user moves more documents in folder then folder is not getting update and documents still appears outside folder.

Videos>https://www.loom.com/share/be413d6aca774fb489ca0ee8087cec05
https://www.loom.com/share/2927c002304a4a189227b8ce773d3626

cc @sourabhmatolia

**Comment by chetansatasiya** [comment]
> @chetansatasiya @KartikSuthar
> 
> Tested on dev branch of the platform with redis object cache plugin enabled and also redis enabled on server.
> Video Explanation of Issue exist on release branch >
> 
> https://www.loom.com/share/03686a7042954ac48bfdd49635d2bff6
> 
> Issue 1 > On moving photos in album>
> 
> 1. Album preview is not appearing also album count is not getting update.
> 2. When user go inside the album moved photo gets display count is not coming proper.
> 3. If user moves more photos in album then album is not getting update automatically.
> 4. User required to flush cache to show correct count, album preview and updated photos in album
> 
> Issue 2> On moving documents in folder
> 
> 1. On moving first time documents in folder. Number of documents inside and outside folder display correctly.
> 2. After that if user moves more documents in folder then folder is not getting update and documents still appears outside folder.
> 
> Videos>
> 
> https://www.loom.com/share/be413d6aca774fb489ca0ee8087cec05
> 
> https://www.loom.com/share/2927c002304a4a189227b8ce773d3626
> 
> cc @sourabhmatolia

@mohit-buddyboss This is fixed now

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED<Tested on dev branch of the platform with redis object cache plugin enabled and also redis enabled on server.
Issue mentioned here : https://github.com/buddyboss/buddyboss-platform/pull/2271#issuecomment-841327419 is fixed now. 

Move functionality for Photos and documents is working fine on dev branch.
Videos:
https://www.loom.com/share/63ee690e4ce04126b599a245cf9183d5
https://www.loom.com/share/2502757fa89745e2ab9eec81e4bb80ba

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia

**Pull request merged**
