### PR TITLE
Fix - Activity comment more option icon overlaps dropdown

### LINKED ISSUE #2726: Activity comment more option icon overlaps dropdown
**Describe the bug**
Activity comment more options icon overlaps more option dropdown

**To Reproduce**
1. Go to activity
2. Check any activity with multiple comments
3. Click on comment more option dropdown

**Expected behavior**
More action button should not overlap the more option dropdown

**Screenshots**
https://ibb.co/d4QLnhP

**Environment**
NA

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2726 

### How to test the changes in this Pull Request:

1. Go to activity
2. Check any activity with multiple comments
3. Click on comment more option dropdown

### Proof Screenshots or Video
https://ibb.co/285HbkT

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by KartikSuthar — DISMISSED** [review]
@amincdev Merged to dev and pass to QA.

**Comment by amincdev** [comment]
@mohit-buddyboss @sumitbuddyboss Merged in `dev` and ready for testing.

**Comment by mohit-buddyboss** [comment]
@amincdev 

Tested on dev branch of the platform. 

Issue is resolve now. Video: https://loom.com/share/6cf43a7298614c3aaf5a080cd0959ec4

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @KartikSuthar @chetansatasiya

**Comment by JetalDobariya** [comment]
Hello, 

I have tested this PR in QA Approved branch, now More option and Report content is not overlapping on each other. So it is working fine.
Video  : https://www.loom.com/share/ae1eea7ec2054ce4bd50dcc3d1a3eca1

Thanks!

**Pull request merged**
