### PR TITLE
898 - Fixed the JS issue with WP text editor in profile fields

### LINKED ISSUE #898: Entries in repeating fieldsets cannot be deleted when containing a paragraph text field
Repeating field sets with a paragraph text field don't respond to deletion clicks in the profile edit page.

**To Reproduce**
1. Create a repeating field set 
2. Add a field of type paragraph text to it
3. Add a second field set to the list
4. Click on the delete button on any of them

**Expected behavior**
The deleted field set should be removed from the list but nothing happens

**Screenshots**
image

### LINKED ISSUE #907: Items in the repeating field set cannot be deleted
**To Reproduce**
1. Create a repeating field set with a field of type text
2. Add two field sets to the list
4. Click on the delete button for both of them and save the changes

**Expected behavior**
The deleted field sets should be removed from the list but they show up again after submit

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #898 
Fixes #907 

### How to test the changes in this Pull Request:

1. Create a repeating field set
2. Add a field of type paragraph text to it
3. Add a second field set to the list
4. Click on the delete button on any of them

### Proof Screenshots or Video
https://www.loom.com/share/29f08b848ae648c2a3fe02a28316a796

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed the JS issue with WP text editor in profile fields

### CODE REVIEW

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

This issue is already resolve by #846

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

**Issue 1:** Tested this using `fix/898`. This PR fixes nothing and the user is not able to delete any field here. See this Video 
https://www.loom.com/share/fe809442faa441f1a228a8862ca0d286

**Issue 2:**  Tested this issue on the `Dev` branch on the `dev` branch I'm able to delete the repeater set containing paragraph field only if the Paragraph field is **OPTIONAL**. If the Paragraph field is **REQUIRED** then this issue is appearing and user is not able to delete the repeater fieldset containing the paragraph field. See this video: https://www.loom.com/share/dae1c1479a0047899b1e42b04596f37c

cc @mehulkaklotar

**Comment by mehulkaklotar** [comment]
@KartikSuthar can you take over this PR?

**Comment by KartikSuthar** [comment]
> @janakkaneriya007
> 
> **Issue 1:** Tested this using `fix/898`. This PR fixes nothing and the user is not able to delete any field here. See this Video
> https://www.loom.com/share/fe809442faa441f1a228a8862ca0d286
> 
> **Issue 2:** Tested this issue on the `Dev` branch on the `dev` branch I'm able to delete the repeater set containing paragraph field only if the Paragraph field is **OPTIONAL**. If the Paragraph field is **REQUIRED** then this issue is appearing and user is not able to delete the repeater fieldset containing the paragraph field. See this video: https://www.loom.com/share/dae1c1479a0047899b1e42b04596f37c
> 
> cc @mehulkaklotar

@mohit-buddyboss Can you please test again, I have fixed both the issues you have mentioned.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

FIXED. This issue is resolved now. Tested this on branch `fix/898`.  Tested this issue by creating repeater fieldsets containing only paragraph field and another containing different fields like a paragraph, radio buttons, and phone number field. Also tested for both required and optional paragraph field.
For Proof See this video: https://www.loom.com/share/9dac2be56ec141b48a12779d44b4197a

cc @chetansatasiya @mehulkaklotar

**Pull request merged**
