### PR TITLE
Messages - improve the avatar display for multi-user message threads

### LINKED ISSUE #1050: Messages - improve the avatar display for multi-user message threads
**Is your feature request related to a problem? Please describe.**
We want to improve how we display avatars in messages that have more than 2 users. Right now we have some usability issues. We are fixing them in the app layout, and want to do the same on the web so it is in sync. APIs will need updates also.

**Describe the solution you'd like**
Video explanation - https://www.loom.com/share/912bc86bfd064f9790f4627c0f56a689

**Rules:**
1. I should never see my own avatar in a conversation. Should always be the most recent user(s) to reply who are not me.
2. If a conversation has 3 or more people (including me) then we see double avatar layout, with the two most recent replies (not me) showing as avatars. Similar to iMessage - https://prnt.sc/t1txa9
3. Apply these changes into message dropdown in titlebar also
4. Update API so app gets correct data to be able to replicate this UI.

**Support ticket links**
None yet

Theme Issue: https://github.com/buddyboss/buddyboss-theme/issues/828

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1050

### How to test the changes in this Pull Request:

1. I should never see my own avatar in a conversation. Should always be the most recent user(s) to reply who are not me.
2. If a conversation has 3 or more people (including me) then we see double avatar layout, with the two most recent replies (not me) showing as avatars. Similar to iMessage - https://prnt.sc/t1txa9
3. Apply these changes into message dropdown in title bar also
4. Update API so the app gets correct data to be able to replicate this UI.

### Proof Screenshots or Video
Video explanation - https://www.loom.com/share/912bc86bfd064f9790f4627c0f56a689

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

Theme PR: https://github.com/buddyboss/buddyboss-theme/pull/829

### CODE REVIEW

**Comment by eisenwasser** [comment]
@sagarjadhav 

Visual feedback - https://www.loom.com/share/f69d938630f44e3ab39519f812d62263

**Comment by eisenwasser** [comment]
@ankitguptaindia 

I will test the UI. Can you test the avatar logic for which avatar displays and make sure logic is always correct according to the description in the issue.

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

Condition-Begining of the message. - Sender avatar should appear on Top and other user's avatar in the bottom.
https://www.loom.com/share/43fe2025302746efbb524a5737415b78

**Comment by ankitguptaindia** [comment]
@KartikSuthar I am not seeing multi-user avatar in header dropdown area https://prnt.sc/ti7iwn


https://www.loom.com/share/f9e524f63afb45fd970249eb1fa295e1

**Comment by KartikSuthar** [comment]
> @KartikSuthar
> 
> Condition-Begining of the message (when only one person sent the message) - Sender avatar should appear on Top and other user's avatar in the bottom.
> 
> https://www.loom.com/share/43fe2025302746efbb524a5737415b78

@ankitguptaindia As per the design, We have follow like the stack, sender avatar appear on a top as a full image and other as bottom to see the half image of it.

**Comment by KartikSuthar** [comment]
> @KartikSuthar I am not seeing multi-user avatar in header dropdown area https://prnt.sc/ti7iwn
> 
> https://www.loom.com/share/f9e524f63afb45fd970249eb1fa295e1

@ankitguptaindia for that you need to pull theme: https://github.com/buddyboss/buddyboss-theme/pull/829

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

When the conversation has 5+ members then after sending the message sidebar looks like this. https://prnt.sc/ti9fb9
Appear fine after page load.

https://www.loom.com/share/258ecd42e14e433f81a9feb575969353

**Comment by ankitguptaindia** [comment]
@eisenwasser @KartikSuthar 

> @ankitguptaindia
> 
> I will test the UI. Can you test the avatar logic for which avatar displays and make sure logic is always correct according to the description in the issue.

Tested another scenario like Deleted member, Hide conversations, Delete Conversation, More than 10 members in conversation, conversation with attachments etc
Another scenario works fine. 

Need to fix this issue https://github.com/buddyboss/buddyboss-platform/pull/1164#issuecomment-658751035

**Comment by KartikSuthar** [comment]
> @KartikSuthar
> 
> When the conversation has 5+ members then after sending the message sidebar looks like this. https://prnt.sc/ti9fb9 https://prnt.sc/tia6mg
> Appear fine after page load.
> 
> https://www.loom.com/share/258ecd42e14e433f81a9feb575969353

@ankitguptaindia It's fixed. Please take a pull and test.

**Comment by ankitguptaindia** [comment]
@KartikSuthar Fixed.  Thanks.

> > @KartikSuthar
> > When the conversation has 5+ members then after sending the message sidebar looks like this. https://prnt.sc/ti9fb9 https://prnt.sc/tia6mg
> > Appear fine after page load.
> > https://www.loom.com/share/258ecd42e14e433f81a9feb575969353
> 
> @ankitguptaindia It's fixed. Please take a pull and test.


----------------


@sagarjadhav Please check feedback related from Mike  https://github.com/buddyboss/buddyboss-platform/pull/1164#issuecomment-658539503

**Comment by eisenwasser** [comment]
@ankitguptaindia 

Sagar finished my feedback. From your testing, is this 100% ready now?

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia
> 
> Sagar finished my feedback. From your testing, is this 100% ready now?

@eisenwasser Yes, Backend things from my side is also done. If Styling part is ready, we can merge.

**Pull request merged**
