### PR TITLE
Missing pagination for subforums.

### LINKED ISSUE #425: Missing pagination for subforums.
**Describe the bug**
Missing pagination for subforums. Replicated in demo as well.
No pagination even in default theme Twenty Twenty

**To Reproduce**
1. Create Parent Forum
2. Create at least 16 subforums (assigned to Parent Forum)
3. Keep default forums per page setting = 15

**Expected behavior**
Pagination should be visible for subforum sections when number of forum per page is exceeded

**Screen record**
https://www.loom.com/share/b6010f721c1048788006cd043554dbc5

**Support ticket links**
https://secure.helpscout.net/conversation/1111976917/5624/

### PR DESCRIPTION
**Pull request by RoopeshBahree**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #425.

### How to test the changes in this Pull Request:

1. Create Parent Forum
2. Create at least 16 subforums (assigned to Parent Forum)
3. Keep default forums per page setting = 15

### Proof Screenshots or Video

https://www.loom.com/share/760fc456e9174ca884b6415665bd68ef

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by mohit-buddyboss** [comment]
@RoopeshBahree 

Tested this using both Platform and Theme fix branch.

Platform - https://github.com/buddyboss/buddyboss-platform/tree/Missing_pagination_for_subforums
Theme - https://github.com/buddyboss/buddyboss-theme/tree/missed-pagination-sub-forum

**Issue:** Pagination issue is resolved on the Buddyboss theme but it doesn't resolve on the BB platform. If the user uses any other theme then pagination for subforums is not appearing. 

**Expected:** Pagination for subforums must appear if user uses the BB platform with any other theme. 

For better understanding see this video: https://www.loom.com/share/353dd7e7a32c4ef5bb0a745ba38d791d

cc @chetansatasiya @mehulkaklotar

**Comment by chetansatasiya** [comment]
@shohelbuddyboss @buddy4kp Can anyone of you takeover this fix the issue reported by @mohit-buddyboss ?

**Comment by shohelbuddyboss** [comment]
@chetansatasiya 

I've added the pagination template and it's working now with or without buddyboss theme. Please check

**Comment by mohit-buddyboss** [comment]
@shohelbuddyboss 

FIXED
Tested this using both Platform and Theme fix branch.

Platform - https://github.com/buddyboss/buddyboss-platform/tree/Missing_pagination_for_subforums
Theme - https://github.com/buddyboss/buddyboss-theme/tree/fix-subforum-pagination  **(RELATED THEME BRANCH)**

This issue is resolved now and Subforums pagination working fine for BB theme as well as when we are using the BB platform with any other theme.

For Proof See this video: https://www.loom.com/share/09885d04ad5a4544abd274f985dc9834

cc @chetansatasiya @mehulkaklotar

**Comment by mehulkaklotar** [comment]
https://github.com/buddyboss/buddyboss-platform/issues/425#issuecomment-660047117 

closing this.

**Pull request closed without merging**
