### PR TITLE
Shortcode [bbp-topic-form] is not working properly when use in Elementor popup template

### LINKED ISSUE #623: Shortcode [bbp-topic-form] is not working properly when use in Elementor popup template
**Describe the bug**
When you use [bbp-topic-form] shortcode to display a form within a popup using Elementor, it does not display and work properly.

**To Reproduce**
1. Make sure to have Elementor and pro version
2. Create a popup, go to Templates > Popups
3. Insert [bbp-topic-form] shortcode then save
4. Go to the frontend where you have made the popup and you will notice that it will not display properly and cannot post anything.

**Expected behavior**
The [bbp-topic-form] should be working inside a popup since as tested using bbPress it works well

**Screenshots**
- Using the BuddyBoss Platform
using-bbplatform

- Using bbPress
using-bbpress

 

**Support ticket links**
https://secure.helpscout.net/conversation/1111917045/1050/

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #623 

### How to test the changes in this Pull Request:

1. Make sure to have Elementor and pro version
2. Create a popup, go to Templates > Popups
3. Insert [bbp-topic-form] shortcode then save
4. Go to the frontend where you have made the popup and you will notice that it will not display properly and cannot post anything.

### Proof Screenshots or Video
Fixed editor loading issue and made it work.
http://prntscr.com/tit94e

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Theme PR: 
https://github.com/buddyboss/buddyboss-theme/pull/859

### CODE REVIEW

**Comment by KartikSuthar** [comment]
@amincdev Can you please help me at here, needs some cleanup for the UI:
http://prntscr.com/titb3v like this http://prntscr.com/tittvo

**Comment by amincdev** [comment]
> @KartikSuthar @amincdev
> 
> All JS changes releated to elementor should go to the theme JS file and elementor releated JS will not added in platform forum js file.
> 
> @mehulkaklotar Need your thoughts in this.

@KartikSuthar Please let me know if I can help with this.

**Review by chetansatasiya — APPROVED** [review]

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I did verify this platform PR in qa-ongoing branch, now Shortcode [bbp-topic-form] is working fine as expected.
See in the Proofs : https://www.loom.com/share/47b0b89e43954cf2aecbbc54257b3479

Thanks!

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I tested this PR in qa-approved branch, now Forum short code is working fine with Elementor.
--> https://www.loom.com/i/fef1f5dd4c5d4a1d8d0c2520bd492d67

Thanks!

**Pull request merged**
