### PR TITLE
Fixed: Email Reply Button is too small. It doesn't fit the reply text in it

### LINKED ISSUE #719: Email Reply Button is too small. It doesn't fit the reply text in it.
**Describe the bug**
Reply Button is too small. If you use the corresponding (longer) word in another language, word breaks.
Please refer to the screenshot.
https://prnt.sc/rvawf6

**To Reproduce**
1. First Change the reply text with any longer word(Antworten)
2. Now, add a comment to one of your activities using another user and it will send an email about the comment.
3. See an error in received email Like this.
https://prnt.sc/rvawf6

**Expected behavior**
Reply buttons should adjust the width automatically if "Reply" text is in a different language(Antworten).

**Screenshots**
https://prnt.sc/rvawf6

**Support ticket links**
https://secure.helpscout.net/conversation/1124344861/66206?folderId=3701248

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #719 

### How to test the changes in this Pull Request:

1. First Change the reply text with any longer word(Antworten)
2. Now, add a comment to one of your activities using another user and it will send an email about the comment.
3. See received email, It should not break the word in button.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by amincdev** [comment]
@chetansatasiya This is fixed now : https://prnt.sc/s948mx

**Comment by mohit-buddyboss** [comment]
**@amincdev @chetansatasiya** 

Hi, i have checked this for different user activity. Like email notification which we receive when user reply to one of your updates , replay to one of your comment, when someone message and when someone mentioned user in status update.

While testing i have found that for email notification user receive on comment , and reply on comment "Reply" button size gets auto but for other likes message and mentioned activity "reply' button size is still not getting auto expand.

Proof : See [Video](https://www.loom.com/share/04596521d26e4fe98145a0d8cc3b025a)

When someone mentioned in an update : [Screenshot](https://prnt.sc/sg9hcr)

Email notification when someone sends message : [Screenshot](https://prnt.sc/sg9ize)

So, kindly fix this issue for other templates also.

**CC @ankitguptaindia**

**Comment by amincdev** [comment]
@mohit-buddyboss I have fixed the above issues. Please check it.

**Comment by amincdev** [comment]
@mohit-buddyboss Please check this once you get a chance.

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@amincdev Code looks good to me.

@ankitguptaindia This need to be tested

**Comment by amincdev** [comment]
@mohit-buddyboss Can you please test this PR?

**Comment by mohit-buddyboss** [comment]
@amincdev Tested this on the branch `fix/719` of the platform.

Issue: On this branch, activities are not getting load all over the website and I'm getting 500 internal server error. So, Kindly look into this. 
https://www.loom.com/share/6b58c4f9ef634890a93f4e50e81d6e20

**Comment by amincdev** [comment]
@mohit-buddyboss Please check now.

**Comment by mohit-buddyboss** [comment]
@amincdev 

Tested on the platform branch `fix/719`.
FIXED> Tested this for User mentioned activity, Post reply activity, and for message activity. This issue is resolved now and now the Reply button text is not getting overflow.
Video: https://www.loom.com/share/245194dcf283493cbc4561c773855c16

@chetansatasiya

**Pull request merged**
