### PR TITLE
bbp-single-topic shortcode is not working for subscribers.

### LINKED ISSUE #681: bbp-single-topic shortcode is not working for subscribers.
**Describe the bug**
Issue 1 : As an Admin, I can see the topic and all the replies when using bbp-single-topic shortcode on a page, however users ONLY see the reply and subscribe button even though they are apart of the private group. 

Issue2 : I setup a Learndash Group, connected to a BB Social Group. This Social Group also has a forum. Learndash group has a auto-enroll tag from Memberium. So if someone gets the right tag, he enrolls in the learndash group, therefore also in the social group and should also see the forum topics. This works fine, as long as the Social Group is set to public. As soon as i set the social group to private - which would make sense for a learngroup, so only people that own the course could enter - the test user can see the group, but not the forum. The forum then says "there are no discussions yet". He can even start a new topic, but once it is posted, he is not able to see this topic. 

**To Reproduce**
1. Create a Private Group > assign forum > create a discussion. 
2. Create a page > place [bbp-single-topic] shortcode for the discussion created. 
3. Login as subscriber.
4. Go to the Page with shortcode. 
5. Blank page with only 'Reply' and 'Subscribe' button. 

**Expected behavior**
Should show all the replies created on the page. 

**Screenshots**
https://prnt.sc/rnpqsr

**Support ticket links**
https://secure.helpscout.net/conversation/1111907601/234?folderId=3701249
https://secure.helpscout.net/conversation/1124948946/66309?folderId=3701249

### LINKED ISSUE #1101: Two issues are experienced when displaying the forum using the shortcode in LearnDash course lesson.
**Describe the bug**
Issues is experienced when displaying the forum using the shortcode in the LearnDash course lesson. I used the following shortcode **_`[bbp-single-topic id=37913]`_** in the course lesson description to display the discussions. 

**Issue 1** 
CSS issues, fixed in theme PR and merged already...

**Issue 2** 
For **_subscribers_**(students), the discussions are not displayed. It is displayed as a blank page instead. Please refer to the screenshot to know more. 

**To Reproduce**
1. Go to LearnDash > Lesson > Edit > Add the shortcode
2. Visit the lesson on the front end as an admin
3. Visit the lesson on the front end as a subscriber(student)

**Expected behavior**
The shortcode should work without any issue. 

**Screenshots**
- https://i.imgur.com/JktlhuI.jpg : admin
- https://i.imgur.com/uv7y0a9.jpg : student

**Support ticket links**
- https://secure.helpscout.net/conversation/1202742859/79225/

### PR DESCRIPTION
**Pull request by manishpatolia**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #681 
Fixes #1101

### How to test the changes in this Pull Request:

1. Create a Private Group > assign forum > create a discussion. 
2. Create a page > place [bbp-single-topic] shortcode for the discussion created. 
3. Login as subscriber.
4. Go to the Page with shortcode. 
5. Blank page with only 'Reply' and 'Subscribe' button. 

### Proof Screenshots or Video

https://prnt.sc/rurggm

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@mehulkaklotar This will help you to understand the issue. https://www.loom.com/share/97df3dc563ae48df9b5f3f3fa9bc25a4

**Comment by chetansatasiya** [comment]
@manishpatolia 

Also  you if add this change then it will also break the privacy of the forum see here https://prnt.sc/s59uku Adele is not a part of this group https://prnt.sc/s59v6f but in shortcode it still access the discussions

**Comment by manishpatolia** [comment]
@chetansatasiya @mehulkaklotar 
No, it is not affecting my last change with privacy. That's for when we update group that time private forum also updates in option "_bbp_hidden_forums".
 and for shortcode showing private forum same like bbpress https://prnt.sc/s5ahhx, because users have 'read_private_forums' permission that's why showing.
But I will change for shortcode when the forum is part of the group.
I will fix it with groups and push a new commit.

**Comment by manishpatolia** [comment]
@chetansatasiya @mehulkaklotar 
I have changed for the forum when its part of a group that time it will show if the member has access otherwise not.

https://www.loom.com/share/7dfa22b0023f4db4a63579ba5164b12c

**Comment by mohit-buddyboss** [comment]
@manishpatolia 

**One question here** - The issue is fixed and now the user is able to access the Private group forum discussion posted using [bbp-single-topic] shortcode if the user is a member of the Private group. But for existing groups-  admin requires to change Privacy settings of the group once then and only Shortcode functionality will work as expected. So can we make changes so that this fix will not require an admin to change the privacy setting for the existing group?

cc @mehulkaklotar @chetansatasiya

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Fixed. Tested this PR by creating a private group and discussion page using shortcode on the dev branch then switch to fix/681 beach to check on switching branch group members have access to the discussion page created by shortcode or not. Also verified this for both Private as well hidden group. Also for group members and non-group members. A related issue is resolved now and changes implemented successfully.  For proof see this video: https://www.loom.com/share/335d521ba3b64bfcae61084a19e985fa

cc @chetansatasiya @mehulkaklotar

**Pull request merged**
