### PR TITLE
Option to hide all sub-groups from the main Groups directory

### LINKED ISSUE #1079: Option to hide all sub-groups from the main Groups directory
**Is your feature request related to a problem? Please describe.**
Users have asked if we can hide all sub-groups from the main groups directory. So you would only see parent groups (and standalone groups) in the groups directory.

"In your example using universities and their departments, ideally the groups page would only show the universities, and the user would click a particular university to pull up their departments. As it is, the groups page shows all the universities AND ALL the departments, making the page a complete and utter mess.  Do you have any plans or recommendations to fix this? Thanks."

**Describe the solution you'd like**
At BuddyBoss > Settings > Groups, in the "Group Hierarchies" metabox.
We can add an option to "Hide subgroups from the main Groups Directory"

**Support ticket links**
Requested on Youtube by user "Jas For Portland"
https://youtu.be/94LJT_trRls

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1079 .

### How to test the changes in this Pull Request:

1. BuddyBoss > Settings > Groups, in the "Group Hierarchies" metabox.
2. When you enable "Group Hierarchies" see another option "Hide Subgroups"
3. Enable and check the group directory.

### Proof Screenshots or Video
http://prntscr.com/td7kwy
Enable: http://prntscr.com/td7lby
Disable: http://prntscr.com/td7lr3

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by eisenwasser** [comment]
@mohit-buddyboss 
Please do a first pass on testing this.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Tested this feature on branch `fix/1079`. This feature is implemented successfully and working fine. Tested this for subscribers, Members as well as for non-members and non-logged in user. Also tested other related functionalities like send invites and private group access functionality.  All related functionalities are working fine. For Proof see this video: https://www.loom.com/share/5b45c6bef8c84e99bdae497b2ccbb51b

****Note:** _This feature will hide subgroups from only the Group Directory page. Users can still see subgroups from the User profile Group tab._  Screenshot: https://prnt.sc/tenjnt**

 @eisenwasser Here I have one question. If the admin hides the subgroups from the Group directory page then we should show subgroups on the User Profile group tab or not? 

cc @chetansatasiya @mehulkaklotar

**Comment by mehulkaklotar** [comment]
@mohit-buddyboss The setting is for Groups Directory only. It says in the setting label. Why should we hide subgroups from users page? sub groups are still accessible to user.

**Comment by mohit-buddyboss** [comment]
@mehulkaklotar @KartikSuthar 

Tested this new feature on branch f`ix/1079`. Hide subgroup functionality is working fine for the group directory page as well as for WP pages created using group type shortcode. **We just require to change the label of the checkbox from "Hide subgroups from the main Groups Directory" to "Hide subgroups from the main Groups Directory and WordPress pages created using group type shortcode. "**

For Proof see this video: https://www.loom.com/share/817e3a408b3445aebbfcb42e157c566b

**Comment by sourabhmatolia** [comment]
@mohit-buddyboss @KartikSuthar 

I will take care of changing settings label before releasing. Thanks.

**Comment by mohit-buddyboss** [comment]
> @mohit-buddyboss @KartikSuthar
> 
> I will take care of changing the settings label before releasing. Thanks.

@sourabhmatolia @KartikSuthar 
Okay, This is working fine. We just require to change label because this option not only hide subgroups from the main group directory but also from pages created using group type shortcode. https://prnt.sc/uep7bu

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
