### PR TITLE
#1705 - Fix document display issue

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — DISMISSED** [review]
@chetansatasiya Approved

**Comment by dipskakadiya** [comment]
@ankitguptaindia This is critical issue we  should test as soon as possible as this should be release in next release

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

This issue has been fixed. Tested with Dev branch code. Tested briefly for all privacy options for Photos and Documents with Public, Private, Hidden Group and Members specific. 

**Privacy Option checking for Public, Private, Hidden Group with Photos and Documents Test -** 
https://www.loom.com/share/cec95f7feb32470b9609368a3429a8de


**Privacy Option checking for Member Photos, Documents :-** 

https://www.loom.com/share/e3d759699b46427c92ba5f89df5d304c

**Review by ankitguptaindia — DISMISSED** [review]
Ready to Release 🚀

**Comment by ankitguptaindia** [comment]
@sourabhmatolia FYI -  this PR was not in list which we set next release milestone. 
But this is critical, need to add this one. Please merge in this build.

**Review by mehulkaklotar — APPROVED** [review]
@chetansatasiya approved! 🚀

**Pull request merged**
