### PR TITLE
Only hidden groups in the site other group members single activity not accessible by other members

### LINKED ISSUE #1854: Only hidden groups in the site other group members single activity not accessible by other members
**Describe the bug**
When we have only hidden groups into the site, no any public or private.
If user A post-activity and when user B of that group member views a single activity page to view, it's not accessible.

**To Reproduce**
1. Make sure the site has all hidden groups.
2. Go to group A using member X and create an activity
3. Go to group A using member Y and view the single activity of X
4. See an error

**Expected behavior**
Group members will show the group activity with hidden groups.

**Screenshots**
https://drive.google.com/file/d/1zaLZFhFRuyK-1XDlfIZrtro6FlZolgTn/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1324219133/106011

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1854

### How to test the changes in this Pull Request:

1. Make sure the site has all hidden groups.
2. Go to group A using member X and create an activity
3. Go to group A using member Y and view the single activity of X
4. See an error

### Proof Screenshots or Video
http://prntscr.com/vu2nbs

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
Looks good! 👍 

@KartikSuthar Let's put this into testing.

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

I'm still facing the issue, Please check the video proof.

How to reproduce:
1) Go to group A using member X and create an activity
2) Go to group A using member Y and comment on member X activity
3) See an error
Note: Make sure member Y have a subscriber role.

https://www.loom.com/share/fd8f191d14b24d20b8ccc7275eb9648f

cc @ankitguptaindia @sourabhmatolia

**Comment by KartikSuthar** [comment]
@sumitbuddyboss, I have fixed this issue. Please re-test again.

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 
The issues have been fixed and it's working properly for me, For proof please check the below video.

**Video:**
https://www.loom.com/share/f2fe37d520204e4fa61891205e0a6aaa

@chetansatasiya 
Ready foo release 🚀 

cc @ankitguptaindia @sourabhmatolia

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
