### PR TITLE
Allow to use custom registration page instead of Platform

### LINKED ISSUE #607: Allow to use custom registration page instead of Platform
**Is your feature request related to a problem? Please describe.**
Some customers are asking if they can use a custom registration URL instead of having to use the default BuddyBoss register form. They want to have all of the signup/register buttons redirect to a custom URL instead, particularly useful for membership plugins.

**Describe the solution you'd like**
https://www.loom.com/share/a7c1168523e5403d98b1fd87a9374589

See wireframe:
[registration-flow.pdf](https://github.com/buddyboss/buddyboss-platform/files/4295669/registration-flow.pdf)

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #607 .

### Theme PR:
https://github.com/buddyboss/buddyboss-theme/pull/462

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by eisenwasser** [comment]
@chetansatasiya 

When using this branch grunt fails now.

```
Running "jsvalidate:src" (jsvalidate) task
Validating src/bp-core/js/vendor/dropzone.js  
>> Line 32: Unexpected reserved word
Encountered 2 errors.
Warning: Task "jsvalidate:src" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by eisenwasser** [comment]
@chetansatasiya Reporting issues:

1. When you enable Private Network, nobody can register:
https://www.loom.com/share/2b3703827b674d1d88e89791ece7ef1a

2. If custom URL is selected, the entire Registration Pages metabox needs to go away. Not sure why you only removed 2 options and the other 2 remain. Doesn't make sense.
https://www.loom.com/share/8257d7e9a8b44cefbd806d9e2add850c

**Comment by eisenwasser** [comment]
@chetansatasiya 

The logic for the form is weird and confusing, and does not factor in Email Invites component.
Please update using attached wireframe and these instructions:
https://www.loom.com/share/a7c1168523e5403d98b1fd87a9374589

[registration-flow.pdf](https://github.com/buddyboss/buddyboss-platform/files/4276239/registration-flow.pdf)

**Comment by eisenwasser** [comment]
@chetansatasiya 

Also give me a "View Tutorial" button, it can link to a random article for now. I will make a video showing how to use it. https://prnt.sc/raegr8

**Comment by chetansatasiya** [comment]
@mehulkaklotar @eisenwasser When you merge this current PR make sure to merge [this](https://github.com/buddyboss/buddyboss-theme/pull/462) theme PR as well.

**Comment by chetansatasiya** [comment]
Theme PR https://github.com/buddyboss/buddyboss-theme/pull/462

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

I have tested +ve/-ve Use Cases after adding a custom signup URL option. It is working fine.
Users are getting created with Custom Sign up URL and WordPress Default sign up process. 

Some brief about this testing - https://www.loom.com/share/02a1fef64c2a4333aa0461776f51ffbe

**Comment by eisenwasser** [comment]
@chetansatasiya 

If Custom URL is enabled, in Sent Invites the "Invited" text should not be links:
https://www.loom.com/share/c652599a55ed4e3b977a5fb36c933e78

**Comment by eisenwasser** [comment]
Same when the status changes to Registered, it should not be a link.

**Pull request merged**
