### PR TITLE
#2447- Fix - Connection tab on the activity feed is also showing the logged in member own activity

### LINKED ISSUE #2447: Connection tab on the activity feed is also showing the logged in member own activity
**Describe the bug**
Connection tab on the activity feed is also showing the logged in member own activity 

**To Reproduce**
1. Go to BuddyBoss > Settings > Activity > Enable **Activity tabs**
2. Go to Activity Feed
3. Click the connection tab

**Expected behavior**
Connection tab will only display the logged in member connections activity

**Screenshots**
https://www.loom.com/share/be40808161554924939a740278cc3bf9

**Support ticket links**
https://secure.helpscout.net/conversation/1528963033/145049/

### PR DESCRIPTION
**Pull request by meetmakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2447  .

### How to test the changes in this Pull Request:

1. Go to BuddyBoss > Settings > Activity > Enable Activity tabs
2. Go to Activity Feed
3. Click the connection tab

### Proof Screenshots or Video

screencapture-dev-meet-flywheelsites-members-meet-activity-friends-2021-08-26-00_18_45

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@meetmakadiya Approved. Ready for testing.

**Comment by sumitbuddyboss** [comment]
Hello @meetmakadiya 

Fixed >

I have checked with fix/2447 branch and the related issue is resolved now we can see only connection member activity for the proof please check the below video. 


Video:
https://www.loom.com/share/931747d9a6474ae4b39bae2efd5641ab

Ready for release 🚀 

Note:
@meetmakadiya 
Please merge this PR to qa-ongoing branch.

Thank you

**Comment by meetmakadiya** [comment]
@sumitbuddyboss `fix/2447` branch merge to `qa-ongoing` . please check it and let me know if any queries.
http://i.imgur.com/bNGy2A8.png
Thanks you.

**Comment by JetalDobariya** [comment]
Hello @meetmakadiya 

I did verify this PR in qa-approved branch, now in the Connection tab only appear connected member's Activity.
See the Proof for the differentiate of the "All Update" news feed and "Connection" news feed.
--> All Updates tab : https://www.loom.com/i/4d6b5cad29434d20b16bb8c194166ffa
--> Connection tab : https://www.loom.com/i/7eaa5f9fd94c4f48bec45a203aebaf3a

Thanks!

**Pull request merged**
