### PR TITLE
Private group documents will be visible on the /documents page for logged out users.

### LINKED ISSUE #1036: Private group documents will be visible on the /documents page for logged out users.
**Describe the bug**
If you keep 'Allow members to upload documents in profiles and profile activity' setting checked, the issue gets resolved. 

**Expected behavior**
Should be hidden.

**Screenshots**
https://drive.google.com/file/d/17py525iA0VZg9d_aatIuO9GfGVQu3oGP/view

**Support ticket links**
https://secure.helpscout.net/conversation/1192789807/77520?folderId=3701249

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1036 .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by KartikSuthar** [comment]
@ankitguptaindia 
Can you please test the document/folder based on their privacy in the below cases?
1. Directory Page
 - All Documents
- My Documents
- Group Documents
2. User Document Page/User specific folder
3. Group Document Page/Group-specific folder
4. Searching in the above 3 conditions

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

Group is appearing in MY GROUP tab although user is not added in that group.

Please refer for more details - https://www.loom.com/share/09206191271449fd8c788c78e65b7287

**Comment by KartikSuthar** [comment]
> @KartikSuthar
> 
> Group is appearing in MY GROUP tab although user is not added in that group.
> 
> Please refer for more details - https://www.loom.com/share/09206191271449fd8c788c78e65b7287

@ankitguptaindia It's fixed. Can you please retest again?

**Comment by ankitguptaindia** [comment]
@KartikSuthar @chetansatasiya 
(Rare Scenario but it should not work in this way)

User can download ONLY ME privacy folder if they have Download Link. 

Scenario -  Suppose User X created a public folder and User Y, Z saved the download link.
Later on User X changed the privacy and made Only me. In this case, User Y, Z can download this folder bçoz they have download link already. as well as non logged in user can also download that folder via link. 


Refer - 
https://www.loom.com/share/451419cbc53642b4988d1ab88112b997

**Comment by chetansatasiya** [comment]
> @KartikSuthar @chetansatasiya
> (Rare Scenario but it should not work in this way)
> 
> User can download ONLY ME privacy folder if they have Download Link.
> 
> Scenario - Suppose User X created a public folder and User Y, Z saved the download link.
> Later on User X changed the privacy and made Only me. In this case, User Y, Z can download this folder bçoz they have download link already. as well as non logged in user can also download that folder via link.
> 
> Refer -
> https://www.loom.com/share/451419cbc53642b4988d1ab88112b997

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
> > @KartikSuthar @chetansatasiya
> > (Rare Scenario but it should not work in this way)
> > User can download ONLY ME privacy folder if they have Download Link.
> > Scenario - Suppose User X created a public folder and User Y, Z saved the download link.
> > Later on User X changed the privacy and made Only me. In this case, User Y, Z can download this folder bçoz they have download link already. as well as non logged in user can also download that folder via link.
> > Refer -
> > https://www.loom.com/share/451419cbc53642b4988d1ab88112b997
> 
> @ankitguptaindia This is fixed now 👍


This is fixed.  tested.

**Comment by ankitguptaindia** [comment]
> > @KartikSuthar
> > Group is appearing in MY GROUP tab although user is not added in that group.
> > Please refer for more details - https://www.loom.com/share/09206191271449fd8c788c78e65b7287
> 
> @ankitguptaindia It's fixed. Can you please retest again?

It is fixed. tested.

**Comment by ankitguptaindia** [comment]
@KartikSuthar 

Reported issue on this PR have been fixed.

Also tested Documents, Folders and Privacy in below scenario:-
Directory Page
- All Documents
- My Documents
- Group Documents
User Document Page/User specific folder
Group Document Page/Group-specific folder
Searching in the above 3 conditions

**Pull request merged**
