### PR TITLE
Firefox comment/reply anchoring

### LINKED ISSUE #2011: Firefox comment/reply anchoring
**Describe the bug**
As per clients suggestion we should remove page scroll on activity comment links.
"Using Firefox browser, when someone clicks on reply/comment in a post in Groups or Newsfeed, it scrolls down and you can no longer see the main post. This created confusion for the users."

**To Reproduce**
1. Go to Newsfeed using Firefox
2. Click on any post comment link
3. See page scroll

**Expected behavior**
Page should not scroll

**Screenshots**
https://www.loom.com/share/cb87982b2cf74f91a36bace37d4e6573

**Support ticket links**
https://secure.helpscout.net/conversation/1370695923/115459/

### PR DESCRIPTION
**Pull request by annrra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2011 

### How to test the changes in this Pull Request:

1. Go to Newsfeed using Firefox
2. Click on any post comment link
3. See result

### Proof Screenshots or Video

https://drive.google.com/file/d/1q_lAIYYZd8QUhkQEH7sawzHgG0KSaljm/view

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@annrra Looks good merge in dev and add in testing.

@mohit-buddyboss @sumitbuddyboss Make sure this will work on all the browsers.

**Comment by mohit-buddyboss** [comment]
@annrra 

Tested on dev branch of the platform and theme. 
Now the page is not getting scroll in Firefox when user try to comment on news feed page. But I can see small behavior difference while using Firefox.
Steps:
1. Go to news feed page in Firefox
2. Try to comment on last post which you can see on the screen. 
3. When user try to comment on post in the end of the screen and which comment area is not appearing then you will notice that in Firefox  page is not scrolling up to show whole comment editor area where as in chrome and edge the page gets scroll in this case and comment editor area do not get hide. 

Video: https://www.loom.com/share/660834be7e5f4be5b5f9044a14e91aa8

cc @chetansatasiya @joshuamarkt

**Comment by annrra** [comment]
@mohit-buddyboss 
Comments anchoring is re-fixed and should scroll comment form in the middle of the viewport
https://drive.google.com/file/d/1IlknYiyTuUIn5tb3tUvMdTV1dOIlKzy5/view

**Review by chetansatasiya — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@annrra 

FIXED> Tested on dev branch of the platform. 
Now on clicking on comment page scroll in middle of the view port. This is solving the issue mentioned here https://github.com/buddyboss/buddyboss-platform/pull/2012#issuecomment-822365572

Video: https://www.loom.com/share/39c6a684e510414196d148f63a7561c8

Related issue is resolve now and PR is ready for release.

cc @chetansatasiya @sourabhmatolia

**Pull request merged**
