### PR TITLE
#2420 - Fixed to hide subgroups from My Groups tab

### LINKED ISSUE #2420: Subgroups are displaying in All Groups and My Groups tabs whereas Hide Subgroups option is checked from setting
**Describe the bug**
Subgroups are displaying in All Groups and My Groups tabs whereas Hide Subgroups option is checked from setting.

**To Reproduce**
1. Go to BuddyBoss -> Groups -> Create Group ( i.e - Parent Group)
2. Go to BuddyBoss -> Groups -> Create Group  ( i.e - Sub Group) -> Select Group Parent ( i.e - Parent Group)
3. Go to BuddyBoss ->Settings -> Groups -> Hide Subgroups -> Checked
4. See error - https://screencast-o-matic.com/watch/crhYjFVfdVx

**Expected behavior**
Subgroup should not be display in All Groups and My Groups tabs if we enable Hide Subgroups option from setting.

**Screenshots**
https://screencast-o-matic.com/watch/crhYjFVfdVx

**Support ticket links**
Based on App testing

### PR DESCRIPTION
**Pull request by surajkrsingh**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2420 

### How to test the changes in this Pull Request:

1. Checked the `Hide subgroups from Groups Directory & Group Type Shortcode` option from Group settings
2. Visit group directory page > All groups and My groups
3. Also visit user profile > group > My groups
4. Above all places, subgroups shouldn't display

### Proof Screenshots or Video

https://drive.google.com/file/d/1uBKPkWQQW7SgDFUeJymSpsmx4qdikXzi/view?usp=sharing

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed to hide subgroups in My Groups tab

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@surajkrsingh Approved

**Comment by varunqa** [comment]
Verified Result -Fixed
Screen Short- https://prnt.sc/1s4gaol  ,  https://prnt.sc/1s4gd9i
Steps- 
1.Login In App >>Go to Group 
2.Tap on my Groups >>select that any group which You Are the Organizer >>Tap on Manage and select Setting option
3.Tap on Group Parent >> Add any group to be as Parent 
4.login in web and go to buddyboss >>setting >>Group >> Group Hierarchies>> check mark to Hide Subgroups.
5.Save it and go to app and observe in Group that sub group is got hide in my Group.  

Build Version - 1.3.2 (133) Android 

3.0.7 (308)-- iOS

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@surajkrsingh This is not working expected. Settings saying `Hide subgroups from Groups Directory & Group Type Shortcode` so it should hide only in groups `directory page` and `Group Type Shortcode` shortcode page. Now it also hide from the users groups page as well.

@varunqa This need to test properly with web and also in app.

**Comment by surajkrsingh** [comment]
@chetansatasiya 
We updated the PR.
Update demo - https://drive.google.com/file/d/1o228h52ecXoSljecpFpNt1yQ_TyoCYg_/view

**Comment by varunqa** [comment]
1) When User hide Subgroup  Form Backed  
    A)In App the Subgroup is not visible --- Fixed.   https://prnt.sc/1s4gd9i
    B)IN Web the Subgroup is Appearing --- Not Fixed .  https://prnt.sc/1sxpizh
    C)In App At User Profile >Group the Subgroup is not visible    
    D)In Web the Subgroup is Appearing at User Profile 
   
@chetansatasiya @surajkrsingh  Please lemme Know if I have missed something or Anythings that You need me To check Specially
As I have Checked the video but for me it is not Working Please Have A look.

User :tester1/tester1000

**Pull request closed without merging**
