### PR TITLE
Fixed Html posted in content is lost on editing the discussion

### LINKED ISSUE #1235: Html posted in content is lost on editing the discussion
**Describe the bug**

Html posted in content is lost on editing the discussion.

**To Reproduce - Video Explanation**

1. https://drive.google.com/file/d/1JBdHAfv7k-h3bdGaI_uIXxi54nwaZrsv/
2. https://drive.google.com/file/d/1hSKwkUZGB6kDZrN5-E6FtC0eG-zzGSCJ/

**Support ticket links**

https://secure.helpscout.net/conversation/1225976140/83395

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1235  .

### How to test the changes in this Pull Request:

1. Create a new discussion with this content: `<select>text</select>`
2. Now, Edit that discussion, It was like this before: https://prnt.sc/tlvytu
3. Test this with Forum Topic and Reply also.

### Proof Screenshots or Video
https://prnt.sc/tlvzny

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
Note: This issue: https://prnt.sc/tlqonx is related to the theme and it is fixed here : https://github.com/buddyboss/buddyboss-theme/pull/869

**Review by chetansatasiya — APPROVED** [review]
@amincdev Code looks good to me.

@ankitguptaindia This need to be tested

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Issue:
Still got the issue while editing the for, Html posted in content is lost on editing the discussion 

**Video:**
https://www.loom.com/share/735cb3e007a3457ba8bf1f5846a5d955


CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss This issue has been fixed and you check in `dev`. Because this PR was older and closed, Please post the final update on this PR: https://github.com/buddyboss/buddyboss-platform/pull/1826

**Pull request merged**
