### PR TITLE
Fix discussion reply with document not loading when documents upload disabled for activity

### LINKED ISSUE #2798: The discussion reply with the document file, when edited the documents are not loading
**Describe the bug**
I was able to replicate the same at the dev end and as per checking its been affected due to the document's profile settings even when the document's forum and reply options enabled

**To Reproduce**
Please check the video to reproduce the issue.

**Screenshots**
http://somup.com/crjqhKYSZZ

**Support ticket links**
https://secure.helpscout.net/conversation/1603565223/159132/

### PR DESCRIPTION
**Pull request by kishanjasani**
Discussion reply with a document not loading when document upload disabled for activity and profile.

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

It was not working because the default type is `profile` in the `bb_user_has_access_upload_document( $group_id = 0, $user_id = 0, $forum_id = 0, $thread_id = 0, $type = 'profile' )` function and we are not passing the forum while editing the forum. So it was taking the `profile` as the default argument. That is the reason for the issue. 

Fixes #2798 .

### How to test the changes in this Pull Request:

1. Uncheck this option from buddyboss plugin setting.
screenshot-buddyboss test-2021 08 19-15_58_35
2. Not add a document in the forum.
3. Try to edit that reply with a document.
4. See Document is visible.

### Proof Screenshots or Video
screenshot-buddyboss test-2021 08 19-16_05_00

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
LGTM 🚀

**Comment by chetansatasiya** [comment]
@kishanjasani Merge in dev and add in testing.

**Review by dipskakadiya — APPROVED** [review]
@kishanjasani Approved.

**Comment by umohitbuddyboss** [comment]
Verified Result - Fixed

Attached Screenshot - 
image

Checked on Site Connected to : https://bb-app-platform.flywheelsites.com/

**Comment by JetalDobariya** [comment]
Hello @kishanjasani 

I did verify this PR in qa-approved branch, now document is visible if "Upload documents in profiles and activity posts" Option is disabled from backend.
-> Backend : https://www.loom.com/i/760d895026e143a897901bf4c52668fa
-> https://www.loom.com/i/c39256dbfb454c2c9eaa6401184816f1

Thanks!
CC : @umohitbuddyboss

**Pull request merged**
