### PR TITLE
Added new icons for TikTok, Telegram and ClubHouse

### LINKED ISSUE #2450: New icons for TikTok, Telegram and ClubHouse
**Is your feature request related to a problem? Please describe.**
Add icons for TikTok, Telegram and ClubHouse

**Connected Issue in Theme**
https://github.com/buddyboss/buddyboss-theme/issues/1464

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2450 

### How to test the changes in this Pull Request:

1. Add links to newly added fields (TikTok, Telegram and ClubHouse) theme options -> Footer -> Social Links
2. Check icons in footer

### Connected PR in Theme
https://github.com/buddyboss/buddyboss-theme/pull/1465

### Proof Screenshots or Video
image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by Felipemauah** [comment]
Hi! Can you add the Spotify icon too please?

**Comment by Felipemauah** [comment]
...even if it were possible to have a field to insert custom icons, it would certainly help a lot and reduce support for this feature, as there are many different needs for different platforms. 👊👊👊

**Review by KartikSuthar — APPROVED** [review]

**Comment by amincdev** [comment]
@mohit-buddyboss merged in dev

**Comment by mohit-buddyboss** [comment]
@amincdev 

Related feature is implemented successfully and PR is ready to release.
Connected PR:  buddyboss/buddyboss-theme#1465

cc @chetansatasiya @sourabhmatolia

**Comment by sourabhmatolia** [comment]
@Felipemauah 
Thanks for the suggestion.
We will discuss this internally.

**Pull request merged**
