### PR TITLE
Fix #1899 : Fix User response is missing error showing while sign up

### LINKED ISSUE #1899: User response is missing error showing while sign up
**Describe the bug**
When user try to sign up then `User response is missing error showing up`

**To Reproduce**
Using this below plugin: 
https://www.buddyboss.com/resources/docs/integrations/google-captcha-pro-recaptcha/
1- We are using this pro plugin and then enable re captcha for ( buddypress registration form) setting. ( https://prnt.sc/w330h2 )
2- Now sign up and Observe  

**Expected behavior**
User should be able to sign up successfully

**Screenshots**
https://prnt.sc/voa3i0

### PR DESCRIPTION
**Pull request by buntybuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- Issue was when there is a google captcha enabled on registration page and a profile type field on the registration page
- At that time, all the textarea field was convrting to tinyMCE editor.
- Google captcha has hidden textarea field for the verify code.
- So this js ( register.js - check the commit ) was converting that google captcha hidden textarea as tinyMCE editor and this was creating problem in verifiying captch response.
- So from now only textarea which hass "wp-editor-area" class ( captcha hidden textarea doesn't have this class, but other textarea by default has this calss ) will be converted into tinyMCE editor.
- Also after changing profile type, ajax response were appending to two places. So to avaoid this we have added proper selector.

Fixes #1899 .

### How to test the changes in this Pull Request:

1. Add Google Captcha Pro plugin [google-captcha-pro.zip](https://github.com/buddyboss/buddyboss-platform/files/5754933/google-captcha-pro.zip)
2. Add keys and Enable google captcha for BuddyPress registration page https://prnt.sc/wd1bf1
3. Add profile type field to registation form.
4. Go to registration page and fill all the fields.
5. Change profile type from the dropdown.
6. Fill the captcha.
7. And submit the form.

### Proof Screenshots or Video

https://www.loom.com/share/4d7ebd82f1cb40beabc77318b9c33f59

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Logs: 621799827eb4c930c5f912a42e1767497ffbe23b, e3fde203fcb87c5a3925317319086e7c0ca922e5

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@buntybuddyboss LGTM 🚀 

Merge in dev and add in testing.

**Comment by buntybuddyboss** [comment]
@chetansatasiya I've merged it to `dev`.

**Comment by sumitbuddyboss** [comment]
Hello @buntybuddyboss 


Issue > 
Still, I'm facing the same duplicate filed issue for the proof please check the below issue video.

Issue video:
https://www.loom.com/share/f950d5daf287445e81e88d48171601c6

**Comment by buntybuddyboss** [comment]
@sumitbuddyboss 

- Realised that code was not updated on the site you were checking.
- I've uploaded `dev` brnach zip again on the site and it's working fine now.
- Proof: https://www.loom.com/share/3741c11287bc475d8862aa7bf220d5ea

Let me know if you still face any issue.
Thanks

**Comment by sumitbuddyboss** [comment]
Hello @buntybuddyboss 

FIXED> Tested this on the dev server. This issue is resolved now for proof please check the below video.

Proof video:
https://www.loom.com/share/109d33f051aa4bd2a34ceb096e43dce2


Cc @sourabhmatolia

**Pull request merged**
