### PR TITLE
Fixed - Participant avatar is clickable but participant name is not c…

### LINKED ISSUE #2066: Participant avatar is clickable but participant name is not clickable in private message threads
In private message threads my own username & avatar is clickable but for participant there is only avatar is clickable not the name. Please refer to the screenshot: https://prnt.sc/xk5yrm

**Describe the solution you'd like**
Username & avatar both should be clickable.

**Support ticket links**
https://secure.helpscout.net/conversation/1405159534/121637

### PR DESCRIPTION
**Pull request by nitishkaila**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?

### Changes proposed in this Pull Request:

Fixes #2066.

### How to test the changes in this Pull Request:

1. Go to Messages
2. Open the existing conversation
3. Participant name should clickable now

### Proof Screenshots or Video

https://www.loom.com/share/04024a601a5448fd802b367b5f4a5df1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
Looks good to me.

@nitishkaila Merge this change in `dev` branch and add in testing.

**Comment by sumitbuddyboss** [comment]
Hello @nitishkaila 

Please merge it to the dev branch.

cc @chetansatasiya

**Comment by nitishkaila** [comment]
Hi @sumitbuddyboss

Merged in the dev. Please check it.

**Comment by mohit-buddyboss** [comment]
@nitishkaila 

FIXED> Tested on dev branch. Also tested for blocked and suspended members. Blocked and suspended participants names are nor clickable. Other than that now participants names also clickable along with Avatar.
Video: https://www.loom.com/share/f0d0c30a14f04c9aa4223062191fbaab

Related issue is resolve now and PR is ready to release.

@chetansatasiya

**Pull request merged**
