### PR TITLE
#1055 profile dropdown backend menu changes

### LINKED ISSUE #1055: UI for easily controlling menus in the Profile Dropdown, and hiding menus
**Is your feature request related to a problem? Please describe.**
Users want the ability to easily re-order menus in the profile dropdown, and hide some of the menus. They also want the ability to hide any tabs in profile and groups.

**Describe the solution you'd like**
Video explanation - https://www.loom.com/share/eb9bab224a604cbabd830e137f2cb018

In Appearance > Customize > BuddyBoss Platform:
- In "Group Navigation", add option to hide any tab (unless it is required for functionality)
- In "Profile Navigation", add option to hide any tab (unless it is required for functionality)
- Create new section "Profile Dropdown". In this section, add the ability to re-order any nav items and hide any nav items from the profile dropdown. This will work in theme profile dropdown, and WP toolbar dropdown both.

Profile dropdown edits should be changed in:
- Theme profile dropdown
- WordPress admin bar profile dropdown
- our Elementor widget "Header Bar"

**Support ticket links**
No specific tickets, but this has been requested many times, in many channels.

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Theme Pr: https://github.com/buddyboss/buddyboss-theme/pull/837

Fixes #1055

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by eisenwasser** [comment]
@amincdev 

Feedback for WP adminbar dropdown:
https://www.loom.com/share/bcf2bf59820c43cbab1a00560ea723a8

**Comment by eisenwasser** [comment]
@chetansatasiya 

Disabling a component/setting is making the item red in the menu editor, but the non-functional link remains on frontend in profile dropdown: https://www.loom.com/share/f2574feba6bb415589449d3e57b0a2b7

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Disabling a component/setting is making the item red in the menu editor, but the non-functional link remains on frontend in profile dropdown: https://www.loom.com/share/f2574feba6bb415589449d3e57b0a2b7

@eisenwasser This is fixed now 👍  You have to test by creating new menu OR delete that items first and add again and see the changes.

**Comment by chetansatasiya** [comment]
> @amincdev
> 
> Feedback for WP adminbar dropdown:
> https://www.loom.com/share/bcf2bf59820c43cbab1a00560ea723a8
> 
> Ideally we can insert the @ programmatically, if not it could be done via CSS 'content' insertion.

@amincdev @eisenwasser  Fixed via programatically 👍

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 
Tested on platform branch `fix/1055` and theme `branch enhancement/header-profile-menu`

Here I would like to share a few minor feedbacks

1. Users don't have the option to hide icons for all menu items. Our own Profile drop-down menu doesn't have icons but now this custom drop-down menu has icons and if the user doesn't select any icons then it displays default icons. So, can we provide an option by which users can select an option to display no icons for menu items? Screenshot: https://prnt.sc/tjjqa9

2. Currently, if user selects any menu items from the side list then it is not easy to identify dor the user which items are already selected from the side list. So, can we show already added items as checked inside the list so that the user can easily identify which items are already added to the menu? Screenshot: https://prnt.sc/tjjt9k 

3. If items are appearing in the parent-children relationship in side list ( Parent menu and their sub-menu items) so when admin select parent items and their sub-item and add in the menu then those items do not display in the parent-child relationship they display as a separate item and user need to rearrange them to make then sub-items of parent items. So, is it possible if the user adds any parent item and it's sub-item into the menu then those items display default as they are appearing in side list? After, that if user don't want to show them as parent and submenu item they can change their position. Video:https://www.loom.com/share/7495b83bda97428caac532645dba1f4d

4. WP admin-bar design issue. Video: https://www.loom.com/share/6d4b936392be461498329b5780001a0e

5. Custom Profile Dropdown menu colors getting set as color selected for header links in theme options 'Styling' tab. Default Custom drop-down color is not set as per header links color option. So, kindly guide if it will work the same way or we will provide different options to set a color for the custom drop-down menu items? Video: https://www.loom.com/share/f3517ac20fa64140939a0c0d002ce192

6. In mobile devices default menu is appearing which displays currently on the dev branch. So, for mobile, we will display the default drop-down menu or custom profile drop-down menu? Screenshot: https://prnt.sc/tjkftp

7. Create group field appearing as an invalid field.  Video: https://www.loom.com/share/85e9d4b5f0d8469b9a4519d8f99dfaba

@mehulkaklotar @eisenwasser

**Comment by amincdev** [comment]
@mohit-buddyboss 

I have discussed these issues with @chetansatasiya and these are the responses for each one:

1. For icons, We have a logic that in menu item list if any of the item has an icon selected then we show the default icon for the rest of the items. Or if there is no icon selected for any of item the we don't show icon at all. This same logic is applied for sub-menu as well. Let me know if you have any questions. Here is the video link for this logic. : https://github.com/buddyboss/buddyboss-theme/pull/837#issuecomment-658547214

2. This is the default WordPress that how it's handling this.

3. This is the default WordPress that how it's handling this.

4. Fixed WP admin-bar design issue. {Please take pull in theme branch.}

5. **WP admin-bar design issue.**
    I have used 'Header Links Color' for default color and use 'Sub Menu Hover and Active Links Color' for the hover color.

6. Yes, It is the same as earlier for mobile. No change in that.

7. 'Create Group' link will be invalid if this setting is not enabled: https://prnt.sc/tl3min

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 
Tested on platform branch fix/1055 and theme branch enhancement/header-profile-menu

We're getting 2 logout option in profile drowpdown.

Issue Video.
https://www.loom.com/share/529c9d03d3824e7c855be9fca8663fe3

CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
@amincdev 
Profile drop down parent/child menu arrow and alignment not proper in the responsive device.

Issue video:
https://www.loom.com/share/2d5b40ec7fc44379b012e01d2afbf76e

CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss I have checked this issue with default WP theme Twenty Twenty and BuddyPress Plugin. It is same there as well.

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> Tested on platform branch fix/1055 and theme branch enhancement/header-profile-menu
> 
> We're getting 2 logout option in profile dropdown.
> 
> Issue Video.
> https://www.loom.com/share/529c9d03d3824e7c855be9fca8663fe3
> 
> CC @ankitguptaindia

@sumitbuddyboss This is fixed now 👍

**Comment by sumitbuddyboss** [comment]
> > @chetansatasiya
> > Tested on platform branch fix/1055 and theme branch enhancement/header-profile-menu
> > We're getting 2 logout option in profile dropdown.
> > Issue Video.
> > https://www.loom.com/share/529c9d03d3824e7c855be9fca8663fe3
> > CC @ankitguptaindia
> 
> @sumitbuddyboss This is fixed now 👍


@chetansatasiya 
Tested on platform branch fix/1055 and theme branch enhancement/header-profile-menu and the issue is resolve now, For the proof please check the below video. 

Video
https://www.loom.com/share/50401cd9a3034c4d8c9e5f8c0eee9887

CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 
Tested on platform branch fix/1055 and theme branch enhancement/header-profile-menu and the issue is resolve now, For the proof please check the below video.

Video:
https://www.loom.com/share/e1aba0e12df843d38bdc5208252b667f

CC @ankitguptaindia

**Pull request merged**
