### PR TITLE
Fixed-Photos: Select Album option are still showing even it is disabled

### LINKED ISSUE #2001: Photos: Select Album option are still showing even it is disabled.
**Describe the bug**
Disabling "Enable Album" in settings is not affecting when uploading a photo, the "Select Album" still appearing.

**To Reproduce**
1. Go to BuddyBoss Setting > Media > Photos and disable "Enable Albums"
2. Next, Profile Page and under photo tab, try uploading a photo
3. Once you put a photo, you can still the "Select Album"

**Expected behavior**
The "Select Album" while uploading a photo should be disabled when the "Enable Albums" in setting is off.

**Screenshots**
Disabled Album: https://prnt.sc/wee7z9
Select Album appearing: https://prnt.sc/wee9dk

**Support ticket links**
https://secure.helpscout.net/conversation/1383349454/117552

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2001.

### How to test the changes in this Pull Request:

1. Go to BuddyBoss Setting > Media > Photos and disable "Enable Albums"
2. Next, Profile Page and under photo tab, try uploading a photo
3. Once you put a photo, you can still the "Select Album"

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crVjDlPU9B

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fixed - Photos: Select Album option is still showing even it is disabled

### CODE REVIEW

**Review by chetansatasiya — COMMENTED** [review]
@jitendrabanjara1991 Code looks good.

We need to fix this issue in Document also. Can you check in document also like select folder is still coming if folder is disable?

**Comment by chetansatasiya** [comment]
> @jitendrabanjara1991 Code looks good.
> 
> We need to fix this issue in Document also. Can you check in document also like select folder is still coming if folder is disable?

@jitendrabanjara1991 Ignore this as we don't have something like this in document.

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@jitendrabanjara1991 Merge in dev and add in testing.

**Comment by mohit-buddyboss** [comment]
@jitendrabanjara1991 

FIXED> Tested this on dev server. This issue is resolved now and now "Select" or "create" album option is not appearing. If Album option is disable from back end. 

Proof : https://www.loom.com/share/db38e9e3a3df4bc69db8c7bea8acaa7f

Related issue is resolve now and PR is ready to merge.

@mehulkaklotar @sourabhmatolia

**Pull request merged**
