### PR TITLE
Fix #2000: PHP 8.0 Deprecate required parameters after optional parameters

### LINKED ISSUE #2000: PHP 8.0 Deprecate required parameters after optional parameters
I am continuously getting the following deprecated error for buddyboss platform with PHP 8.0 & WP 5.6 installation

Deprecated | Required parameter $option follows optional parameter $value | 1 | +wp-content/plugins/buddyboss-platform/bp-loader.php:130

Deprecated | Required parameter $post_type follows optional parameter $taxonomies | 1 | +wp-content/plugins/buddyboss-platform/bp-core/compatibility/bp-incompatible-plugins-helper.php:295

See the screenshot for more details: [https://prnt.sc/wg7ldg](https://prnt.sc/wg7ldg)

**To Reproduce**
You will see the error for PHP 8.0 & WP 5.6 environment

**Expected behavior**
Should not be any Deprecated error.

**Screenshots**
[https://prnt.sc/wg7ldg](https://prnt.sc/wg7ldg)

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

- For the first error, the second parameter is not used anywhere, so i removed that and updated the number of args of the add_filter() function
- For the second error, i have made the first parameter required because the function call never sends the null value.

Fixes #2000

### How to test the changes in this Pull Request:

1. use PHP 8.0 & WP 5.6 environment
2. go to wp-admin > dashboard page
3. see the errors are fixed now

### Proof Screenshots or Video
https://www.loom.com/share/c016a499cbbe4eaf8537867e233bea61

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by sadrul** [comment]
Related buddyboss theme issue https://github.com/buddyboss/buddyboss-theme/issues/1268

**Review by chetansatasiya — COMMENTED** [review]
Looks good 👍 

@sadrul Merge this branch to dev and add in testing.

**Comment by sadrul** [comment]
@sumit Merged to `dev` and ready for testing

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

I checked with PHP 8.0 and now there is No any PHP Error relate to Deprecate but there is another error related to the Undefined variable $user, So please check the below screenshot and video.

https://www.loom.com/share/14834bea1aa14d12b1fa85312171c375
https://prnt.sc/x7gake

cc @chetansatasiya

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

FIXED> Tested this on the dev server. This issue is resolved now.

**Proof**
https://prnt.sc/x9nzw1

@chetansatasiya 
The related issue is resolved now and PR is ready to merge.


cc @sourabhmatolia

**Pull request merged**
