### PR TITLE
Member page become slow for thousand of users.

### LINKED ISSUE #1202: Member pages become slow when there are thousands of users
**Describe the bug**
The member page is loading slow when thousands of users.

**To Reproduce**
1. Go To members page
2. See error

**Expected behavior**
The query is taking to much time it should not.

**Screenshots**
https://prnt.sc/ti69if

**Support ticket links**
Client site

### PR DESCRIPTION
**Pull request by asaquzzamanbb**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1202 .

### How to test the changes in this Pull Request:

1. Go To members page
2. See error https://prnt.sc/ti69if

### Proof Screenshots or Video

https://prnt.sc/10ly1ho

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@asaquzzamanbb Code looks good to me. Please merged to dev and pass to QA.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 
Merger done! 
https://github.com/buddyboss/buddyboss-platform/commit/61ea058c4fb8a6150ba51a1a5769b172d24b1b12

**Comment by sumitbuddyboss** [comment]
Hello @asaquzzamanbb 

Issue >
I'm not getting all users on the member page, The issue is on the dev branch.

**Video**
https://www.loom.com/share/efd83937eaac42c9b845979ca56210ba


Thank you

**Review by chetansatasiya — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

As discussed with you and @KartikSuthar on dev branch  > Members directory page> Only those members are appearing who have "last activity" detail.  Suppose customer creates user and later install our platform then on members directory page members will not appear until members login into the site. After login activity BP will get their last activity log and those members will start appearing on members directory page. So, we need modification here to avoid this issue. 

cc @sumitbuddyboss @sourabhmatolia

**Review by chetansatasiya — APPROVED** [review]
@KartikSuthar LGTM 

@sumitbuddyboss @mohit-buddyboss Please test out this PR with thousands of users like 50 to 70K members in members directory, groups members page, invites page and group messages page. You guys need to test this branch it self will not add in dev until 100% testing.

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Tested using this `fix/1202` of the platform and `master` branch of the theme. 

ISSUE> I'm not able to see any improvements while using this PR. This PR is creating more 'Slow Queries' than 'Master' branch.
I tested after creating 92k members on website and In group I added 6k members and also send invites to more than 3k users. 

Master branch:
https://prnt.sc/1ebnxhv - Members directory
https://prnt.sc/1ebqdrj  - Group members Tab

fix/1202 branch:
https://prnt.sc/1ebmz0j  - Members Directory
https://prnt.sc/1ebmq7k - Group members tab
https://prnt.sc/1ebnkqg - Pending Invites tab

So, This PR is not doing any improvements. 

cc @sourabhmatolia @chetansatasiya

**Comment by sourabhmatolia** [comment]
@mohit-buddyboss @asaquzzamanbb 

**UPDATE**

Bumped to next milestone because changes rejected by QA above.

**Comment by asaquzzamanbb** [comment]
> @asaquzzamanbb
> 
> Tested using this `fix/1202` of the platform and `master` branch of the theme.
> 
> ISSUE> I'm not able to see any improvements while using this PR. This PR is creating more 'Slow Queries' than 'Master' branch.
> I tested after creating 92k members on website and In group I added 6k members and also send invites to more than 3k users.
> 
> Master branch:
> https://prnt.sc/1ebnxhv - Members directory
> https://prnt.sc/1ebqdrj - Group members Tab
> 
> fix/1202 branch:
> https://prnt.sc/1ebmz0j - Members Directory
> https://prnt.sc/1ebmq7k - Group members tab
> https://prnt.sc/1ebnkqg - Pending Invites tab
> 
> So, This PR is not doing any improvements.
> 
> cc @sourabhmatolia @chetansatasiya

@mohit-buddyboss 
Could you please test it after disabled the moderation module. Hope it will work fine after disabled the Moderation module.

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Tested with branch `fix/1202` of the platform by creating more than 94k members and assigning more than 6k members in group and sending invites to more than 1500 members.  Tested with and without moderation component. This PR is increasing little amount of improvement.

**Review by chetansatasiya — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Members directory order is coming different when we compare it with Master branch.

Master branch : https://prnt.sc/1h2c8ty

fix 1202 branch: https://prnt.sc/1h2cqxc

cc @KartikSuthar @chetansatasiya @sourabhmatolia

**Comment by sourabhmatolia** [comment]
**UPDATE**

As per discussion with @asaquzzamanbb issue not replicable anymore.
After confirming with @manishpatolia we will close this PR and associated Issue.

**Comment by manishpatolia** [comment]
@sourabhmatolia @asaquzzamanbb 

I have checked on the client site, and right now, I seem fine so we can close this issue.
https://www.loom.com/share/54c91785f63243249561dd634952eab2

**Pull request closed without merging**
