### PR TITLE
Fixed Some UI issues on Album page

### LINKED ISSUE #513: Some UI issues on Album page- Button looks weird in upload Photos in Album pop-up
**Describe the bug**
1. button looks weird in Select Photos pop-up in Album 
2. Width is very tiny in Album title field
3. Make Cancel and Save button style little better.  https://prnt.sc/qr3eup

**To Reproduce**
1. Go to User Album 
2. Click on Select Photos from Library
3. See error -  you will see button getting touch to image.

**Expected behavior**
Should have proper space with respect to other elements

**Screenshots**
https://prnt.sc/qr3az2 . https://prnt.sc/qr3eup

**URL for Ref-** http://ankitlocal.local/members/admin/photos/albums/9/

**Support ticket links** N/A- Reported by QA

### PR DESCRIPTION
**Pull request by shashank-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #513 .

### How to test the changes in this Pull Request:

1. Go to User Album
2. Click on Select Photos from Library
3. Please check, all issues are fixed.

### Proof Screenshots or Video

[Done]
https://prnt.sc/r5k9wz
https://prnt.sc/r5l235
https://prnt.sc/r5lyj6

Find a new Issue in smaller device like iphone-5 & 6/7/8
**Before** > https://prnt.sc/r5kyea
**After** > https://prnt.sc/r5kzdo

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by anoopmishrabuddyboss** [comment]
@shashank-buddyboss I have tested this on my local with the latest `fix/album-page-UI-issue` branch issue is fixed with BuddyBoss theme https://prnt.sc/r90frp  but with other themes, the issue is not fixed https://prnt.sc/r90d5q please review and fix with others

**Comment by shashank-buddyboss** [comment]
@anoopmishrabuddyboss 

I have fixed issues for other themes.

Other themes: https://prnt.sc/re0m8m, https://prnt.sc/re0mdt
Buddyboss theme: https://prnt.sc/re0mhp, https://prnt.sc/re0mlb

Thanks.

**Comment by anoopmishrabuddyboss** [comment]
Tested it on my local with the latest `fix/album-page-ui-issue` branch issue is fixed with other themes 
Screenshots:- https://prnt.sc/rep8o6 https://prnt.sc/rep905  https://prnt.sc/repbds
@chetansatasiya please review and merge to the dev branch.

**Comment by shashank-buddyboss** [comment]
@sagarjadhav 

I have removed div added before ID/Class and !important from the style file.

Thanks

**Comment by chetansatasiya** [comment]
@sagarjadhav Can you review this again please?

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
