### PR TITLE
PROD-788 #2558 - Fix - Missing Friend ID on group pages

### LINKED ISSUE #2558: Missing Friend ID on group pages
**Describe the bug**
We discover a bug on your Dev site between BuddyBoss Platform and BuddyPress Extended FriendShip
 ( https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/), 
 The bug is in: wp-contentpluginsbuddyboss-platformbp-friendsbp-friends-template.php
 
**To Reproduce**
1. First install BuddyPress Extended Friendship Request plugin
https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/
2. Then go to Group page, click on any group member tab
3. Click on any unfollow connect icon, add some text in "Send Request box" then

**Expected behavior**
It should be send request without any error

**Screenshots**

**Environment**
https://ibb.co/wsBgtm4

**Support ticket links**
https://secure.helpscout.net/conversation/1558954101/150307

Jira: [PROD-788]

[PROD-788]: https://buddyboss.atlassian.net/browse/PROD-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by meetmakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2558 

### How to test the changes in this Pull Request:

1. First install BuddyPress Extended Friendship Request plugin
https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/
2. Then go to Group page, click on any group member tab
3. Click on any unfollow connect icon, add some text in "Send Request box" then
4. fix the issue.

### Proof Screenshots or Video

http://i.imgur.com/1W1Ox8H.png

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@meetmakadiya Approved. Ready for testing.

**Comment by harshalQA** [comment]
Not fixed: As Admin user Getting an error while sending a connection request to Members from a public group

Tested site URL: https://bb-app-platform.flywheelsites.com/wp-admin/

Note: I installed BuddyPress Extended Friendship Request plugin: https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/

Video:
https://www.awesomescreenshot.com/video/5438427?key=4695d36109f24c32ea644ed9cdc822f7

**Comment by meetmakadiya** [comment]
@harshalQA branch merge with `qa-ongoing` now you can test PR.

**Comment by azanoni** [comment]
Any news about this?

**Comment by basil-buddyboss** [comment]
Retested in the QA ongoing branch.
Status: Fixed

Proof Screenshots or Video:
https://watch.screencastify.com/v/2oWz1DfsCRZ3ZIJp2pdB

**Comment by chetansatasiya** [comment]
Closing this as it's not reproducible any more with current release branch

**Pull request closed without merging**
