### PR TITLE
Fixed Document file rename does not allow characters from any language other than English

### LINKED ISSUE #1072: Document file rename does not allow characters from any language other than English
**Describe the bug**
While renaming any document file it only allows English characters, If you try to enter any other language character it is not allowing.

**To Reproduce**
1. Go to my document
2. Click on more action button
3. Click on "Rename"
4. Add any language character other than English.
5. Error: It won't allow.

**Expected behavior**
It should allow any language character.

**Screenshots**
https://prnt.sc/t4fl4c

**Support ticket links**
https://secure.helpscout.net/conversation/1198878229/78482/

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1072 #1161  .

### How to test the changes in this Pull Request:

1. Go to my document
2. Click on more action button
3. Click on "Rename"
4. Add any language character other than English.
5. Error: It won't allow.

### Proof Screenshots or Video
https://prnt.sc/t4ur25

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
@amincdev 

If using this word `arjuualmaädhira` this is arabic word the it is changing the file name after save in simple english text.

https://www.loom.com/share/a6b2c32de575434ea3115600b4726acc

**Comment by amincdev** [comment]
> @amincdev
> 
> If using this word `arjuualmaädhira` this is arabic word the it is changing the file name after save in simple english text.
> 
> 
> https://www.loom.com/share/a6b2c32de575434ea3115600b4726acc

@chetansatasiya Can you please check this? It seems, while renaming the file there's some kind of filtering is happening which is converting this kind of character "ä" to normal "a" character.

**Comment by ankitguptaindia** [comment]
@amincdev 

Some special Character like `~` not allowed in renaming the folder but allowed at the time of creating new folder.

https://www.loom.com/share/768bc4b306f046b8a2a2e42600d8397d

**Comment by amincdev** [comment]
> @amincdev
> 
> If using this word `arjuualmaädhira` this is arabic word the it is changing the file name after save in simple english text.
> 
> 
> https://www.loom.com/share/a6b2c32de575434ea3115600b4726acc

@ankitguptaindia This is fixed now.

**Comment by amincdev** [comment]
> @amincdev
> 
> Some special Character like `~` not allowed in renaming the folder but allowed at the time of creating new folder.
> 
> 
> https://www.loom.com/share/768bc4b306f046b8a2a2e42600d8397d

@ankitguptaindia For this we are adding validation at the time of folder creation as well with the same checks.
Also, As per the WordPress sanitize_file_name() function, they do not allow below characters in media name. So we are adding validation to check all these characters while renaming file/folder and creating a folder.

**'?', '[', ']', '/', '\\', '=', '<', '>', ':', ';', ',', "'", '"', '&', '$', '#', '*', '(', ')', '|', '~', '`', '!', '{', '}', '%', '+'**

**Comment by amincdev** [comment]
@ankitguptaindia I have added validation while creating the folder as well. Also, Changed the validation checks as per WordPress standards.

**Comment by ankitguptaindia** [comment]
UPDATE of this task - In Progress.  Will resume after other priority tasks

**Comment by ankitguptaindia** [comment]
@amin

>@ankitguptaindia For this we are adding validation at the time of folder creation as well with the same checks.
Also, As per the WordPress sanitize_file_name() function, they do not allow below characters in media name. So we are adding validation to check all these characters while renaming file/folder and creating a folder.
'?', '[', ']', '/', '\', '=', '<', '>', ':', ';', ',', "'", '"', '&', '$', '#', '*', '(', ')', '|', '~', '`', '!', '{', '}', '%', '+'

I can add all these special character in my Folder name.  https://prnt.sc/tb7cu6

Refer this video for How to Reproduce - 
https://www.loom.com/share/32540269715e4710bdea025949e7d5c2


----

Another Concern - 

If any file already has keyword which are restricted in our validation then system directly changing name to unnamed files without informing to file owner.  https://prnt.sc/tb7mdp

We should not change file name without permission  or informing to users.


https://www.loom.com/share/2576673f4a7640e3a7b99567a59856d8

**Comment by ankitguptaindia** [comment]
@amincdev @chetansatasiya FYI ☝️  Important.

**Comment by chetansatasiya** [comment]
> Another Concern -
> 
> If any file already has keyword which are restricted in our validation then system directly changing name to unnamed files without informing to file owner. https://prnt.sc/tb7mdp
> 
> We should not change file name without permission or informing to users.
> 
> https://www.loom.com/share/2576673f4a7640e3a7b99567a59856d8

@ankitguptaindia I understand but we are following the WordPress Rules here and we are doing the same thing as WordPress doing. For e.g if you upload the same file in WordPress Media it will make the same as it is that we are doing and also WordPress is not informing the admin.

**Comment by ankitguptaindia** [comment]
@chetansatasiya Makes Sense. If this is also happening in WP core then we can skip this. 
---

@amincdev Please fix First issue  https://github.com/buddyboss/buddyboss-platform/pull/1077#issuecomment-653580175 when get chance so we can merge is upcoming release.

**Comment by amincdev** [comment]
@ankitguptaindia as per my discussion with @chetansatasiya, For folder  We have only restricted below characters. So, PLease test that accordingly.
`\ / ? % * : | " < >`

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia as per my discussion with @chetansatasiya, For folder We have only restricted below characters. So, PLease test that accordingly.
> `\ / ? % * : | " < >`

Thanks. @amincdev I wil review and update you.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @amincdev 

Now Special Character is not allowed in folder name but when users use these characters in a folder then Spinner is continuously running and not giving error or warnings.
Refer for more details - https://www.loom.com/share/2f0d674dab2348bb946f91295435d6d3

Different use case - When users create a new folder under the folder and use ` \ / ? % * : | " < >` these characters then it is giving a generic message and not allowing user to correct name and create folder again.


Refer for more details -  https://www.loom.com/share/ffbdb73fbc5e494c8913b673ec593db0

**Comment by amincdev** [comment]
@ankitguptaindia Above both issues are now fixed.

**Comment by ankitguptaindia** [comment]
> @chetansatasiya @amincdev
> 
> * Now Special Character is not allowed in folder name but when users use these characters in a folder then Spinner is continuously running and not giving error or warnings.
> 
> Refer for more details -
> 
> https://www.loom.com/share/2f0d674dab2348bb946f91295435d6d3
> 
> * Different use case - When users create a new folder under the folder and use ` \ / ? % * : | " < >` these characters then it is giving a generic message and not allowing user to correct name and create folder again.
> 
> Refer for more details -
> 
> https://www.loom.com/share/ffbdb73fbc5e494c8913b673ec593db0

These issues are fixed. Cross tested.

**Pull request merged**
