### PR TITLE
Media Preview Conflict with Elementor Pro Theme Builder

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

**Fixed >**
A related issue is resolved, I have checked in the QA-ongoing branch and Elementor pro Version 3.3.8 and now the media preview is working properly with elementor pro.

Also, I have checked with symlink is enable and disable for the proof please check the below video.

**Video:**
https://www.loom.com/share/8b127c5c936b4a3ba96f1699750e04df
https://www.loom.com/share/3a02fceb8b374fadb5515c17c93ee76d

Ready for Release 🚀 

Thank you

**Comment by JetalDobariya** [comment]
Hello, @chetansatasiya 

I did verify this PR in qa-approved branch and Elementor Pro Version 3.4.3, now media preview is working fine in Activity feed, Forum's discussion, replies etc..
Activity Feed photo : Comment and Reply : https://www.loom.com/i/4a079e2f3fa645db8733dbee64ed1735
Activity Feed Video : https://www.loom.com/i/e1b0a694f13f490387328f1c65a8173b
Forum Discussion and Reply : https://www.loom.com/i/821bd4390b3a49d2a99657d7375fba27

Thanks!

**Comment by anywheresa** [comment]
I am still having this problem

**Comment by hheal** [comment]
We have just installed and seem to also have this issue. Elementor 3.6.0

**Pull request merged**
