### PR TITLE
Edit Activity Popup scroll improvement

### LINKED ISSUE #1466: Edit Activity Popup scroll improvement
**Is your feature request related to a problem? Please describe.**
Edit activity popup with long content should have a scrollbar for the content only. popup header and bottom toolbar should be visible on screen.

**Issue List**

1. Edit popup should not show the photo loading animation: https://prnt.sc/ufc0p0
2. Improve the popup scroll behaviour as suggested in the Video.

**Describe the solution you'd like**
https://www.loom.com/share/4d3705074633452fb23cab1b1a1352d3

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1466 

### How to test the changes in this Pull Request:

1. Edit any activity with long content in it.
2. Check the scrolling behavior

### Proof Screenshots or Video

https://prnt.sc/ugxzb1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
@chetansatasiya Can you please review these changes? So, we can move this for testing?

**Review by chetansatasiya — DISMISSED** [review]

**Comment by amincdev** [comment]
@ankitguptaindia This needs testing.

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 
Kindly push changes to the dev branch for testing.

CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss Merged in `dev`

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed > Related changes working as expected, For proof please check the below video.

Video:
https://www.loom.com/share/0cf7b9c2efcf4349948331647a99cf06

@chetansatasiya  Ready to release 🚀 

CC @ankitguptaindia

**Review by mehulkaklotar — APPROVED** [review]

**Pull request merged**
