### PR TITLE
PROD-922 #1356 - Fixed rtl issue for profile completion widget counter

### LINKED ISSUE #1356: Completion counter showing wrong in the RTL mode
**Describe the bug**
Number of total fields is showing first before the number of the completed field. https://prnt.sc/tzolb5. If a user completes 2 of 4 steps, we show it as (2/4) in English, however, in RTL it should be shown as (4/2). The same issue for the LearnDash steps completion.

**Screenshots**
https://prnt.sc/u00l0z
https://prnt.sc/u00lfl

**Support ticket links**
https://secure.helpscout.net/conversation/1239176569/85584

**Jira issue** : [PROD-922]

[PROD-922]: https://buddyboss.atlassian.net/browse/PROD-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by amincdev**
https://buddyboss.atlassian.net/browse/PROD-4374
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1356  .

### How to test the changes in this Pull Request:

1. Check the Profile completion widget counters in RTL mode

### Proof Screenshots or Video
https://prnt.sc/ur5tm5

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@ankitguptaindia Need to test this

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Please merge it to the dev branch.

I've reviewed in platform fix/1356 and found the same RTL issue in Leandash Course, Member, page. For more detail please check the below video.

**Video:**
https://www.loom.com/share/9f0ae7e2d0364d2993ace21f064b0092 

cc @ankitguptaindia 

Thank you

**Comment by annrra** [comment]
> Hello @amincdev
> 
> Please merge it to the dev branch.
> 
> I've reviewed in platform fix/1356 and found the same RTL issue in Leandash Course, Member, page. For more detail please check the below video.
> 
> **Video:** https://www.loom.com/share/9f0ae7e2d0364d2993ace21f064b0092
> 
> cc @ankitguptaindia
> 
> Thank you

@sumitbuddyboss 
Regarding above new issue is created in BuddyBoss Theme here - https://github.com/buddyboss/buddyboss-theme/issues/1754
Current PR needs final review.

**Review by chetansatasiya — COMMENTED** [review]
LGTM 🚀

**Comment by chetansatasiya** [comment]
@annrra @amincdev Fix the conflict and merge in respective branches.

**Comment by amincdev** [comment]
> @annrra @amincdev Fix the conflict and merge in respective branches.

Done

**Review by KartikSuthar — APPROVED** [review]

**Pull request merged**
