### PR TITLE
Missing bb font icons

### LINKED ISSUE #1846: Missing bb font icons
**Describe the bug**
New bb font icons added

**To Reproduce**
1. Check if 'bb-icon-check-connection' and 'bb-icon-file-default' exist

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by annrra**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1846  .

### How to test the changes in this Pull Request:

1. Check if 'bb-icon-check-connection' and 'bb-icon-file-default' exist

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by annrra** [comment]
'check-connection' and 'file-default' icons added to bb icons font

**Review by chetansatasiya — APPROVED** [review]
@annrra looks good.

Changes add to dev branch and put in testing.

**Review by chetansatasiya — APPROVED** [review]
@annrra fixed the conflict and merge in the dev branch and then give it to testing.

**Comment by annrra** [comment]
@chetansatasiya 
Seems this is outdated issue/PR since missing icons has been added into platform bb icons with another PR
check-connection is not used anywhere in theme or platform and can be safely removed

**Pull request closed without merging**
