### PR TITLE
Fixed - Media uploader -> Select Photos tab more photos does not show photos on select photos tab

### LINKED ISSUE #1457: Media uploader -> Select Photos tab more photos does not show photos
**Describe the bug**
In album page Media uploader -> Select Photos tab loading more photos does not show photos.

**To Reproduce**
1. Go to Profile -> Photos => Any Album Page
2. Click on Add Photos
3. In popup got to "Select Photos" tab
4. click on "Load more" and see photos does not load

**Expected behavior**
Clicking Load more button All new photos should load.

**Screenshots**
https://prnt.sc/ubi319

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1457 

### How to test the changes in this Pull Request:

1. Go to Profile -> Photos => Any Album Page
2. Click on Add Photos
3. In popup got to "Select Photos" tab
4. click on "Load more" and see photos should load now

### Proof Screenshots or Video
https://prnt.sc/uczfev

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
@chetansatasiya Can you please review this?

**Review by chetansatasiya — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@amincdev Can you merge Dev branch in this branch once ?

**Comment by amincdev** [comment]
@ankitguptaindia Please check now.

**Comment by ankitguptaindia** [comment]
@amincdev @sourabhmatolia 

**Status-** Issue has been fixed. Ready to Merge. 
**Proof-** https://www.loom.com/share/a11577d2cab045c3b9bbbdf5df1a2d7b

**Review by sourabhmatolia — APPROVED** [review]

**Pull request merged**
