### PR TITLE
Fixed - The Visit Group button in Email Notification is not displaying properly

### LINKED ISSUE #1570: The Visit Group button in Email Notification is not displaying properly
**Describe the bug**
When translating the "Visit Group" button to a longer word or phrase, it does not fit in the button container.

**To Reproduce**
1. Switch to another language like German or translate the string "Visit Group" to a longer word or phrase.
2. Go to any groups and send an invite.
3. Check the email invitation.
4. Notice the misalignment on the button.

**Screenshots**
email

**Support ticket links**
https://secure.helpscout.net/conversation/1295890647/101189

### PR DESCRIPTION
**Pull request by kent-carlo**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1570.

### How to test the changes in this Pull Request:

1. Switch to another language like German or translate the string "Visit Group" to a longer word or phrase.
2. Go to any groups and send an invite.
3. Check the email invitation.
4. Notice the misalignment on the button.

### Proof Screenshots or Video
image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Adjusted css in email content for Visit group button to be able to handle longer characters.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @kent-carlo 

Issue >
I have checked with fix/1570 branch, I've set site language Arabic, and still, I'm getting issues, check below issue for proof.

Issue video.
https://www.loom.com/share/98d69e69f48c4dd98f20c759e9989576

cc @KartikSuthar @chetansatasiya 

Thank you

**Comment by kent-carlo** [comment]
@sumitbuddyboss checking again

**Comment by sumitbuddyboss** [comment]
Hello @kent-carlo 

Fixed>
I have tested in fix/1570 branch and it's working fine but in qa-ongoing, we didn't receive mail so @kent-carlo please make sure and debug if any conflict.

Video
https://www.loom.com/share/c842b8f8bced4efd843c27c0896bfb7f

Thank you

**Comment by kent-carlo** [comment]
Hello @sumitbuddyboss I have tried t with qa-ongoing branch and email is sending.
https://www.awesomescreenshot.com/video/5361653?key=2ad083cc9100af2dff24b263656091f0

**Comment by JetalDobariya** [comment]
Hello @kent-carlo 

I did verify this PR in qa-approved branch , now "Visit Group" button design looks good.
qa-approved : https://www.loom.com/i/90e0787f204a41f284602c26b1c5aca7
Backend : https://www.loom.com/i/799007514392438b872533673ea00b43

But there is an issue with qa-ongoing branch , please check below video for the Proof.
qa-ongoing : https://www.loom.com/i/76c3a860b51e43f2ac41f39b2d47fe8d
Issue : 
https://www.loom.com/share/3646602c74744eb18da36322fa29da60

Thanks!
CC : @chetansatasiya @KartikSuthar @sumitbuddyboss

**Pull request merged**
