### PR TITLE
Fix Header Search Bar - Multiple issues and Improvements

### LINKED ISSUE #2900: Header Search Bar - Multiple issues and Improvements
**Describe the bug**
If user is on search result page and searching something again from search page then auto suggest list is not appearing expected.

**To Reproduce**
1. Go to Search page
2. Search something
3. Now select any tab from results 
4. Search again and See error

**Expected behavior**
Search result dropdown should not hide on second attempt.

**Screenshots**
https://www.loom.com/share/2e9a6cf2d12f4ad7a0a0a43e2e41336b

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2900 #795

### Connected PR in Theme
https://github.com/buddyboss/buddyboss-theme/pull/1192

### How to test the changes in this Pull Request:

1. Go to Search page
2. Search something
3. Now select any tab from results
4. Search again

### Proof Screenshots or Video
https://www.loom.com/share/c39639ecee9d45388c2296582c815f47

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by KartikSuthar — DISMISSED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

The search result list getting hidden on scroll.

Issue video.
https://www.loom.com/share/bdab9c6d7f674c16bb63de70c64314f9

Thank you

**Comment by amincdev** [comment]
> Hello @amincdev
> 
> The search result list getting hidden on scroll.
> 
> Issue video.
> 
> https://www.loom.com/share/bdab9c6d7f674c16bb63de70c64314f9
> 
> Thank you

@sumitbuddyboss This issue is fixed. Now, the search results will only close by clicking on close button. Please take pull in `qa-ongoing`

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed >
A related issue is resolved, Header search bar issue is resolved Now, the search results will only close by clicking on close button
For the proof please check the below video

**Video**
https://www.loom.com/share/c06f738d3f3e490783eb56829db553ab

Ready for release 🚀 

Thank you

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I did verify this PR in qa-approved branch, but inside scroll is not visible if we have long search result.
inside

Please check and let me know!

Thanks!
CC : @sumitbuddyboss

**Comment by amincdev** [comment]
> Hello @amincdev
> 
> I did verify this PR in qa-approved branch, but inside scroll is not visible if we have long search result.
> inside
> 
> Please check and let me know!
> 
> Thanks!
> CC : @sumitbuddyboss

@JetalDobariya This issue is fixed now: https://prnt.sc/1t7q649

**Comment by JetalDobariya** [comment]
Hello @amincdev 

I did verify again this issue in qa-approved branch, now inside scroll is visible.
--> 
image

Thanks!

**Pull request merged**
