### PR TITLE
PROD-748 Forum reply notification issue fixed

### LINKED ISSUE #2879: When replying to any forum reply it always shows the name of the person who created the discussion in notification
**Describe the bug**
When replying to any forum reply it always shows the name of the person who created the discussion. This issue is happening in our demo as well. See the video: 

https://www.loom.com/share/f6499c6e1c084b2fb62c8ff24cd4a631

**To Reproduce**
See the above video.

**Environment**
Demo, local & client site

**Support ticket links**
https://secure.helpscout.net/conversation/1615546025/161296/

**Jira issue** : [PROD-748]

[PROD-748]: https://buddyboss.atlassian.net/browse/PROD-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2879  .

### How to test the changes in this Pull Request:

1. Create a forum reply to another person's reply
2. Login to the person where you create the reply
3. See the notification it shows the correct name.

### Proof Screenshots or Video

https://www.loom.com/share/c4a3da6dff414ce9997ccc0485582f45

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

**Comment by dipskakadiya** [comment]
Might be this fixed will affect https://github.com/buddyboss/buddyboss-platform/pull/2949 PR solution.

**Comment by mahedihasannoman** [comment]
> Might be this fixed will affect #2949 PR solution.

Hi @dipskakadiya I have checked this fix will not affect #2949 PR solution.

**Review by dipskakadiya — APPROVED** [review]

**Comment by aprilgeller** [comment]
Retested on QA ongoing branch. 
Status: Already Fixed

Proof Video recording: https://watch.screencastify.com/v/PVodGooXpWFagFy4SRLX

**Comment by KartikSuthar** [comment]
Closing the PR as its already fixed and released with PR: https://github.com/buddyboss/buddyboss-platform/pull/2907/files

**Pull request closed without merging**
