### PR TITLE
#2587 - Group Messages

### LINKED ISSUE #2397: Group private message page is broken when group contain thousand of users.
**Describe the bug**
When a group contain thousand of users then the group private message page is broken.

**To Reproduce**
https://www.loom.com/share/8f1ac2dda7794757b0b4503496924999

**Expected behavior**
Group private message page should be work fine.

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2397

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

**App Native Issue**
https://github.com/buddyboss/buddyboss-app-native/issues/1701

### API PR: 
https://github.com/buddyboss/buddyboss-platform-api/pull/348

### Bumped Reason
We have bumped this PR because it's dependent on the Batch Email Task so.
Dependent: https://github.com/buddyboss/buddyboss-platform/pull/2827

### CODE REVIEW

**Review by chetansatasiya — COMMENTED** [review]
@mohit-buddyboss @sumitbuddyboss @JetalDobariya Need to test group message from scratch and need to make sure nothing break.

**Comment by chetansatasiya** [comment]
@sourabhmatolia @firozwp 

We need to bump this PR as we need to test Group Messages from scratch and it will take a time for QA to check and right now QA don't have a time to test so need to bump this one.

**Comment by chetansatasiya** [comment]
We have bumped this PR because it's dependent on the Batch Email Task so.

CC @KartikSuthar @sourabhmatolia @firozwp

**Comment by joshuamarkt** [comment]
@sumitbuddyboss @JetalDobariya 
Don't forget to do this moving forward.
These are the TCs for #2911 #2587 

TC295 | Send message to all members of a group (Group page)
https://app.testlodge.com/a/26895/projects/41638/suites/187795?expand_section=289743#case_3366439
TC296 | Send message with single attached photo to all members of a group (Group page)
https://app.testlodge.com/a/26895/projects/41638/suites/187795?expand_section=289743#case_3366441
TC297 | Send message with multiple attached photo to all members of a group (Group page)
https://app.testlodge.com/a/26895/projects/41638/suites/187795?expand_section=289743#case_3366443
TC298 | Send message with single attached document to all members of a group (Group page)
https://app.testlodge.com/a/26895/projects/41638/suites/187795?expand_section=289743#case_3366447
TC299 | Send message with multiple attached documents to all members of a group (Group page)
https://app.testlodge.com/a/26895/projects/41638/suites/187795?expand_section=289743#case_3366450

**Comment by sumitbuddyboss** [comment]
Hello @sourabhmatolia @firozwp 

We need to bump this pr because we haven't got a chance to test and we need to spend more time for testing so need to bump.

Thank you

**Comment by sumitbuddyboss** [comment]
Note:
Group message > Private message
Total users does not appear in the private message section list. So I've created a separate issue for that.
https://www.loom.com/share/4e562eb0b5294614a3dbf01bfadd833a

Issue link
https://github.com/buddyboss/buddyboss-platform/issues/3188

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

Fixed >
A related issue is resolved, group message is working as expected. All the test cases are passed.

TC119 | Send message to all members of a group (Group page) - Pass
TC120 | Send message with single attached photo to all members of a group (Group page) - Pass
TC121 | Send message with multiple attached photos to all members of a group (Group page) - Pass
TC122 | Send message with single attached document to all members of a group (Group page) - Pass
TC123 | Send message with multiple attached documents to all members of a group (Group page) - Pass
TC124 | Check all the notifications - Pass

https://docs.google.com/spreadsheets/d/1v7bvYc-n-VZYQu8CcAcc9jLmHFduAQmxz_0n8lhjw7o/edit#gid=0

Ready for release 🚀 

Thank you

**Comment by JetalDobariya** [comment]
Hello @KartikSuthar 

I did verify this PR and related issue in qa-approved branch, Now group messages/Private Messages are working fine and listed all the TCs are Passed.
TC119 | Send message to all members of a group (Group page) - Pass
TC120 | Send message with single attached photo to all members of a group (Group page) - Pass
TC121 | Send message with multiple attached photos to all members of a group (Group page) - Pass
TC122 | Send message with single attached document to all members of a group (Group page) - Pass
TC123 | Send message with multiple attached documents to all members of a group (Group page) - Pass
TC124 | Check all the notifications - Pass

https://docs.google.com/spreadsheets/d/1v7bvYc-n-VZYQu8CcAcc9jLmHFduAQmxz_0n8lhjw7o/edit#gid=0

Thanks!
CC : @sumitbuddyboss @sourabhmatolia

**Pull request merged**
