### PR TITLE
PROD-743 #2906  - Fix: Generating video thumbnail stuck at loading

### LINKED ISSUE #2906: Generating video thumbnail stuck at loading
**Describe the bug**
When ffmpeg is installed in server and adding video, generating thumbnail stuck at loading. In my test, waited around 10 mins.

**To Reproduce**
1. Make sure site has ffmpeg installed, in my case I tested in demo site.
2. Upload video and trying changing thumbnail.
3. See that generating thumbnail stuck at loading.

**Expected behavior**
Should generate thumbnail.

**Screenshots**
https://www.loom.com/share/21ce639e9d264c34bd98fa3cc6524e15

**Environment**
Which site did you replicate this issue on?
Replicated on buddyboss demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1579569633/154974/

**Jira issue** : [PROD-743]

[PROD-743]: https://buddyboss.atlassian.net/browse/PROD-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2906 .

### How to test the changes in this Pull Request:

1. Make sure the site has ffmpeg installed.
2. Upload video and trying changing thumbnail.
3. Once the thumbnail is generated in the background, see the thumbnail on the pop-up.

### Proof Screenshots or Video
https://vimeo.com/622320805/032f78cbb0

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — DISMISSED** [review]

**Review by dipskakadiya — DISMISSED** [review]

**Review by chetansatasiya — DISMISSED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Issue >

I checked with fix/2906 and qa-ongoing branch and the latest changes not working.

Issue video:
https://www.loom.com/share/10805d9e81b442afa11dd97887311c4d


Test status: Fail

Thank you

**Comment by milanhirapra** [comment]
@sumitbuddyboss 

I fixed this issue. Please check proof video: https://vimeo.com/658503053/d3d50dcb18

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Fixed >
A Related issue is resolved now the thumbnail is generating for the proof please check the below video.


### Test Case:
Generating video thumbnail stuck at loading

Pre-Requisite:
1] Make sure the site has FFmpeg installed

To Reproduce
1) Upload the video and try to change the thumbnail.
2) See error


Video:
https://www.loom.com/share/f8644dfeb8cf427c945f65f2adde54fa

Test status: PASS

Ready for release 🚀 

Thank you

**Comment by basil-buddyboss** [comment]
Hi @milanhirapra 

This has been tested in the QA-approved branch and there were no issues encountered.

Result: Passed

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
