### PR TITLE
Fixed - Private message threads does not loads more then 20

### LINKED ISSUE #2051: Private message threads does not loads more then 20
**Describe the bug**
There is no way to load private message threads more then 20. By default it loads 20 threads then it does not loads any older threads.

**To Reproduce**
Create private message threads more then 20 and reload the private message page. It will show only 20 threads. No way to load older threads.

[https://www.loom.com/share/3af6238cb84d4d4b83337a58e4ad447a](https://www.loom.com/share/3af6238cb84d4d4b83337a58e4ad447a)

**Support ticket links**
[https://secure.helpscout.net/conversation/1394162417/119455](https://secure.helpscout.net/conversation/1394162417/119455)

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2051 

### How to test the changes in this Pull Request:

1. Go To Message screen
2. Try to load more thread by scrolling down
3. It should load more threads now

### Proof Screenshots or Video

https://www.loom.com/share/52fc4779bfa84713b02fbb57ffacb917

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
@mehulkaklotar @chetansatasiya I have fixed this issue by adding `Math.round()`, Because in comparison I was getting values like `353 and 353.266` . So, now it is working fine, Please review it and let me know if this should be fixed in some other way.

**Review by chetansatasiya — DISMISSED** [review]
@amincdev Merge in dev and add in testing.

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @amincdev 
Kindly merge it into dev

**Comment by sourabhmatolia** [comment]
@mohit-buddyboss 

merged in dev branch just now. Thnx

**Comment by mohit-buddyboss** [comment]
@amincdev 

Verified this on the branch 'fix/2051' and on dev branch.  Issue is still exist on both the branches. 
Only 20 number of threads are appearing and on adding new message older threads are getting disappear. Kindly look into this.
Video: https://www.loom.com/share/96d678a793b24b6694a2373cc3646bde

cc @chetansatasiya

**Comment by amincdev** [comment]
> @amincdev
> 
> Verified this on the branch 'fix/2051' and on dev branch. Issue is still exist on both the branches.
> Only 20 number of threads are appearing and on adding new message older threads are getting disappear. Kindly look into this.
> Video:
> 
> https://www.loom.com/share/96d678a793b24b6694a2373cc3646bde
> 
> cc @chetansatasiya

@mohit-buddyboss Issue is fixed and merged in dev.

**Comment by mohit-buddyboss** [comment]
@amincdev 

FIXED> Tested this on dev branch. Tested old threads are getting load or not. Also, tested this by creating single user, multi user and group thread new messages and by applying message access restrictions. Now, loader is appearing and threads and all older threads are getting load. 

Video: https://www.loom.com/share/71e9c9f32a73437fb7d3337e4ad92eff
Related issue is resolve now and PR is ready to merge.

cc @mehulkaklotar @sourabhmatolia

**Pull request merged**
