### PR TITLE
#800 - BuddyBoss Email Header > can't select entire Logo

### LINKED ISSUE #800: BuddyBoss Email Header > can't select entire Logo
**Describe the bug**
While I am added Logo on BuddyBoss Email Header > can not select the entire logo and also there is no option to skip image crop.

**To Reproduce**
1. Go to 'Admin Dashboard - Buddyboss - Email'
2. Click on 'Customize Layout - Header - Upload logo'
3. See error

**Expected behavior**
Can select the entire logo or have a button to skip the image crop functionality.

**Screenshots**
https://www.loom.com/share/4f5021d4029d460eb141ceee7efabf71

### PR DESCRIPTION
**Pull request by sagarjadhav**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #800 .

### Other information:

* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
@sagarjadhav 

Now I am checking again the same action related to WordPress, Password Reset emails template is broken. https://prnt.sc/s77gap

https://www.loom.com/share/34c63f02849142a68f18f249e285a227

**Comment by sagarjadhav** [comment]
@ankitguptaindia Fixed template issues

**Comment by ankitguptaindia** [comment]
@sagarjadhav @eisenwasser 

Fixed. Both types of emails templates 1) Emails coming from Platform and 2) WordPress Core emails are Fixed now.

WP Mail - https://prnt.sc/s7cjdg. 
Platform Email - https://prnt.sc/s7cmi2
Site Admin Email Change - https://prnt.sc/s7co67

**Comment by eisenwasser** [comment]
@sagarjadhav @ankitguptaindia 

When I go into Customizer > BuddyBoss Emails. It is now just "There has been a critical error on your website."

https://prnt.sc/sb2hk1

That is after merging DEV branch into this one.

**Comment by sagarjadhav** [comment]
@eisenwasser Code was not merged properly and some code was lost. I have added back those fixes.

@ankitguptaindia Can you please verify once again?

**Comment by ankitguptaindia** [comment]
@mohit-buddyboss you can start with this task.
Let me know if need help

**Comment by mohit-buddyboss** [comment]
@sagarjadhav ,

I tested this and found out that layout of emails which we are receiving from WordPress are getting broken

1) Email which user receive on creating user from WP back end. 
[Email Screenshot](https://prnt.sc/sc8xxs)

2) Email which user receive to reset password .
[Email Screenshot](https://prnt.sc/sc8zuk)

For more clarification kindly see this [Video](https://www.loom.com/share/067aa86b8e8840ccb7033f1c3098d06b)

**CC** @ankitguptaindia

**Comment by ankitguptaindia** [comment]
@sagarjadhav Cross checked the issue. https://prnt.sc/sgnswb WP default email having issue. 

You can use this site to test. This site has plugin of `fix/800` branch.

**Comment by sagarjadhav** [comment]
@eisenwasser @ankitguptaindia Fixed given issues.

**Comment by eisenwasser** [comment]
@ankitguptaindia Can you retest this please

**Comment by ankitguptaindia** [comment]
@eisenwasser @sagarjadhav 

This is working now. I am using `fix/800` branch to test.

Platform related emails - works fine -  https://prnt.sc/sybrwn. https://prnt.sc/sybzax
WP related emails - works fine -  https://prnt.sc/sybvqg. https://prnt.sc/syc49r


Quick Summery - https://www.loom.com/share/c8436f100d4b4b259cf23b78bc761488

**Pull request merged**
