### PR TITLE
Fixed: Password reset email is not displaying properly when Paid Membership Pro is active

### LINKED ISSUE #1704: Password reset email is not displaying properly when Paid Membership Pro is active
**Describe the bug**
When Paid Membership Pro is active along with the BuddyBoss Platform, the password reset email source code contains several `<BR>` tags causing to have unnecessary spaces on the final output.

**To Reproduce**
1. Activate Paid Membership Pro
2. Go to the reset password page.
3. Try to reset your password.
4. Check the email and see the error

**Screenshots**
pmpro

**Support ticket links**
https://secure.helpscout.net/conversation/1300227041/101884
https://secure.helpscout.net/conversation/1322282892/105612

### PR DESCRIPTION
**Pull request by shohel**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1704  .

### Changelog entry

> Fixed: Password reset email is not displaying properly when Paid Membership Pro is active

### CODE REVIEW

**Comment by shohel** [comment]
@sourabhmatolia 

Issue fixed

**Review by chetansatasiya — COMMENTED** [review]
@shohel 

@KartikSuthar Added this filter here https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/bp-core-functions.php#L3425 to fix the invite email issue and now if you remove this filter then maybe it will break again the invite email.

@shohel Can you please cross check with like it's not going to break anything in invite email?

**Comment by shohel** [comment]
@chetansatasiya 

 here https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/bp-core-functions.php#L3425 is also removing the filter. As did I, so technically it should not create any issue.

I will check it soon.

**Review by chetansatasiya — APPROVED** [review]
@shohel Approved!

**Comment by chetansatasiya** [comment]
@ankitguptaindia This is ready for testing

**Comment by ankitguptaindia** [comment]
@chetansatasiya @sourabhmatolia 

Issue has been fixed. Tested with dev branch and also tested some other emails format view. Looks Fine now.

**Password Reset Email  - https://prnt.sc/vclzcq**
Activate your account - https://prnt.sc/vcm0cg
Invitation to the group: - https://prnt.sc/vcm0t5
Messages - https://prnt.sc/vcm13v

**Review by ankitguptaindia — APPROVED** [review]

**Pull request merged**
