### PR TITLE
PROD-885 Fix : #1849 Fixed only show relevant photos

### LINKED ISSUE #1849: Only show relevant photos to user when relevant activity feed is ticked
**Describe the bug**
Some days ago, you have implemented a very nice feature : "**Show relevant activity feed**". When the checkbox is ticked in the admin panel ("Only show relevant activity feed"), photos displayed in the page **"photos" should also be relevant to user**. But this is not the case for the moment. 

=> https://demos.buddyboss.com/online-communities/photos/

**To Reproduce**
1. Create BuddyBoss Sandbox
2. Go to Joseph profile and click on "View As"
3. Go to Groups page of "Sports Players"
4. Create an activity in that group with some photos attached.
5. Go to Alyssa profile and click on "View As"
6. In the top main menu, go to Pages -> Photos

Photos uploaded by Joseph in the group Sports Players are displayed to Alyssa. But Alyssa is not a member of that group. Those photos are not relevant to her !

**Expected behavior**
Only show relevant photos (based on the development of relevant activity feed)

**Screenshots**
none

**Support ticket links**
none

**Jira issue** : [PROD-885]

[PROD-885]: https://buddyboss.atlassian.net/browse/PROD-885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #1849.

### How to test the changes in this Pull Request:

1. Log in to the user profile.
3. Go to any joined group.
4. Create an activity in that group with some photos attached.
5. Log in to another user profile that is not a connection of the first user.
6. In the top main menu, go to Pages -> Photos

### Proof Screenshots or Video

https://www.loom.com/share/b74d6085dbbb406cbc9a713cadef2bea

### CODE REVIEW

**Comment by ExoGeek** [comment]
Hi,

Could you please release this fix in the next release ?

Thanks in advance

**Comment by ExoGeek** [comment]
Hello,

If this issue is resolved, may I ask you to release this fix in the next release ? It's very weird that members do see group's photos event if they are not member of that group...

Thanks

**Comment by ExoGeek** [comment]
Hi @firozwp, do you close this pull request because that "issue" has been resolved in a future release of Buddyboss ?

**Comment by ExoGeek** [comment]
@firozwp Sorry but I think something goes wrong here. There's no reason to see medias from groups you are not a member of. This is absolutely not relevant to user... You do not see those medias on the activity feed (when relevant activity is checked). Why do you see those medias in the screen "photos", "videos" or "documents" ?

Don't you think that something needs to be implemented to only show relevant medias ?

See : #1849

**Comment by firozwp** [comment]
@ExoGeek 
I will ask a developer to share more detail on this. 
cc: @chetansatasiya

**Comment by chetansatasiya** [comment]
@ExoGeek Thanks for your feedback on this and I appreciate it. I take a look into this and this is something I can consider a feature request, given code in the PR will not work what you are expecting. We need to make complete scope for all the places like Photos, Videos, and Documents. However, I request you submit a feature request here https://www.buddyboss.com/roadmap/  

CC @firozwp @sourabhmatolia @mikejyoung

**Pull request closed without merging**
