### PR TITLE
#1697 - Fix activity more link

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@chetansatasiya `bp_blog_posts_content_activity_read_more_added` Meta not required. you can directly check in content `read more` link exist or not. 
you can do something link this with condition 
`false !== strrpos( $excerpt, __( 'Read more', 'buddyboss' ) ` 
OR
you can add one unique class `blog-read-more-link` with read more link and find that class  in content. 
`false !== strrpos( $excerpt, 'class="blog-read-more-link"')` 
Let me know if you need any further explanation

**Comment by chetansatasiya** [comment]
@dipskakadiya This is ready for the review.

**Review by dipskakadiya — DISMISSED** [review]
@chetansatasiya Approved. @ankitguptaindia Ready for testing. PR merged in dev.

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 

I've checked my **Old post**, and as per old post the read more is still appearing below image. 
https://prnt.sc/va1o6u

CC @ankitguptaindia

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> I've checked my **Old post**, and as per old post the read more is still appearing below image.
> https://prnt.sc/va1o6u
> 
> CC @ankitguptaindia

@sumitbuddyboss @ankitguptaindia Old post remain as it is if post have a content.

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 
Fixed >Tested this on the Dev branch and everything working as expected and PR is ready to release

For the proof please check the below video.
https://www.loom.com/share/e2aa403f2ef2423e86081ce2348de10c

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

**Issue:**
While checking this I've noticed that Read more is appearing default while posting anything when we create a post from the backend.

Screenshot:
https://prnt.sc/va3ues

CC @ankitguptaindia

**Comment by amincdev** [comment]
> Hello @chetansatasiya
> 
> **Issue:**
> While checking this I've noticed that Read more is appearing default while posting anything when we create a post from the backend.
> 
> Screenshot:
> https://prnt.sc/va3ues
> 
> CC @ankitguptaindia

@sumitbuddyboss That is the default functionality, When Admin publish a blog post then it's activity should have "Read More" link that links the blog post. Link is not relative to content.

**Comment by sumitbuddyboss** [comment]
> > Hello @chetansatasiya
> > **Issue:**
> > While checking this I've noticed that Read more is appearing default while posting anything when we create a post from the backend.
> > Screenshot:
> > https://prnt.sc/va3ues
> > CC @ankitguptaindia
> 
> @sumitbuddyboss That is the default functionality, When Admin publish a blog post then it's activity should have "Read More" link that links the blog post. Link is not relative to content.

Thanks for the clarification @amincdev

**Comment by sumitbuddyboss** [comment]
@chetansatasiya @amincdev  
PR is ready to release 

CC @ankitguptaindia

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
This is not working! https://prnt.sc/vcmh8c

We need to fix this properly before we can merge it. Read more is coming so many times when it is not neccessary.

@chetansatasiya

**Comment by chetansatasiya** [comment]
> This is not working! https://prnt.sc/vcmh8c
> 
> We need to fix this properly before we can merge it. Read more is coming so many times when it is not necessary.
> 
> Issues to be fixed:
> 
> 1. #1524
> 2. #1420
> 
> @chetansatasiya

@sourabhmatolia @mehulkaklotar @dipskakadiya  We need to take a proper decesion here to make it proper because this is going back and forth.

**Comment by chetansatasiya** [comment]
@mehulkaklotar This is ready for you to review.

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
@chetansatasiya 

Issues found: 
- posting youtube video doesn't embed it in news feed https://prnt.sc/vk0o8a
- posting youtube video doesn't embed with long text https://prnt.sc/vk0q4d

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Issues found:
> 
> * posting youtube video doesn't embed it in news feed https://prnt.sc/vk0o8a
> * posting youtube video doesn't embed with long text https://prnt.sc/vk0q4d

@mehulkaklotar Both issues are fixed now 
https://prnt.sc/vk4rc3
https://prnt.sc/vk4ru5

**Review by mehulkaklotar — APPROVED** [review]
approved!

@ankitguptaindia needs testing.

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

Fixed >I've checked in the dev branch The activity Read more link is working fine from my end. For the proof please check the below video.

Video
https://www.loom.com/share/fe9a1086805548d8bcb6056cfc2a02ca

@chetansatasiya Ready for release 🚀 

CC @ankitguptaindia

**Review by mehulkaklotar — APPROVED** [review]

**Pull request merged**
