### PR TITLE
PROD-762 #2793 - fix: Cannot translate the Profile Photo and Cover Photo on Elementor Profile Completion widget

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes https://github.com/buddyboss/buddyboss-platform/issues/2793 .

### How to test the changes in this Pull Request:

1. Create an Elementor page
2. Insert Profile Completion widget. https://i.ibb.co/RHsV6Nm/profile.jpg
3. Make sure that you enable Profile and Cover Photo.
4. Now, using the Loco Translate plugin, try to translate all the instances of **"Profile Photo"** and **"Cover Photo"**.
5. Go to BuddyBoss > Tools > Repair Community
6. Check/Enable **Repair default profile set and fields** option and click on **Repair Items** button
7. Lastly, go to frontend and notice those strings are now translated

### Proof Screenshots or Video
https://vimeo.com/588713860/551918f09c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@milanhirapra Can you explain how cache affecting translation?

**Comment by milanhirapra** [comment]
@dipskakadiya 
User profile completion information is stored in the user meta table. If we will translate **profile photo** and **cover photo** strings from the backend then it will not translate.
So, this `bp_core_xprofile_clear_all_user_progress_cache()` function removes user profile complete information from user meta table.

**Review by dipskakadiya — APPROVED** [review]

**Review by dipskakadiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Issue >
I'm getting fatal error when selecting buddyboss-platform from the plugin section, I've also cross-check with buddyboss platform pro and theme and there it's working fine.

Issue video:
https://www.loom.com/share/7bd7f629c1864522a9101d8d365e468f


Thank you

**Comment by milanhirapra** [comment]
Hello @sumitbuddyboss 

I checked your last concern in other sites with this branch and it's working fine.
Please check here: https://vimeo.com/656052541/ac974179e4

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Issue >
I am not able to test this PR because when I select buddyboss plugin in loco translate at that time gives a fatal error. Can you please make sure about this?

Issue video:
https://www.loom.com/share/ca36466bf9af450eaeb0d6c8972e84da

Getting the same issue in 
https://github.com/buddyboss/buddyboss-platform/pull/3049#issuecomment-994516556

cc @chetansatasiya @KartikSuthar

**Pull request merged**
