### PR TITLE
BB REST API - Activity Endpoint : Relevant Feed

### LINKED ISSUE #1812: BB REST API : Activity Comment - PHP Fatal Error: Uncaught ArgumentCountError: Too few arguments bp_blogs_activity_comment_content_with_read_more
**Describe the bug**
With the latest version of BuddyBoss, there's a PHP Fatal Error when you try to post comment using BB REST API.

```
[21-Nov-2020 10:32:41 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function bp_blogs_activity_comment_content_with_read_more(), 1 passed in /opt/htdocs/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/bp-activity-filters.php:2348
Stack trace:
#0 /opt/htdocs/wp-includes/class-wp-hook.php(287): bp_blogs_activity_comment_content_with_read_more()
#1 /opt/htdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#2 /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/classes/class-bp-rest-activity-endpoint.php(1101): apply_filters()
#3 /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/classes/class-bp-rest-activity-endpoint.php(1171): BP_REST_Activity_Endpoint->render_item()
#4 /opt/htdocs/wp-content/plugins/buddyb in /opt/htdocs/wp-content/plugins/buddyboss-platform/bp-activity/bp-activity-filters.php on line 2348
```

**To Reproduce**
```
Entête : POST /wp-json/buddyboss/v1/activity/1218/comment HTTP/1.1
Données : { "content":"Test Comment", "parent_id":1218 }
```

**Expected behavior**
none

**Screenshots**
none

**Support ticket links**
none

### LINKED ISSUE #1816: BB REST API - Activity Endpoint : Show relevant Feed doesn't work in REST API
**Describe the bug**
This issue is related to the new functionality of "Relevant Feed"  #1311 

When you create an activity not relevant to a user, that activity is not shown on the website (OK) but it is shown in the REST API (KO).

**To Reproduce**
1. Create an activity in a public group
2. Login with a user that is not member of that group
3. Make the request `GET {{host}}/wp-json/buddyboss/v1/activity`

**Expected behavior**
Activities not relevant should not be returned in the REST API.

**Screenshots**
none

**Support ticket links**
none

### LINKED ISSUE #1858: BB REST API - Signup Endpoint : Password doesn't match after activation
**Describe the bug**
When a user register a new account using the rest api, a default generated password is attached to the user. Normally, when user activates his account, the default password is replaced by the user password.

But when the user clicks on the activation link received by email, the default password is not replaced. Thus, user can't login in with his password !

This is also the case when an administrator manually activate an account (default password is not replaced).

**To Reproduce**
1. Register a new user using the BB REST API

```
POST {{host}}/wp-json/buddyboss/v1/signup
Content-Type: application/json

{
  "signup_email": "neville@buddyboss.com",
  "signup_password": "abcdef1234",
  "field_1": "Neville",
  "field_2": "Buddy",
  "field_3": "exo_neville"
}
```

2.1. Go to wp-admin -> Users -> Pending Signups AND manually activate the user using the link "Activate"
2.2. Click on the activation link received by email.

**Expected behavior**
After activation, user should be able to log in with his password (the one entered by the user in the registration form)

**Screenshots**
none

**Support ticket links**
none

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1816 
Fixes #1812
Fixes #1858

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by mehulkaklotar — DISMISSED** [review]
Looks good! 👍 

@KartikSuthar Let's test it.

**Comment by ExoGeek** [comment]
@KartikSuthar Could you also add the correction of the issue #1858 for the next release (1.5.6) ?

**Review by mehulkaklotar — APPROVED** [review]
Merging 👍

**Comment by sourabhmatolia** [comment]
@ExoGeek 

Issue mentioned above is released in BuddyBoss Platform v1.5.6

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-6/

Please update the plugin to see the latest changes.

Thank you.

**Pull request merged**
