### PR TITLE
Network Search - Media

### LINKED ISSUE #1316: Network Search - Media search not working
**Describe the bug**
When network search in media is enabled and we search media name that media not working

**To Reproduce**
1. Go to Buddyboss -> Setting ->Search
2. Check media https://prnt.sc/tv33ea
3. Go to the front and search any media name
4. See result

**Expected behavior**
Media result should show when media is enabled
Note: 
- Ignore all the document(Because the document is separate things)
  https://prnt.sc/tv38mr
- Check BP media privacy and ignore if the media has not allowed it.

**Support ticket links**
Client site

### PR DESCRIPTION
**Pull request by dipskakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Attachment search issue fixed
Media photo & albums network search added

### How to test the changes in this Pull Request:

Go to Buddyboss -> Setting ->Search
Check media https://prnt.sc/tv33ea
Go to the front and search any media name
See result

### Connected PR in Theme
https://github.com/buddyboss/buddyboss-theme/pull/1093

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by dipskakadiya** [comment]
@amincdev 
Refer blow design for media and albums search. 

Albums Desing: 
Screen Shot 2020-10-05 at 9 10 02 PM

Photo Design : 
Photos Result

**Review by mehulkaklotar — DISMISSED** [review]
@dipskakadiya Looks good!

@ankitguptaindia needs testing!

**Comment by ankitguptaindia** [comment]
@dipskakadiya Can you merge this in to Dev as per new process?

**Comment by dipskakadiya** [comment]
@ankitguptaindia Branch merged to dev. Ready for testing

**Comment by ankitguptaindia** [comment]
@dipskakadiya 

Can you create a video for this and explain what changes will appear after introducing your changes.
I can see difference in option in setting ie. In your screenshot Media checkbox has 2 sub-options.https://prnt.sc/tv33ea
but in my site it has NO suboptions. https://i.imgur.com/q1zrwEc.jpg

And Question- What types of Media it will search?
- Suppose I disabled Photos option from search and enabled Media option from setting then what will be result.?


Bug- When searching any file which is listed in WP Media library then it shows 404 on click the media.
Refer - https://www.loom.com/share/8d8d05885808494b9b8b4e11f6b6af87

**Comment by dipskakadiya** [comment]
> @dipskakadiya
> 
> Can you create a video for this and explain what changes will appear after introducing your changes.
> I can see difference in option in setting ie. In your screenshot Media checkbox has 2 sub-options.https://prnt.sc/tv33ea
> but in my site it has NO suboptions. https://i.imgur.com/q1zrwEc.jpg
> 
> And Question- What types of Media it will search?
> 
> * Suppose I disabled Photos option from search and enabled Media option from setting then what will be result.?
> 
> Bug- When searching any file which is listed in WP Media library then it shows 404 on click the media.
> Refer - https://www.loom.com/share/8d8d05885808494b9b8b4e11f6b6af87

@ankitguptaindia I think you testing the wrong thing, Media search means our BuddyBoss media component. You are search attachment

**Comment by ankitguptaindia** [comment]
@dipskakadiya @amincdev 

Some issue with this module-

1. when searching any media then this is redirecting to photos page instead of particular media so if any image is listing in bottom of photos page after load more then it looks not searchable. 
Particular searched image should appear on click search result.
2. If media is coming from Group then group privacy looks weird in search result  https://prnt.sc/v73biq
3.  If disabled all search box including Group But search is still searching in Group Media and showing result.  https://prnt.sc/v73ziv
4. When searching Group's Album in header search it is giving some warnings.
Notice: Trying to get property ‘media’ of non-object in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/bp-media-template.php on line 764
5. Media is not getting searched if available in Member's Album via image name.
https://www.loom.com/share/d4a24bf0407c44e087ec6bbebd64a042

**Comment by dipskakadiya** [comment]
@ankitguptaindia 
1) when searching any media then this is redirecting to photos page instead of particular media so if any image is listing in bottom of photos page after load more then it looks not searchable.
Particular searched image should appear on click search result.
> We don't have any URL for single Photo activity look like it's feature work

2) If media is coming from Group then group privacy looks weird in search result https://prnt.sc/v73biq
> Fixed 

3) If disabled all search box including Group But search is still searching in Group Media and showing result. https://prnt.sc/v73ziv
> Can you share your setting screenshot

4) When searching Group's Album in header search it is giving some warnings.
Notice: Trying to get property ‘media’ of non-object in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/bp-media-template.php on line 764
> Fixed

5) Media is not getting searched if available in Member's Album via image name.
https://www.loom.com/share/d4a24bf0407c44e087ec6bbebd64a042
> I can't replicate this issue

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia
> 
> 1. when searching any media then this is redirecting to photos page instead of particular media so if any image is listing in bottom of photos page after load more then it looks not searchable.
>    Particular searched image should appear on click search result.
> 
> > We don't have any URL for single Photo activity look like it's feature work

Okay. I will create  new issue for this concern.

----------
> 
> 1. If media is coming from Group then group privacy looks weird in search result https://prnt.sc/v73biq
> 
> > Fixed
> 
----------

FIXED> Looks fine..

----------

> 1. If disabled all search box including Group But search is still searching in Group Media and showing result. https://prnt.sc/v73ziv
> 
> > Can you share your setting screenshot


PLESE refer this  - https://i.imgur.com/YvlqIPO.jpg
https://www.loom.com/share/5889d5e4599c4accabc591a7a2db08f3

----------

> 1. When searching Group's Album in header search it is giving some warnings.
>    Notice: Trying to get property ‘media’ of non-object in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/bp-media-template.php on line 764
> 
> > Fixed

FIXED.
----------

> 
> 1. Media is not getting searched if available in Member's Album via image name.
>    https://www.loom.com/share/d4a24bf0407c44e087ec6bbebd64a042
> 
> > I can't replicate this issue

@dipskakadiya 

I tried to explain how you can reproduce in this video - https://www.loom.com/share/2fb3a106938e4f6d895b3d8fa3fab49f

----------

Issue -  Recently added image in member photos section is also not searchable in header search.
Refer - https://www.loom.com/share/6cfb7bde345c4e17a6233dad46b8229e

------
Issue -  Notice: Undefined index: message in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/classes/class-bp-media.php on line 632

when searching image in Logged out mode. https://www.loom.com/share/a4a75bd6e2584608ab8b9eb87257272e
-------

@amincdev 
Issue - The height of search box depending on search result item. If any image has extra height then search result appearing with extra height. It looks weird https://www.loom.com/share/a251cd29dbc045ce9ec4754730531514

-------
 Issue - When selecting any GIF and searching that GIF then it is appearing as MEDIA. Is it intended?
FYI- It  is appearing in result only when enabled Media checkbox from Search setting of plugin.
https://www.loom.com/share/4d5753026daf4d0db1bc0ca4af90aa36

--------

Issue -  Media uploaded as comment in activity feed is not appearing on search result. Although appearing same media if added as Documents on same comment.
https://www.loom.com/share/45141884f817453b9b56f9ae35003704
-------

**Comment by dipskakadiya** [comment]
@ankitguptaindia 

If disabled all search box including Group But the search is still searching in Group Media and showing the result.
> you disabled group component, group component doesn't affect media search. this is the same as Currently search working for documents. I don't think this is a bug

Media is not getting searched if available in Member's Album via image name.
https://www.loom.com/share/d4a24bf0407c44e087ec6bbebd64a042
> As discuss on call, Working fine for me

Issue - Notice: Undefined index: message in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/classes/class-bp-media.php on line 632
> Fixed

Issue - Media uploaded as comment in activity feed is not appearing on search result. Although appearing same media if added as Documents on same comment.
https://www.loom.com/share/45141884f817453b9b56f9ae35003704
> As discuss on call, Working fine for me

Issue - When selecting any GIF and searching that GIF then it is appearing as MEDIA. Is it intended?
FYI- It is appearing in result only when enabled Media checkbox from Search setting of plugin.
https://www.loom.com/share/4d5753026daf4d0db1bc0ca4af90aa36
> it's not bug. it's intended. it's default Wordpresss single attachment page

**Comment by amincdev** [comment]
@ankitguptaindia 

> Issue - The height of search box depending on search result item. If any image has extra height then search result appearing with extra height. It looks weird

Fixed

**Comment by ankitguptaindia** [comment]
> If disabled all search box including Group But the search is still searching in Group Media and showing the result.
> 
> > you disabled group component, group component doesn't affect media search. this is the same as Currently search working for documents. I don't think this is a bug.

OKAY

> 
> Media is not getting searched if available in Member's Album via image name.
> 
> https://www.loom.com/share/d4a24bf0407c44e087ec6bbebd64a042
> 
> > As discuss on call, Working fine


@dipskakadiya 
NOTE- I cross tested this and found when searching media with file extension then it is not searching media BUT if search with extension then it gives the result.
On the other hand. If searching same thing in WordPress Media search box then it give same result with and without extension. 

For eg. If searching `captian-america.jpg` then it doesn't give result. If `captian-america` then gives the result. 

REFER-  https://www.loom.com/share/18ce5d8ec5bb41ad82a567f8f27f41dd 

> 
> Issue - Notice: Undefined index: message in /Users/ank/Local Sites/julytest/app/public/wp-content/plugins/buddyboss-platform/src/bp-media/classes/class-bp-media.php on line 632
> 
> > Fixed
> 

👍 

> Issue - Media uploaded as comment in activity feed is not appearing on search result. Although appearing same media if added as Documents on same comment.
> 
> https://www.loom.com/share/45141884f817453b9b56f9ae35003704
> 
> > As discuss on call, Working fine.

Yep. my test was with extension. Above fix will also fix this.  
> 
> Issue - When selecting any GIF and searching that GIF then it is appearing as MEDIA. Is it intended?
> FYI- It is appearing in result only when enabled Media checkbox from Search setting of plugin.
> 
> https://www.loom.com/share/4d5753026daf4d0db1bc0ca4af90aa36
> 
> > it's not bug. it's intended. it's default Wordpresss single attachment page

**Okay. If this is intended.** 

> @ankitguptaindia
> 
> > Issue - The height of search box depending on search result item. If any image has extra height then search result appearing with extra height. It looks weird
> 
> Fixed

**FIXED. 👍**

**Comment by dipskakadiya** [comment]
@ankitguptaindia 
I cross tested this and found when searching media with file extension then it is not searching media BUT if search with extension then it gives the result.
On the other hand. If searching same thing in WordPress Media search box then it give same result with and without extension.
> Both are a different entity, With WordPress Media extension also saved in the title so it's searchable, with BP Photo we only storing title without extension so it's not searchable with extension

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia
> I cross tested this and found when searching media with file extension then it is not searching media BUT if search with extension then it gives the result.
> On the other hand. If searching same thing in WordPress Media search box then it give same result with and without extension.
> 
> > Both are a different entity, With WordPress Media extension also saved in the title so it's searchable, with BP Photo we only storing title without extension so it's not searchable with extension

Okay 👍  Thanks for clarification.

**Comment by ankitguptaindia** [comment]
**Status-** Above reported issues have fixed. Some scenario reported by me above are intended explained by developer.  
One major concern was related to search, is a feature addition and created saparate request here https://github.com/buddyboss/buddyboss-platform/issues/1707

**Proof-** https://www.loom.com/share/b33ce62eb4674453a02b9e75ab275995

**Review by ankitguptaindia — APPROVED** [review]
**Closing Remark- ** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [ ] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [ ] Tested negative test scenario

- [ ] Updated Labels as per current status

**Final Update-** All known issues has been fixed.  Ready to Release. 🚀

**Review by mehulkaklotar — APPROVED** [review]
approved! 🚀

**Pull request merged**
