### PR TITLE
#1386 fix subfolder download issues

### LINKED ISSUE #1386: When you download the document folder , the sub-folder is missing.
**Describe the bug**
When you download the document folder , the sub-folder is missing. 

**To Reproduce**
1.Create a 'folder' for document.
2. Create a sub-folder.
3. Download the parent folder.
4.  The sub-folder is missing in zip file.

**Expected behavior**
Sub-folder should also be there in download. 

**Support ticket links**
https://secure.helpscout.net/conversation/1257507112/88857/

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1386 

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

I am using NON Fixed branch i.e. `Master` and `Dev` But subfolder are working expected there as well.
I could not face any issue while downloading the subfolder in Master branch as well.
Can you share in which circumstances this issue is appearing?

Refer for more details-  https://www.loom.com/share/5f2c49ebf2394370b99c4710b6fb6040

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> I am using NON Fixed branch i.e. `Master` and `Dev` But subfolder are working expected there as well.
> I could not face any issue while downloading the subfolder in Master branch as well.
> Can you share in which circumstances this issue is appearing?
> 
> Refer for more details- https://www.loom.com/share/5f2c49ebf2394370b99c4710b6fb6040

@ankitguptaindia try in our demo server not working their and also in customer site as well

**Comment by ankitguptaindia** [comment]
I was not able to replicate this issue on my local site, it was working on my local with master branch.
But this functionality was not working on @Anve-sri 's site. On the flywheelsites sites Folder downloading was not workig as expected.
Tested on flywheelsites and it is working now.




https://www.loom.com/share/ebf4f31ce74d44c7a36d6f6f74dda1bc

**Review by ankitguptaindia — APPROVED** [review]
@chetansatasiya 

**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [x] Tested negative test scenario

- [ ] Updated Labels as per current status

**Final Update-**Ready to Merge. 🚀

**Pull request merged**
