### PR TITLE
Added Feature: Show relevant Feed - at the global news feed page #1311

### LINKED ISSUE #1311: Show relevant Feed - at the global news feed page
**Is your feature request related to a problem? Please describe.**

In the global news feed page, there should be an option to show only content relevant to the users.

**Describe the solution you'd like**

BuddyBoss Settings > Activity > Add an option (Show Relevant Feed)

**Support ticket links**

https://www.facebook.com/groups/buddyboss/permalink/1004572619977580/

**Suggestion From Michael**

https://www.loom.com/share/67989c746c9248cd9ffe38472ec5f4fd

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1311 .

### How to test the changes in this Pull Request:

1. GO to BuddyBoss settings > Activity
2. Check **Show Relevant Feed**
3. Go to the global new feed page, and see, all posts relevant to members.

### Proof Screenshots or Video

https://www.loom.com/share/f32055a9a3fe4c459b242110b3e1e553

### Changelog entry

> Added Feature: Show relevant Feed - at the global news feed page

### CODE REVIEW

**Comment by shohelbuddyboss** [comment]
@chetansatasiya @mehulkaklotar 

Added Feature: Show relevant Feed - at the global news feed page. Please review this PR when you have time.

cc: @sourabhmatolia @eisenwasser

**Comment by shohel** [comment]
@dipskakadiya 

This PR is ready to code review

cc: @sourabhmatolia

**Review by dipskakadiya — DISMISSED** [review]
@shohelbuddyboss Approved @ankitguptaindia Can we test this in priority if we can. Merge PR into `dev` branch

**Review by dipskakadiya — DISMISSED** [review]
@shohelbuddyboss Approved

**Comment by ankitguptaindia** [comment]
@sumitbuddyboss 
Please start testing of this PR.

**Comment by sumitbuddyboss** [comment]
Hello @shohel 

I've checked in the dev branch and it's working as expected from my end for proof please check the below video.

**Video**
https://www.loom.com/share/ff653e6f4d78455f9aedf0d66b0d379c

@chetansatasiya Ready to release 🚀 

CC @ankitguptaindia

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
This PR needs to check for lot of places for relevant feeds and it does not do it. we need to discuss this first and then merge it.

**Review by mehulkaklotar — APPROVED** [review]
approved!

@ankitguptaindia please test this again.

**Comment by sumitbuddyboss** [comment]
> approved!
> 
> @sumitbuddyboss @ankitguptaindia please test this again.

Hello @shohel @mehulkaklotar 

Could you please merge this to the dev branch? 
https://www.loom.com/share/2ce0837b80874c5c9d7fe1bd90ea7655

CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
Hello @shohel @mehulkaklotar 

I've checked in the dev branch and the Show relevant Feed feature is working fine from my end. For the proof please check the below video.
https://www.loom.com/share/bf04715e1388446a9d239b72161e2845

Ready for release 🚀 

CC @ankitguptaindia

**Review by sourabhmatolia — APPROVED** [review]

**Review by sourabhmatolia — APPROVED** [review]

**Pull request merged**
