### PR TITLE
#1538 - Fixed the RTL issue with the code editor for the RTL languages

### LINKED ISSUE #1538: When Platform plugin is active on a Arabic site, Customize 'Additional CSS' section is not working.
**Describe the bug**
When Platform plugin is active on a Arabic site, Customize 'Additional CSS' section is not working. You can not add your CSS there. 

**To Reproduce**
1. Go to 'Settings > general' , set 'Arabic' as Site language. 
2. Go to Appearance > Customizer > Additional CSS.'
3. See error

**Screenshots**
Without Platform plugin https://prnt.sc/umx0lt
With Platform plugin https://prnt.sc/umx0w7

**Support ticket links**
https://secure.helpscout.net/conversation/1287717269/99774/

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1538.

### How to test the changes in this Pull Request:

1. Go to 'Settings > general' , set 'Arabic' as Site language.
2. Go to Appearance > Customizer > Additional CSS.'

### Proof Screenshots or Video
https://prnt.sc/ur3o8d
https://prnt.sc/ur3pev

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — COMMENTED** [review]
@amincdev Can you take a look into this please?

**Review by amincdev — DISMISSED** [review]

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@janakkaneriya007 Fix the conflict

**Comment by amincdev** [comment]
@chetansatasiya Conflicts Fixed

**Review by chetansatasiya — APPROVED** [review]
@amincdev Approved

**Comment by chetansatasiya** [comment]
@ankitguptaindia Ready for testing!

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

Please merge it to the dev branch.

CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
Hello @amincdev @janakkaneriya007 

**Issue:**
We can not access the "Theme Editor". Please check the below video.

**How to reproduce:**
1) Go to 'Settings > general', set 'Arabic' as Site language.
2) Go to Appearance > Theme Editor

**Video.**
https://www.loom.com/share/572b049bd70549d69126ae15603d4b01

cc @ankitguptaindia 

Thank you

**Comment by amincdev** [comment]
> Hello @amincdev @janakkaneriya007
> 
> **Issue:**
> We can not access the "Theme Editor". Please check the below video.
> 
> **How to reproduce:**
> 
> 1. Go to 'Settings > general', set 'Arabic' as Site language.
> 2. Go to Appearance > Theme Editor
> 
> **Video.**
> 
> https://www.loom.com/share/572b049bd70549d69126ae15603d4b01
> 
> cc @ankitguptaindia
> 
> Thank you

@sumitbuddyboss This issue is fixed now: https://prnt.sc/vvovyj

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Issue:
Number not seen proper in the editor. Please check the below video for more detail.
https://www.loom.com/share/5960f9e557194fceb7cd3996d4766e8c

cc @ankitguptaindia

**Comment by amincdev** [comment]
> Hello @amincdev
> 
> Issue:
> Number not seen proper in the editor. Please check the below video for more detail.
> 
> https://www.loom.com/share/5960f9e557194fceb7cd3996d4766e8c
> 
> cc @ankitguptaindia

@sumitbuddyboss 
This issue is fixed and merged in `dev` now: https://prnt.sc/vxa00b

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

All the issues have been fixed and it's working properly for me, For proof please check the below video.

Video:
https://www.loom.com/share/f78fdf9619614fc7b0d9651dd2c2a2a4

@chetansatasiya 
Ready to release  🚀 

cc @ankitguptaindia

**Review by sourabhmatolia — APPROVED** [review]

**Pull request merged**
