### PR TITLE
Fix - Video, Media & Document Issues

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1. Fix the Preview logic so now we are not using the .php file instead of we are using the WordPress Rewrite Rule.
2. Fix the Offload media CloudFront issue when remove files from server options.
3.  Added support to WP-Stateless – Google Cloud Storage plugin to server media, documents & videos.
4. Fix the video play issue via php code.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — APPROVED** [review]
@chetansatasiya  Please merged to dev and pass to QA.

**Review by KartikSuthar — APPROVED** [review]

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

Issue > https://github.com/buddyboss/buddyboss-platform/issues/2603 is not getting resolve through this PR. 
Tested on dev branch of the platform and theme. Issue still exist if user uploads MP3 file inside group. Symlink source for the group uploaded MP3 file redirects users to 404 page but if user uploads file through activity then symlink source doesn't get redirect to the 404 page. 
Video: https://www.loom.com/share/23238900bfa94eeca284543ee660bbbc

cc @sourabhmatolia @KartikSuthar

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED>
Tested the issue : https://github.com/buddyboss/buddyboss-platform/issues/2560 on https://platform-testing.flywheelsites.com/ with the dev branch of the platform. Now we are getting preview for the PDF files  if "REMOVE FILES FROM SERVER" setting is enabled.  
Video: https://www.loom.com/share/1350e74d2ba740e9acef87d3fd37780c

cc @sourabhmatolia @KartikSuthar

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED>
Tested this issue : https://github.com/buddyboss/buddyboss-platform/issues/2611 on client website : https://thefigapp.com/ .
Now, Photos are appearing on client website.
Video: https://www.loom.com/share/e065e7d258c942b1ae10332c32a1a0d7

cc @sourabhmatolia @KartikSuthar

**Comment by mohit-buddyboss** [comment]
> @chetansatasiya
> 
> Issue > #2603 is not getting resolve through this PR.
> Tested on dev branch of the platform and theme. Issue still exist if user uploads MP3 file inside group. Symlink source for the group uploaded MP3 file redirects users to 404 page but if user uploads file through activity then symlink source doesn't get redirect to the 404 page.
> Video: https://www.loom.com/share/23238900bfa94eeca284543ee660bbbc
> 
> cc @sourabhmatolia @KartikSuthar

FIXED>
Tested on the dev branch of the platform.
Now if we upload mp3 files in Group then it is playing. Also, tested for messages, comments, and forum replies and MP3 files are working fine.
Video: https://loom.com/share/477272164e704838b91d2a9b6eab65d4

cc @sourabhmatolia @KartikSuthar

**Comment by mohit-buddyboss** [comment]
@chetansatasiya 

FIXED >
Changes > Fix the Preview logic so now we are not using the .php file instead of we are using the WordPress Rewrite Rule.
Tested issue related to removal of preview.php. Tested on the local server as well as on https://platform-testing.flywheelsites.com/ using dev branch of the platform. 
Case 1: When symlinks are disabled then now preview.php URL's are not getting generate instead we are showing WP URL's. Example : https://platform-testing.flywheelsites.com/bb-document-preview/Zm9yYmlkZGVuXzI1Nzk=/Zm9yYmlkZGVuXzcx/bb-document-pdf-preview-activity-image/

Also, tested whole website via uploading all types of media and media preview is appearing fine and also Videos are playing as expected. 

Case 2: When symlinks are active. 
Tested whole website for breaking media previews and also uploaded new media. All media URL's gets convert into symlinks and previews are appearing fine. 

Video: https://loom.com/share/0d4d29b326f44e7bb9de45be1d9d339b
https://loom.com/share/3bb6d27269c241d7aa56f39b6594f1db

Related issues are resolve now and PR is ready for release.

cc @sourabhmatolia @KartikSuthar

**Comment by Performin** [comment]
Can confirm this is fixed on our site with 1.7.2.2

**Comment by chrisdubia** [comment]
This still does not work.  FFmpeg is only being used to provide a thumbnail preview of videos that are uploaded - it is not being used to transcode

**Pull request merged**
