### PR TITLE
Fix - video popup edit redirect

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — DISMISSED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @sadrul @amincdev

**Issue - 1**
The "More options" button design is not proper.

**How to reproduce:**
1. Open any video in popup
2. Hover on Menu icon dots
3. See error


**Screenshot:**
https://prnt.sc/1g2lfo2

Thank you

**Comment by amincdev** [comment]
> Hello @sadrul @amincdev
> 
> **Issue - 1**
> The "More options" button design is not proper.
> 
> **How to reproduce:**
> 
> 1. Open any video in popup
> 2. Hover on Menu icon dots
> 3. See error
> 
> **Screenshot:**
> https://prnt.sc/1g2lfo2
> 
> Thank you

@sumitbuddyboss Issue is fixed now.

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

**Issue - 2** 
If we edit video activity the first time then we can not edit a second time and the privacy button look weird for more detail please check the below issue video

Issue video:
https://www.loom.com/share/9932a1c483d5462fbac4998d9f46d346


Thank you

**Review by KartikSuthar — APPROVED** [review]

**Comment by sadrul** [comment]
@sumitbuddyboss the reported issue fixed, could you please test the edit for all - video, photos and media

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

**Fixed >**
Related issues are resolved now and now the edit button is working properly for me for proof please check the below video.

**Video:**
https://www.loom.com/share/8f9853b5d01c43cbb0478168447ea71d


Ready for release 🚀 
@chetansatasiya 

Thank you

**Pull request merged**
