### PR TITLE
.htaccess rules >> The htaccess access rules for bb files protection is no longer working on Apache 2.4

### LINKED ISSUE #2820: .htaccess rules >> The htaccess access rules for bb files protection is no longer working on Apache 2.4
**Describe the bug**
BB create some .htaccess on wp-content/uploads/bb_* . This .htaccess file contains an outdated apache directive: deny from all but the default in apache 2.4 must be Require all denied.

**To Reproduce**
1. Create a new site on Apache 2.2 with BB Platform
2. Configure/activate **Symbolic Links** and **Direct Access** from BuddyBoss > Settings > media
2. Update Apache from 2.2 to 2.4
3. Can see the **htaccess file contains an outdated apache directive: deny from all but the default in apache 2.4 must be Require all denied** in the apache error log.

**Expected behavior**
The htaccess rules must work with Apache 2.4.

**Support ticket links**
https://secure.helpscout.net/conversation/1596869757/157935?folderId=4312419

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2820

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@KartikSuthar LGTM 🚀

**Comment by KartikSuthar** [comment]
**Regarding restricting files under upload folders on openlitespeed server**

1. First of all make sure Auto Load from .htaccess is set to Yes under openlitespeed configuration as shown in the screenshot. http://prntscr.com/1qsu521
2. Restart openlitespeed service `sudo /usr/local/lsws/bin/lswsctrl restart` or from panel here: http://prntscr.com/1qsub64
3. Delete the previous .htaccess files from the server.
`../wp-content/uploads/bb_medias/.htaccess`
`../wp-content/uploads/bb_documents/.htaccess`
`../wp-content/uploads/bb_videos/.htaccess`
4. Refresh the WordPress admin and check the .htaccess files created again.
5. Restart openlitespeed service `sudo /usr/local/lsws/bin/lswsctrl restart` or from panel here: http://prntscr.com/1qsub64

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

As discussed and explained .htaccess file code is not getting auto update. It should get auto update. So, here we need changes so that code gets auto update.

cc @sourabhmatolia @firozwp @chetansatasiya

**Review by chetansatasiya — APPROVED** [review]

**Comment by KartikSuthar** [comment]
@mohit-buddyboss I have implemented auto-update while updating a platform.
when DB version of platform less then `17701` this. it will be updated automatically.

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Tested on qa-onging branch of the platform using apache version 2.4.53.

Now .htaccess file restrictions are working fine also it is automatically getting update.

Video: https://www.loom.com/share/28940bf9b37e4adc858ca1ecaaa81eef

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya @firozwp

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

Tested on qa-approved branch of the platform.
This PR related changes are working as expected.

@sourabhmatolia

**Pull request merged**
