### PR TITLE
Group Navigation changes after video tab added

### LINKED ISSUE #2581: Group Navigation changes after video tab added
### Scope
- We should have flag to identify whether the customer has re-order group navigation before or not
- The order should be same on Group Navigation and Front Side by default if customer did not update order before.
- On fresh setup of WP with platform plugin and theme the order of the menu item on Group Navigation and at Front side both are different. Please see screenshot https://tinyurl.com/yfz6h5wv 

**To Reproduce**
1. Go to Group Navigation
2. Check different menu items and check the same order on group page  
3. both these place has different order

**Expected behavior**
Order should be same by default for fresh setup

### Acceptance Criteria
Newly added video tab should show after photos default but if the customer re-ordered group tabs before and now we add video tab then we should add a tab in the last.

this changes found from the https://github.com/buddyboss/buddyboss-platform/pull/2570#issuecomment-874729168
issue and PR https://github.com/buddyboss/buddyboss-platform/issues/2568 and  https://github.com/buddyboss/buddyboss-platform/pull/2570

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Proof screenshot : https://www.awesomescreenshot.com/image/10652469?key=00d023fa715f80cde79672df006c9614

Fixes #2581 

### How to test the changes in this Pull Request:

1. Go to Group Navigation
2. Check different menu items and check the same order on group page  
3. both these place has different order

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@krunal-buddyboss LGTM merge in dev and put in testing.

**Review by chetansatasiya — APPROVED** [review]
LGTM 🚀 Merge in dev and put in testing.

**Comment by krunal-buddyboss** [comment]
Thank you @chetansatasiya , I have merged it to Dev.

@sumitbuddyboss @mohit-buddyboss please test this issue and let me know if any concern in it.

Thanks :)

**Comment by sumitbuddyboss** [comment]
Hello @krunal-buddyboss 

**Fixed>**
I've set up a fresh site in local and check the order before enabling video uploading module and check order after enable video uploading module now all the order is as expected for the proof please check the below videos.

**Video**
https://www.loom.com/share/29ecf2f2413f4003b9de186e401d3271
https://www.loom.com/share/d4b90d6fdbd64f798e2b8cde96adcdec


Ready for release 🚀 
@sourabhmatolia @chetansatasiya 

Thank you

**Pull request merged**
