### PR TITLE
Dropzone 5.7.2

### LINKED ISSUE #1180: Uploading photos on iPhone, the photo is rotated sideways.
**Describe the bug**
When adding photos on the iPhone using Chrome or Safari using the Add Photos button on the Photos profile tab, then clicking on the "Drop images here to upload", then clicking on the Take Photo, and taking a photo, the image displays sideways and not in the correct upright position.

**To Reproduce**
1. Go to 'profile > photos'
2. Click on 'Add Photos'
3. Click on 'Drop images here to upload' then Take Photo from camera. 

**Expected behavior**
Right orientation. 

**Screenshots**
[Attachments.zip](https://github.com/buddyboss/buddyboss-platform/files/4901953/Attachments.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1218485289/82244?folderId=3701249

### PR DESCRIPTION
**Pull request by mehulkaklotar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR updates Dropzone.js lib to 5.7.2 version.
https://github.com/enyo/dropzone/tree/master/dist

Fixes #1180 

### How to test the changes in this Pull Request:

Test all possible places of dropzone uploader

1. Activity Photo and Document uploader (News Feed(sitewide activity), User Timeline, Group Timeline)
2. User Profile Photo and Document uploader
3. Group Photo and Document uploader
4. Messages -> Create New Message and send reply form -> Photo and Document uploader
5. Forums -> Topic and reply form photo and document uploader
6. Group Messages -> Photo and Document uploader

### PR connected in theme
https://github.com/buddyboss/buddyboss-theme/pull/1026

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Dropzone.js - Lib updated to version 5.7.2

### CODE REVIEW

**Comment by mehulkaklotar** [comment]
@amincdev We need to check for template changes and design changes.

**Comment by mehulkaklotar** [comment]
Self note: Fix or refer this one here  https://github.com/buddyboss/buddyboss-platform/issues/836

**Review by chetansatasiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @amincdev @mehulkaklotar 
Please check the below issues.

**Issue: 1**
https://github.com/buddyboss/buddyboss-platform/issues/1180

This issue appears sometimes with some photos. Not every time with all photos. It showing little weird behavior every time.
when you upload and select photos from the phone media folder and select the size of given options then it rotate photos sometime left or sometimes right.

Refer below screenshot -

Looks fine when using these photos - https://i.imgur.com/Mh79qRc.jpg

It doesn't look fine with these photos - https://i.imgur.com/vt0TahJ.jpg


**Issue: 2**
https://github.com/buddyboss/buddyboss-platform/issues/1403

Tested this specific issue on iOS 13.7 Safari.

Some photos getting rotated after uploading from the Selfie folder.

https://i.imgur.com/GPgqDdR.jpg
https://i.imgur.com/6Pfc2jN.jpg

CC @ankitguptaindia

**Comment by ankitguptaindia** [comment]
@sumitbuddyboss Make sure when you test this PR, don't forget to check here as explained https://i.imgur.com/xOhFhhE.jpg

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

I've tested in my flywheel site and the design does not seem proper of dropzone in the mobile device.

**Device**:
iPhone 11 pro
iPhone 11
iPad pro

Issue Video.
https://www.loom.com/share/6a3a4b59c1da43c3b8230bbd36e5bb29

**Screenshot**
image

CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss 
Above issue is fixed now : https://prnt.sc/uqmp7e

Please take pull in theme branch -> fix/1024

**Comment by sumitbuddyboss** [comment]
> @sumitbuddyboss
> Above issue is fixed now : https://prnt.sc/uqmp7e
> 
> Please take pull in theme branch -> fix/1024

Hello @amincharoliya 

As we discussed, I've checked in browser stack but still, I'm not getting the change in mobile. The browser stack shows old CSS that why our change does not reflect there so we need to check in the real device.
https://www.loom.com/share/557d3dfe1f634426ba402ce355b8423a

Other than that in Desktop everything is working as expected, For the proof please check the below video.
https://www.screencast.com/t/7IaE8HEmT


CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
> Hello @amincdev @mehulkaklotar
> Please check the below issues.
> 
> **Issue: 1**
> #1180
> 
> This issue appears sometimes with some photos. Not every time with all photos. It showing little weird behavior every time.
> when you upload and select photos from the phone media folder and select the size of given options then it rotate photos sometime left or sometimes right.
> 
> Refer below screenshot -
> 
> Looks fine when using these photos - https://i.imgur.com/Mh79qRc.jpg
> 
> It doesn't look fine with these photos - https://i.imgur.com/vt0TahJ.jpg
> 
> **Issue: 2**
> #1403
> 
> Tested this specific issue on iOS 13.7 Safari.
> 
> Some photos getting rotated after uploading from the Selfie folder.
> 
> https://i.imgur.com/GPgqDdR.jpg
> https://i.imgur.com/6Pfc2jN.jpg
> 
> CC @ankitguptaindia

@amincharoliya @mehulkaklotar 
May I know the status of both the issues?

**Comment by amincdev** [comment]
@sumitbuddyboss Here is the screenshot from iPhone and it is showing fine.
https://prnt.sc/ur88v5

As we discussed that the changes were not reflecting. So, this must be the cache issue for you guys.

**Comment by chetansatasiya** [comment]
@amincdev @sumitbuddyboss Is there anything still pending in this PR?

**Comment by sumitbuddyboss** [comment]
> @sumitbuddyboss Here is the screenshot from iPhone and it is showing fine.
> https://prnt.sc/ur88v5
> 
> As we discussed that the changes were not reflecting. So, this must be the cache issue for you guys.

@amincdev  It's working looks good now. 
https://prnt.sc/uu6d4m

**Comment by sumitbuddyboss** [comment]
> > Hello @amincdev @mehulkaklotar
> > Please check the below issues.
> > **Issue: 1**
> > #1180
> > This issue appears sometimes with some photos. Not every time with all photos. It showing little weird behavior every time.
> > when you upload and select photos from the phone media folder and select the size of given options then it rotate photos sometime left or sometimes right.
> > Refer below screenshot -
> > Looks fine when using these photos - https://i.imgur.com/Mh79qRc.jpg
> > It doesn't look fine with these photos - https://i.imgur.com/vt0TahJ.jpg
> > **Issue: 2**
> > #1403
> > Tested this specific issue on iOS 13.7 Safari.
> > Some photos getting rotated after uploading from the Selfie folder.
> > https://i.imgur.com/GPgqDdR.jpg
> > https://i.imgur.com/6Pfc2jN.jpg
> > CC @ankitguptaindia
> 
> @amincharoliya @mehulkaklotar
> May I know the status of both the issues?

Hello @amincdev @mehulkaklotar 
The Below issue is not related to this PR so we consider it as separate. 
https://github.com/buddyboss/buddyboss-platform/issues/1180
https://github.com/buddyboss/buddyboss-platform/issues/1403

Other than that in Desktop and mobile everything is working as expected, For the proof please check the below video.
**Video:**
https://www.screencast.com/t/7IaE8HEmT
https://prnt.sc/ur88v5

@chetansatasiya 
The related issue is resolved now and PR is ready to merge.

**Review by sumitbuddyboss — APPROVED** [review]
@chetansatasiya 
The related issue is resolved now and PR is ready to merge.
Connected PR
https://github.com/buddyboss/buddyboss-theme/pull/1026

**Pull request merged**
