### PR TITLE
Fixed Media popup fluctuation issue while changing images

### LINKED ISSUE #1383: Inconsistency space around the images when opening in light box
**Describe the bug**
When open images in a lightbox that are posted in the activity feed, the black space around the images are not consistent.

**To Reproduce**
https://screencast-o-matic.com/watch/cYjbheGdwK

**Expected behavior**
Space should be consistent around the images.

**Support ticket links**
https://secure.helpscout.net/conversation/1250130153/87502

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1383 

### How to test the changes in this Pull Request:
https://screencast-o-matic.com/watch/cYjbheGdwK

### Proof
https://www.loom.com/share/4166eb40011e4664bcde90a814ff752f

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
Anyone who tests this PR Please watch the proof video before testing.

**Comment by ankitguptaindia** [comment]
@amincdev 

This fix creating new issue. Sidebar content couldn't load when viewing the image preview. Spinner always running continuously. If switch back to stable branch then looks fine https://i.imgur.com/2DFbPQI.jpg

**Screenshot/Video for Demonstration-** https://www.loom.com/share/71baf0d6022a45b9a810025db57bf994

**Comment by amincdev** [comment]
@ankitguptaindia 

> This fix creating new issue. Sidebar content don't load when viewing the image preview. Spinner always running continuously. If switch back to stable branch then looks fine https://i.imgur.com/2DFbPQI.jpg

Can you please test this now?

**Comment by ankitguptaindia** [comment]
@amincdev 

Issue has been fixed. 


**Proof-** https://www.loom.com/share/fc7d0acab2b44db588073192fbc56916

**Review by ankitguptaindia — APPROVED** [review]
**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [x] Tested negative test scenario

- [x] Updated Labels as per current status

**Final Update-** Ready to Merge. 🚀 

**Issue /  Title-**. Fixed Media popup fluctuation issue while changing images 

**Status-** Issue has been fixed.  
**Proof-** https://www.loom.com/share/fc7d0acab2b44db588073192fbc56916

**Review by chetansatasiya — APPROVED** [review]

**Pull request merged**
