### PR TITLE
#702 Fix visibility based on display name format

### LINKED ISSUE #702: Disallow Nickname visibility to be changed on frontend instead of First Name
**Describe the bug**
Nicknames can't be disabled on backend yet it can be set its visibility in frontend.
First Name can be disabled on backend but we can't change the visibility in frontend.

**To Reproduce**
1. Go to BuddyBoss > Settings > Profile
2. Allow Nickname, First Name and Last Name
3. Go to BuddyBoss > Profile Fields and set the visibility of First Name to public and allow members to override
4. In frontend, go to Profile > Edit. In this scenario, there is no option for First Name field to be hidden, but for Nickname there is an option. 

**Expected behavior**
This should be the other way around, Nicknames should not have the option to change the visibility in the frontend since it cannot be disabled on the backend and it is used for mentioning. First Names should have an editable visibility option

**Screenshots**
backend
front

**Support ticket links**
https://secure.helpscout.net/conversation/1122055167/65736?folderId=3701258

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #702 

https://github.com/buddyboss/buddyboss-theme/pull/986

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by eisenwasser** [comment]
@chetansatasiya 

Finding some issues
https://www.loom.com/share/68d76beea7d849f4a1b1b3ae088ff225

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Finding some issues
> https://www.loom.com/share/68d76beea7d849f4a1b1b3ae088ff225

@eisenwasser 

Issue 1 - Not able to edit visibility for the firstname - Fixed
Issue 2 - I think this is correct like as I said and scoped like when you select the first & last name as display format then you can't change the visibilty and it's always public. But still there is nothing connection between required and optional If I am not wrong then. Can you give your thoughts please?

**Comment by eisenwasser** [comment]
@chetansatasiya 

If the field is Optional then visibility should be customizable. If I do not have to enter any data at all, then why do I have to display data when I do enter it? Doesn't make sense. If the admin wants to let users customize visibility of Last Name they should be able to, I don't see any logical reason to prevent this since the user can already decide to leave the field blank.

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> If the field is Optional then visibility should be customizable. If I do not have to enter any data at all, then why do I have to display data when I do enter it? Doesn't make sense. If the admin wants to let users customize visibility of Last Name they should be able to, I don't see any logical reason to prevent this since the user can already decide to leave the field blank.

@eisenwasser I understand and I made the changes here so now the last name doesn't have any restriction.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @eisenwasser 

Bunch of issues found when performing below test scenarios - 

**_1. When Display Name Format set as NICKNAME and First Name and Last name are also allowed:_** 

And site admin changed the Visibility to ONLY ME and also selcted option enforce field visibility then First Name still appearing as Public to everyone even for logged out user as well.

2. Same issue heppening when using My Connection Privacy and checking profile from Non connected person

**_Refer for steps-_**
https://www.loom.com/share/ea889f6f647b4185a3f361563d2316a3

-----

3. **_When Display Name Format set as NICKNAME and First Name and Last Name are DISABLED then User is still searchable from Header Search via FirstName or Last Name._**
And as per logic, these fields will not appear anywhere in site so it should also not searchable on whole site.
(If you disable "First Name" and "Last Name" fields, they will not appear anywhere in the network. This allows your members to be fully anonymous (if they use a pseudonym for their nickname))

**_Refer for steps-_**

https://www.loom.com/share/9f7f4a7a78274e3fa04cbbab47dad0df

4. **_When Display Name Format set as NICKNAME:_** 

We are giving Requirement option to Last name Only. First Name doesn't have Requirement option.
First Name also should have Requirement option as whole system can work only using NickName so forcing to put First Name as mandatory in not good as per logic.
we are giving option to Disable Nick Name but Not making this optional.

**_Refer for steps-_**
https://www.loom.com/share/6b501bf3b5b34f53b75241cd5953608e

**_5.  When Display Name Format set as - FIRST NAME:_**
and Last Name is disabled but user can be searched via Last Name.
Although as per logic - (If you disable "Last Name" field, it will not appear anywhere in the network.)

**_6. When Display Name Format set as - First Name & Last Name:_**
As per label added on setting page - (All name fields are required with this format. Best used for professional networks.)
But Last Name can be set as Optional, we are not showing LastName as required.
As well as, with changing visibilty, user can Hide Last Name  and it won't show on User Profile and breking the rule of showing First & Last Name format.

**_Refer for steps-_**

https://www.loom.com/share/199e9bee6bc64061ba535a25fd8c457b

**Comment by chetansatasiya** [comment]
> **_1. When Display Name Format set as NICKNAME and First Name and Last name are also allowed:_**
> 
> And site admin changed the Visibility to ONLY ME and also selcted option enforce field visibility then First Name still appearing as Public to everyone even for logged out user as well.
> 
> 1. Same issue heppening when using My Connection Privacy and checking profile from Non connected person
> 
> **_Refer for steps-_**
> https://www.loom.com/share/ea889f6f647b4185a3f361563d2316a3

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> 4. **_When Display Name Format set as NICKNAME:_**
> 
> We are giving Requirement option to Last name Only. First Name doesn't have Requirement option.
> First Name also should have Requirement option as whole system can work only using NickName so forcing to put First Name as mandatory in not good as per logic.
> we are giving option to Disable Nick Name but Not making this optional.
> 
> **_Refer for steps-_**
> https://www.loom.com/share/6b501bf3b5b34f53b75241cd5953608e

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> **_6. When Display Name Format set as - First Name & Last Name:_**
> As per label added on setting page - (All name fields are required with this format. Best used for professional networks.)
> But Last Name can be set as Optional, we are not showing LastName as required.
> As well as, with changing visibilty, user can Hide Last Name and it won't show on User Profile and breking the rule of showing First & Last Name format.
> 
> **_Refer for steps-_**
> 
> https://www.loom.com/share/199e9bee6bc64061ba535a25fd8c457b

@ankitguptaindia This is intenional I think we can't say people to fill last name always. Some one need to hide their last name then it's fine but as per settings if some one have both filled then it will show both otherwise it will display only firstname.

**Comment by chetansatasiya** [comment]
> 3. **_When Display Name Format set as NICKNAME and First Name and Last Name are DISABLED then User is still searchable from Header Search via FirstName or Last Name._**
>    And as per logic, these fields will not appear anywhere in site so it should also not searchable on whole site.
>    (If you disable "First Name" and "Last Name" fields, they will not appear anywhere in the network. This allows your members to be fully anonymous (if they use a pseudonym for their nickname))
> 
> **_Refer for steps-_**
> 
> https://www.loom.com/share/9f7f4a7a78274e3fa04cbbab47dad0df



> **_5. When Display Name Format set as - FIRST NAME:_**
> and Last Name is disabled but user can be searched via Last Name.
> Although as per logic - (If you disable "Last Name" field, it will not appear anywhere in the network.)

@ankitguptaindia No: 3 & 5 issue I am creating the new issue and will manage in seprate Pr for this.

**Comment by chetansatasiya** [comment]
@ankitguptaindia All other issues has been fixed now 👍

**Comment by chetansatasiya** [comment]
@ankitguptaindia We need to test this

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia We need to test this

Started and pausing again due to Edit Activity Priority tasks.

**Comment by chetansatasiya** [comment]
> > @ankitguptaindia We need to test this
> 
> Started and pausing again due to Edit Activity Priority tasks.

@ankitguptaindia np but we need to keep in list for upcoming release.

**Review by mehulkaklotar — APPROVED** [review]
@dipskakadiya everything looks good here! 👍 

Can you make sure that we update the related templates in theme as well?

@ankitguptaindia can you test this and verify everything?

**Comment by ankitguptaindia** [comment]
@dipskakadiya Have you fixed this issue in this PR or is this still pending ?
https://github.com/buddyboss/buddyboss-platform/pull/1168#issuecomment-661721806

**Comment by dipskakadiya** [comment]
@ankitguptaindia Can you test that thing. I think it'll be fixed with my code.

**Comment by ankitguptaindia** [comment]
> > **_1. When Display Name Format set as NICKNAME and First Name and Last name are also allowed:_**
> > And site admin changed the Visibility to ONLY ME and also selcted option enforce field visibility then First Name still appearing as Public to everyone even for logged out user as well.
> > 
> > 1. Same issue heppening when using My Connection Privacy and checking profile from Non connected person
> > 
> > **_Refer for steps-_**
> > https://www.loom.com/share/ea889f6f647b4185a3f361563d2316a3
> 
> @ankitguptaindia This is fixed now 👍

These issues have been fixed.

**Comment by ankitguptaindia** [comment]
> > 1. **_When Display Name Format set as NICKNAME:_**
> > 
> > We are giving Requirement option to Last name Only. First Name doesn't have Requirement option.
> > First Name also should have Requirement option as whole system can work only using NickName so forcing to put First Name as mandatory in not good as per logic.
> > we are giving option to Disable Nick Name but Not making this optional.
> > **_Refer for steps-_**
> > https://www.loom.com/share/6b501bf3b5b34f53b75241cd5953608e
> 
> @ankitguptaindia This is fixed now 👍

This issue is fixed now

**Comment by ankitguptaindia** [comment]
> > 1. **_When Display Name Format set as NICKNAME and First Name and Last Name are DISABLED then User is still searchable from Header Search via FirstName or Last Name._**
> >    And as per logic, these fields will not appear anywhere in site so it should also not searchable on whole site.
> >    (If you disable "First Name" and "Last Name" fields, they will not appear anywhere in the network. This allows your members to be fully anonymous (if they use a pseudonym for their nickname))
> > 
> > **_Refer for steps-_**
> > https://www.loom.com/share/9f7f4a7a78274e3fa04cbbab47dad0df
> 
> > **_5. When Display Name Format set as - FIRST NAME:_**
> > and Last Name is disabled but user can be searched via Last Name.
> > Although as per logic - (If you disable "Last Name" field, it will not appear anywhere in the network.)
> 
> @ankitguptaindia No: 3 & 5 issue I am creating the new issue and will manage in seprate Pr for this.

These issues have been fixed.

**Comment by ankitguptaindia** [comment]
> > **_6. When Display Name Format set as - First Name & Last Name:_**
> > As per label added on setting page - (All name fields are required with this format. Best used for professional networks.)
> > But Last Name can be set as Optional, we are not showing LastName as required.
> > As well as, with changing visibilty, user can Hide Last Name and it won't show on User Profile and breking the rule of showing First & Last Name format.
> > **_Refer for steps-_**
> > https://www.loom.com/share/199e9bee6bc64061ba535a25fd8c457b
> 
> @ankitguptaindia This is intenional I think we can't say people to fill last name always. Some one need to hide their last name then it's fine but as per settings if some one have both filled then it will show both otherwise it will display only firstname.

@chetansatasiya 

In this way, What is difference between Options `First Name`& `First Name+Last Name`. 
As per your text - 
>Some one need to hide their last name then it's fine but as per settings if some one have both filled then it will show both otherwise it will display only firstname.

In this way, If site admin wants to give Last name optional then admin can choose First Name Option. As this Format has option to make Last name optional.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**When Display Name Format set as NICKNAME and First Name and Last Name are DISABLED-** 
What is use of Visibility setting in this case. As whole system based on Nickname Only.
Admin/user can make NickName visibility as ONLY ME and Nothing will appear on User's profile. It shows blank fields on user profiles. https://i.imgur.com/Qdluu9o.jpg 

https://www.loom.com/share/9ee039316da14daa9a02d05e670e5c4f

**Comment by chetansatasiya** [comment]
> > > **_6. When Display Name Format set as - First Name & Last Name:_**
> > > As per label added on setting page - (All name fields are required with this format. Best used for professional networks.)
> > > But Last Name can be set as Optional, we are not showing LastName as required.
> > > As well as, with changing visibilty, user can Hide Last Name and it won't show on User Profile and breking the rule of showing First & Last Name format.
> > > **_Refer for steps-_**
> > > https://www.loom.com/share/199e9bee6bc64061ba535a25fd8c457b
> > 
> > 
> > @ankitguptaindia This is intenional I think we can't say people to fill last name always. Some one need to hide their last name then it's fine but as per settings if some one have both filled then it will show both otherwise it will display only firstname.
> 
> @chetansatasiya
> 
> In this way, What is difference between Formats `First Name`& `First Name+Last Name`.
> As per your text -
> 
> > Some one need to hide their last name then it's fine but as per settings if some one have both filled then it will show both otherwise it will display only firstname.
> 
> In this way, If site admin wants to give Last name optional then admin can choose First Name Option. As this Format has option to make Last name optional.

@sourabhmatolia & @eisenwasser Need your thoughts

**Comment by ankitguptaindia** [comment]
@dipskakadiya 
Now-
**WHEN Display Name Format Set as  First Name ONLY.- **
then Last Name field is appearing on User's profiles page although disabled from settings. And also not appearing in Profiles fields admin setting page

https://i.imgur.com/jdTnUSz.jpg
https://i.imgur.com/wWjz2AN.jpg
https://i.imgur.com/LuxdlIn.jpg

**Comment by ankitguptaindia** [comment]
@chetansatasiya @dipskakadiya @sourabhmatolia 
All known issues have been fixed. 👍 

I tested according to the logic discussed on call. Woking fine.

Created short video for fixes and new logic implementation. Please check and let me know if I tested a per logic we decided.
https://www.loom.com/share/80842455a2ff40f5807bd2ca9987e5ac

**Review by ankitguptaindia — APPROVED** [review]
**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [x] Tested negative test scenario

- [x] Updated Labels as per current status

**Final Update-** Ready to Merge 🚀

**Pull request merged**
