### PR TITLE
Fix deprecated warning for block category filter

### LINKED ISSUE #3037: Warning: Block Category is deprecated
**Describe the bug**
`block_categories` filter is deprecated in the WP 5.8.0 version. 

**To Reproduce**
1. Go to 'WP Pages'
2. See deprecated block warning.

**Environment**
WP 5.8

**Support ticket links**
https://secure.helpscout.net/conversation/1648588407/166886/

### LINKED ISSUE #3168: Fix the use of `block_categories` based on the WP versions
**Describe the bug**
`block_categories` function is deprecated from WP 5.8.0.

**To Reproduce**
1. Go to WordPress post/page editor
2. Edit the post/page
3. Check the debug log.
4. PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in C:\MAMP\htdocs\platform\wp-includes\functions.PHP on line 5586

**Expected behavior**
It should be working with the old version as well as the new one without notice.

### PR DESCRIPTION
**Pull request by kishanjasani**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3037 
Fixes #3168

### How to test the changes in this Pull Request:

1. Go to WP Pages.
2. See warning is gone.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@kishanjasani  LGTM 🚀

**Review by KartikSuthar — APPROVED** [review]

**Comment by basil-buddyboss** [comment]
Retested in the QA ongoing branch.
Status: Fixed

Proof Screenshots or Video:
https://watch.screencastify.com/v/PLTcGHGF4b2MblyW5yNF

**Comment by dipskakadiya** [comment]
@basil-buddyboss If testing done and it's ready for release then please Add appropriate label to ticket and remove needs testing lable.

**Review by dipskakadiya — APPROVED** [review]

**Comment by JetalDobariya** [comment]
Hello @kishanjasani 

I did verify this PR and related issue in qa-approved branch, but still i getting same error "PHP Deprecated...." when i open WP page or Post.
See in the Proofs Video : https://loom.com/share/9f17763cb2c74e629564909df841b62a

NOTE : I checked related issue with @basil-buddyboss and @sumitbuddyboss's system but facing same issue in Basil's system but From sumit side error is not coming.

Please check and let me know if anythings are missed.

Thanks!
CC : @basil-buddyboss @sumitbuddyboss @sourabhmatolia

**Comment by JetalDobariya** [comment]
Hello @kishanjasani 

I did verify this PR in qa-approved branch, now related issue is resolved already in theme.
Error was occures because Buddyboss App is Active that's why but in theme issue is already resolved, PHP Deprecated error is not appear when i edit Post/Page.
--> https://prnt.sc/21y9yv7

Thanks @KartikSuthar for your help.

CC : @sourabhmatolia @sumitbuddyboss

**Pull request merged**
