### PR TITLE
Fixed-Disappearing comments after editing posts and custom post types

### LINKED ISSUE #1839: Disappearing comments after editing posts and custom post types
**Describe the bug**
Comments get the removed/blank content in single blogs after editing the post. This actually happens when Post Type Comments is enabled in BuddyBoss > Settings > Activity > Posts in Activity Feeds > and enable Post Type Comments.

**To Reproduce**
issue can be reproduced on the demo
1. Create a single blog post
2. Enable comments on blog post
3. Go to frontend and comment on the post and click publish
4. Enable Post Type Comments in BuddyBoss > Settings > Activity > Posts in Activity Feeds
5. Go back to the post and post another comment
6. Edit the post and click save
7. Go to frontend of post and refresh page
8. See your comments get blank contents

**Expected behavior**
All comments should stay and not be blank

**Screenshots**
https://drive.google.com/file/d/10baQhDSvKPyDdr9BRCwMq_vPD4otRZxg/view
https://drive.google.com/file/d/13gZufaEpF6e1HYc1nGM_KrdRnborBAwc/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1345548625/110215
https://secure.helpscout.net/conversation/1361670423/113872
https://secure.helpscout.net/conversation/1371811207/115628
https://secure.helpscout.net/conversation/1383864062/117641
https://secure.helpscout.net/conversation/1385071997/117927
https://secure.helpscout.net/conversation/1375017455/116124
https://secure.helpscout.net/conversation/1405049792/121599

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1839.

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crVfbJPQ10

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> $resave_activity->content = '';
    The above code was issuing. Every time this was removing content when the post updated.
> $commentdata->user_id
    $commentdata was returning with the array. So it was displaying an error in ajax when you try to post a comment.

### CODE REVIEW

**Review by chetansatasiya — COMMENTED** [review]
Looks good to me.

**Comment by chetansatasiya** [comment]
@mehulkaklotar Need your review here before approved and merged.

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
@jitendrabanjara1991 can you fix phpcs issues in your changes?

**Comment by jitendrabanjara1991** [comment]
@mehulkaklotar 
I have formatted the code and run phpcs in my changes. So, Please check it and let me know if anything else.
Thanks

**Review by mehulkaklotar — APPROVED** [review]
Looks good to me.

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

Fixed > 
Tested on the Dev branch, Related issue is resolved for the proof please check the below video.

Video:
https://www.loom.com/share/9812724fd46644ada968c195ceb20c57


@chetansatasiya @mehulkaklotar 
The related issue is resolved now and PR is ready to merge. 🚀

**Pull request merged**
