### PR TITLE
Fixed While uploading Profile photo or cover photo, it should update instantly on page

### LINKED ISSUE #1655: While uploading Profile photo or cover photo, it should update instantly on page.
**Is your feature request related to a problem? Please describe.**
While uploading Profile photo or cover photo, It is not updating instantly wherever it is shown on page.

**Describe the solution you'd like**
When user uploads a profile photo or cover photo it should update instantly update wherever it is shown on the page.

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1655 

### How to test the changes in this Pull Request:

1. Go to Profile page and update profile image
2. It should update profile image everywhere seen on page
3. Go to Group page and update cover photo
4. It should update cover photo  everywhere seen on page

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by dipskakadiya — DISMISSED** [review]
@amincdev Approved. @ankitguptaindia Ready for testing. PR merged in dev

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

**Issue 1** 
In the group page cover photo, it can't update instantly. Please check the below video.
https://www.loom.com/share/65460656e15e41658120a8ae0b7b8094

**Issue 2**
When we refresh the page at that time dropzone design not look proper. Please check the below video.
https://www.loom.com/share/6a928a81afc3444b91853fe1fd617c36


**Query:**
If we delete the profile photo and cover photo it'll not update instantly. So, Do we need to update instantly while deleting? 
https://www.loom.com/share/0f57889f968240ccbdf98dc9c3b467d4


CC @ankitguptaindia

**Comment by amincdev** [comment]
@sumitbuddyboss 

> Issue 1
> In the group page cover photo, it can't update instantly. Please check the below video.

Fixed

> Issue 2
> When we refresh the page at that time dropzone design not look proper. Please check the below video.

This is not related to this issue. You can create a separate issue where I will check this.

> Query:
> If we delete the profile photo and cover photo it'll not update instantly. So, Do we need to update instantly while deleting?

The group cover photo will be removed now instantly when deleted.

@chetansatasiya @dipskakadiya  When the profile photo gets removed what image to show as the default profile photo? Can you please help here?

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Issue >

**Issue 1**
**Profile photo**
It will take a little bit of time to reflect on the profile photo when we upload it.

**Issue 2**
**Profile photo**
When we delete the profile photo it will not update instantly. 

I have covered both issues below the video so please check this video.
https://www.loom.com/share/aff70545d60345f6aca9c38ee61d0744

Thank you

**Comment by amincdev** [comment]
> Hello @amincdev
> 
> Issue >
> 
> **Issue 1**
> **Profile photo**
> It will take a little bit of time to reflect on the profile photo when we upload it.
> 
> **Issue 2**
> **Profile photo**
> When we delete the profile photo it will not update instantly.
> 
> I have covered both issues below the video so please check this video.
> 
> https://www.loom.com/share/aff70545d60345f6aca9c38ee61d0744
> 
> Thank you

Issue 1
This depends on your local server speed. It is taking less than a second for me to upload a new photo.

Issue 2 
Fixed now

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed>
Now delete profile photo update instantly. for the proof please check the below video.

Video
https://www.loom.com/share/5e90ad70bce14cf08ef9600cd3ed167e

Ready for release 🚀 

Thank you

**Pull request merged**
