### PR TITLE
fixed Change Password > front end change password function is not wor…

### LINKED ISSUE #2767: Change Password > front end change password function is not working
**Describe the bug**
When we trying to change the password from the frontend (Account > Login Information) it's not working.

**To Reproduce**

1. Go to Account > Login Information
2. Add **current password**, **Add Your New Password**, and **Repeat Your New Password**
3. It gets redirected to the login page after clicking on the **Save Changes** button.
4. Will enter credentials with the new password but it will not work

**Expected behavior**
The new password should work after being changed from the account page.

**Screenshots**
https://vimeo.com/585756350/fee6fd5457

**Environment**
1) The customer site: https://udzbeniknaklik.com/staging-site-test-/
2) Replicated on local setup

**Support ticket links**
https://secure.helpscout.net/conversation/1578908679/154861?folderId=3709082
https://secure.helpscout.net/conversation/1591310685/156969/
https://secure.helpscout.net/conversation/1596039840/157788?folderId=3701248
https://secure.helpscout.net/conversation/1595728332/157724?folderId=3701248

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2767 .

### How to test the changes in this Pull Request:

1. Go to Account > Login Information
2. Add **current password**, **Add Your New Password**, and **Repeat Your New Password**
3. It gets redirected to the login page after clicking on the **Save Changes** button.
4. Will enter credentials with the new password but it will work

### Proof Screenshots or Video

https://vimeo.com/585768453/bcd76993ca

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Issue>
After this release If any user updates the plugin then also getting issue in login because in the database there will be an old entry
so the user can't log in, please check the below video.

Video:
https://www.loom.com/share/4a5cf5738fdc47eebc6f1e56674fef96

Thank you

**Comment by milanhirapra** [comment]
@sumitbuddyboss 

The password was saved as plain text when changing the password, so all users would need to **forget password** first.

CC: @chetansatasiya

**Comment by sumitbuddyboss** [comment]
Hello @milanhirapra 

Fixed >
A related issue is resolved now password change functionality is working properly, for the proof please check the below video.

Video:
https://www.loom.com/share/b95a773e3a754ce08136a5f31050dc38

Ready for release 🚀 

Thank you.

**Comment by JetalDobariya** [comment]
Hello,

I have tested this PR in QA Approved branch and changes has been done and working fine.
Here, I attached video for reference.
https://www.loom.com/share/3a0032ed6d6d4a4aa69ce89dcd22930f

Thanks!
CC : @sumitbuddyboss

**Review by dipskakadiya — COMMENTED** [review]
@milanhirapra Approved. Ready for testing

**Pull request merged**
