### PR TITLE
[CRITICAL] Absence of ADMIN and MODERATOR users in the group users management page!

### LINKED ISSUE #2470: [CRITICAL] Absence of ADMIN and MODERATOR users in the group users management page!
**Describe the bug**
When we set PROFILE TYPE for a user and enable the **"Hide all members of this type from Members Directory"** option for that **PROFILE TYPE**, if user's role in group is **MODERATOR** or **ADMIN**, user will be removed from the MANAGE MEMBERS page of the groups he is a member of.

**Expected behavior**
users are still on the group members management page when this option is enabled

**Screenshots**
1) when **"Hide all members of this type from Members Directory"** option is **disable** for profile type of **"Maverick"**:
Capture

2) when **"Hide all members of this type from Members Directory"** option is **enable** for profile type of **"Maverick"**:
Capture2

3) result:
Capture3

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2470 .

### How to test the changes in this Pull Request:

1. Create a new group and add Admins, Moderators to this group
2. Create a new profile type and enable this option **Hide all members of this type from Members Directory**
3. Assign this profile type to the Group Admins and Moderators
4. Go to the website and open this Group > Manage > Members and can see all members

### Proof Screenshots or Video
https://vimeo.com/592688065/ca78f535ef

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### BuddyBoss API PR
https://github.com/buddyboss/buddyboss-platform-api/pull/339

### CODE REVIEW

**Review by dipskakadiya — DISMISSED** [review]
@milanhirapra Approved. Ready for testing.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
We have to rework this and here is the scope of settings.

When “**Hide all members from the Members Directory**” is selected, hide members from:

- [x] Members Page (Component Page)
- [x] Widget > Members
- [x] Widget > Recently Active Members

DON’T hide from:

- [ ] Profile > Connections
- [ ] Groups > Members
- [ ] Groups > Manage > Members
- [ ] Widget > Members I’m Following
- [ ] Widget > Members Following Me
- [ ] Widget > My Connections

Create a new setting.

- [ ] Hide members with this profile type from Network Search results
         Hide in search if selected

**Comment by janakkaneriya007** [comment]
### Final Proof:
https://www.loom.com/share/7952d8f49f4d4c7f97ec5ae3d58579e2

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Tested on qa-ongoing branch of the platform.

Issue is resolve now and functionality is working same as scope mentioned here : https://github.com/buddyboss/buddyboss-platform/pull/2840#pullrequestreview-760658394

Video: https://loom.com/share/926ad69895f54bd4babbdc3d4ac6478d

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @firozwp @KartikSuthar @chetansatasiya

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007

Tested on qa-approved branch of the platform.
PR is working as expected on this branch.
PR is ready for Production.

cc @sourabhmatolia @KartikSuthar @chetansatasiya @firozwp

**Pull request merged**
