### PR TITLE
#1900 fixed Member loading on scroll issue

### LINKED ISSUE #1900: The group members list is not completely showing when sending a group message - WP 5.6 issue
**Describe the bug**
After updating to WordPress 5.6, the group members list is no longer showing the complete list.

**To Reproduce**
1. Install WordPress 5.6
2. Go to a group with more than 10 members
3. Navigate to the Send Messages tab
4. Notice the error

**Screenshots**
groups

**Support ticket links**
https://secure.helpscout.net/conversation/1365808115/114581/

### PR DESCRIPTION
**Pull request by dkvasani**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1900.

### How to test the changes in this Pull Request:

1. Install WordPress 5.6
2. Go to a group with more than 10 members
3. Navigate to the Send Messages tab

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/cYlFhK8yLC

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by mehulkaklotar — APPROVED** [review]
@dkvasani This looks good to me. please merge it to `dev`

**Comment by sumitbuddyboss** [comment]
Hello @dkvasani @mehulkaklotar 

Please merge it to the dev branch.

cc @ankitguptaindia @sourabhmatolia

**Comment by mehulkaklotar** [comment]
@sumitbuddyboss done merged.

**Comment by sumitbuddyboss** [comment]
Hello @dkvasani 

The issues have been fixed and it's working properly for me, For proof please check the below video.
https://www.loom.com/share/727e50ff43b4481782573013a9702486

@chetansatasiya 
Ready to release 🚀 

cc @ankitguptaindia @sourabhmatolia

**Pull request merged**
