### PR TITLE
#1755 - Fix  Group Messages Media display in group photos

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@mehulkaklotar This is ready for you to review.

@sourabhmatolia As discussed on the scrum added the plugin update to background upgrade the data to fix the issue without tool.

**Review by mehulkaklotar — APPROVED** [review]
approved!

@ankitguptaindia need testing here.

**Comment by sumitbuddyboss** [comment]
Hello @mehulkaklotar 

Could you please merge this to the dev branch?

Thank you

CC @ankitguptaindia

**Comment by sumitbuddyboss** [comment]
Hello @chetansatasiya 

Fixed > The issue is resolved now, I've checked in the dev branch and it's working as expected. For the proof please check the below video.

Video:
https://www.loom.com/share/f696c2d9dda14396820f8d4ab8a70af0

Ready to release 🚀 

CC @ankitguptaindia

**Review by mehulkaklotar — APPROVED** [review]

**Pull request merged**
