### PR TITLE
Group Messages

### LINKED ISSUE #357: Group Messages
**Is your feature request related to a problem? Please describe.**
Group organizers are unable to easily message all of their group members.

**Describe the solution you'd like**
Attached wireframe is shown in the video, but updated a bit to be simpler.

Video Explanation:
https://www.loom.com/share/acbdbf5aece042e3b68224665faa8ca5

[Group-Messages-v2.pdf](https://github.com/buddyboss/buddyboss-platform/files/3966101/Group-Messages-v2.pdf)

### PR DESCRIPTION
**Pull request by chetansatasiya**
This PR will fix #357

https://github.com/buddyboss/buddyboss-theme/pull/159

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-** User having delete message icon to delete own message. Although not having any message to delete.

See for detailed Info : https://www.loom.com/share/0697ec3a56744e1ebf774bfdba1d7f84

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

*Issue-** Inline styling not getting applied  Properly to message received by another user.

https://www.loom.com/share/78f9241a027b45c390cd6a2405398d00

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> _Issue-_* Inline styling not getting applied Properly to message received by another user.
> 
> 
> https://www.loom.com/share/78f9241a027b45c390cd6a2405398d00

@sagarjadhav Can you look into this please?

**Comment by eisenwasser** [comment]
@chetansatasiya Another issue I can see from Ankit's video:
Extra space after each name in inbox title - https://prnt.sc/rb7ont

**Comment by eisenwasser** [comment]
@chetansatasiya The other issues Ankit reported are real.

The two about styling needs to be worked on by @sagarjadhav

**Comment by chetansatasiya** [comment]
> @chetansatasiya Another issue I can see from Ankit's video:
> Extra space after each name in inbox title - https://prnt.sc/rb7ont

@eisenwasser this is fixed now

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-** User having delete message icon to delete own message. Although not having any message to delete.
> 
> See for detailed Info :
> 
> https://www.loom.com/share/0697ec3a56744e1ebf774bfdba1d7f84

@ankitguptaindia @eisenwasser This is fixed now and now delete button will show if user participated on that thread.

**Comment by sagarjadhav** [comment]
@ankitguptaindia Fixed that issue in [theme](https://github.com/buddyboss/buddyboss-theme/pull/159)

**Comment by ankitguptaindia** [comment]
@sagarjadhav @chetansatasiya 

**Issue-** Inconsistency in same design on two different places of theme.

https://www.loom.com/share/ca0ee70ae55548fe9a42eeaa35190231

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Some error/Notice when viewing any other member Profile.
https://i.imgur.com/OBXFqmb.jpg
https://i.imgur.com/eCLj80U.jpg

**Comment by chetansatasiya** [comment]
> @sagarjadhav @chetansatasiya
> 
> **Issue-** Inconsistency in same design on two different places of theme.
> 
> 
> https://www.loom.com/share/ca0ee70ae55548fe9a42eeaa35190231

@sagarjadhav I added the link now we have to make some CSS to look nicer.

**Comment by chetansatasiya** [comment]
> > @sagarjadhav @chetansatasiya
> > **Issue-** Inconsistency in same design on two different places of theme.
> > https://www.loom.com/share/ca0ee70ae55548fe9a42eeaa35190231
> 
> @sagarjadhav I added the link now we have to make some CSS to look nicer.

@amincdev Can you work on this change as @sagarjadhav busy on other tasks so.

**Comment by amincdev** [comment]
> > > @sagarjadhav @chetansatasiya
> > > **Issue-** Inconsistency in same design on two different places of theme.
> > > https://www.loom.com/share/ca0ee70ae55548fe9a42eeaa35190231
> > 
> > 
> > @sagarjadhav I added the link now we have to make some CSS to look nicer.
> 
> @amincdev Can you work on this change as @sagarjadhav busy on other tasks so?

Sure @chetansatasiya , Looking into this.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-**  
Negative Test Case - when accessing any other user message tab and both user having same mesage thread ID. then message sidebar showing some weird data. 

https://i.imgur.com/4pJEgS2.jpg
https://i.imgur.com/dUNTy5t.jpg

More Details-https://www.loom.com/share/c26f4f13e0a94cbd8931e9f193341f9d

**Comment by amincdev** [comment]
> @sagarjadhav @chetansatasiya
> 
> **Issue-** Inconsistency in same design on two different places of theme.
> 
> 
> https://www.loom.com/share/ca0ee70ae55548fe9a42eeaa35190231

@ankitguptaindia This issue is fixed now.

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-**
> Negative Test Case - when accessing any other user message tab and both user having same mesage thread ID. then message sidebar showing some weird data.
> 
> https://i.imgur.com/4pJEgS2.jpg
> https://i.imgur.com/dUNTy5t.jpg
> 
> More Details-
> 
> https://www.loom.com/share/c26f4f13e0a94cbd8931e9f193341f9d

@ankitguptaindia this is fixed now 👍

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> If message having Gif as an attachment and Sender of message want to delete his/her message then other content getting deleted but Gif still appears in the thread. (On the other hand, if message has Image and user deleting message then Image getting deleted )
> 
> 
> https://www.loom.com/share/75cb365e986046029fbe62907b8c1e3b

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-** Can select members twice if using the Search feature.

**How to Reproduce-**  Select All check box to select member and then search any user, you can select member although you already have that member.

See-  https://www.loom.com/share/1bb3c694e83f403d8fa854b94e84a17e

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

EMAIL Notifcation should have reference of Group if Message is coming from GROUP Message feature.

It sounds like user received personal message instead of Group Message https://prnt.sc/rcepkd

https://www.loom.com/share/a927ef5157e14604a93a4c2b9b6b24b5

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-** Can select members twice if using the Search feature.
> 
> **How to Reproduce-** Select All check box to select member and then search any user, you can select member although you already have that member.
> 
> See-
> 
> https://www.loom.com/share/1bb3c694e83f403d8fa854b94e84a17e

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-** When every member of Group have left the group then Private Reply BCC conversation showing blank in thread. Some user has info like `ABC left the Group` but some user not. 

https://prnt.sc/rcfbuz

https://www.loom.com/share/f4f036c21a3f4a9384631788eb59d940

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-** If any Group has MORE THAN 1 Organizer. 
And Second co-organizer sending Group Message then that message is not appearing in his Message Listing page.
Albeit message is getting received by other users of  group.  

https://www.loom.com/share/16c73ebf0e0d4f2eaa1e797770ce60df

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Security Issue_**  BANNED user can Receive and Send Reply to Group Message. Albeit That user is not listing in member's archive page. https://prnt.sc/rcgi9t 




Explanation-  https://www.loom.com/share/7d5bc315198349cab4c46f0e5914cc55

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-** If any Group has MORE THAN 1 Organizer.
> And Second co-organizer sending Group Message then that message is not appearing in his Message Listing page.
> Albeit message is getting received by other users of group.
> 
> 
> https://www.loom.com/share/16c73ebf0e0d4f2eaa1e797770ce60df

This is fixed now 👍

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-** When every member of Group have left the group then Private Reply BCC conversation showing blank in thread. Some user has info like `ABC left the Group` but some user not.
> 
> https://prnt.sc/rcfbuz
> 
> 
> https://www.loom.com/share/f4f036c21a3f4a9384631788eb59d940

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Group Organizer is not able to send message in group if group has only 1 user with same group organizer access.

See - https://www.loom.com/share/f69d5e48637a407882b482f12900e83e

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Security Issue_** BANNED user can Receive and Send Reply to Group Message. Albeit That user is not listing in member's archive page. https://prnt.sc/rcgi9t
> 
> Explanation-
> 
> https://www.loom.com/share/7d5bc315198349cab4c46f0e5914cc55

@ankitguptaindia  This is fixed now 👍 Banned user will not access the group thread until unbanned.

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> EMAIL Notifcation should have reference of Group if Message is coming from GROUP Message feature.
> 
> It sounds like user received personal message instead of Group Message https://prnt.sc/rcepkd
> 
> 
> https://www.loom.com/share/a927ef5157e14604a93a4c2b9b6b24b5

@ankitguptaindia @eisenwasser This is fixed now 👍 Now an email will look like https://prnt.sc/rckf7q

**Comment by ankitguptaindia** [comment]
@sagarjadhav @chetansatasiya 


Newly added info icon and Gif Preview needs styling in mobile layout.

https://www.loom.com/share/f509611891174ae9a30f42c51db9a968

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Group Organizer is not able to send message in group if group has only 1 user with same group organizer access.
> 
> See -
> 
> https://www.loom.com/share/f69d5e48637a407882b482f12900e83e

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> https://www.loom.com/share/f509611891174ae9a30f42c51db9a968

@amincdev I need your help here to fix the UI Issues.

**Comment by amincdev** [comment]
@eisenwasser For this issue in mobile device, I need your confirmation to add the fix.
**Issue** - https://prnt.sc/rdlkvu
**Solution** - https://prnt.sc/rdll1d

**Comment by ankitguptaindia** [comment]
> @eisenwasser For this issue in mobile device, I need your confirmation to add the fix.
> **Issue** - https://prnt.sc/rdlkvu
> **Solution** - https://prnt.sc/rdll1d

@amincdev We can do as you suggested in the screenshot.  we can change later if Mike will suggest anything new.

**Comment by amincdev** [comment]
> @amincdev We can do as you suggested in the screenshot. we can change later if Mike will suggest anything new.

@ankitguptaindia Sure, making this change.

**Comment by amincdev** [comment]
@ankitguptaindia I have fixed the issue.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

**Issue-** 

1. Wrong text in Notification description. 
https://www.loom.com/share/22045528f02949da885b80604ed9ad15

---
2. Self Notification should not go to member who sent the message.
https://www.loom.com/share/3e526c6e7da945e2854742968944eb34

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> **Issue-**
> 
> 1. Wrong text in Notification description.
>    https://www.loom.com/share/22045528f02949da885b80604ed9ad15
> 
> 1. Self Notification should not go to member who sent the message.
>    https://www.loom.com/share/3e526c6e7da945e2854742968944eb34

@ankitguptaindia for `Wrong text in Notification description` this is fixed now it looks like this https://prntscr.com/rj2ckd and for the `Self Notification should not go to member who sent the message.` I don't think there is any issue. We are showing last `10` messages there.

**Comment by ankitguptaindia** [comment]
Status of Cross-checking All above issues after re-fixes:

>Negative Test- when Emoji is disabled in Groups then unable to select members for sending individuals message.
https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-561614809 - 

Working fine


https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-561627751
>Issue- Blank notifications appearing in the Notification icon of header and Message Spinner loading continuously and older message are not appearing in member's Inbox

Looks Fine 



>Cross icons not showing same behavior for All members & Individual members.

>If sending Individual message to group member then it shows, Sent this message to all members of this group with success message.

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-561644145


Tested, Looks fine




>Search box not appearing to Groups members (Recipient )

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-561672621


Tested, Looks fine


-----

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-562009665


>Use Case- When admin sending message to Other members (Group Moderator)with optioned Private Reply BCC selected then some members not receiving message.

>Also message not received by any member of group if Private Reply BCC & Using Select ALL option



>any group have 3 types of members like a member, Organizer, moderator.
In this case, if Moderator sending a message then Organizer is not receiving any message although normal member received



Tested, Looks fine




---



https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-563134449

>I Just found new another issue- If any Group having apostrophe S then some text appearing in Message page.

>For eg. Foodie’s Group looks like Foodie&#8217;s Group https://prnt.sc/q86wnd

Tested, Looks fine

------

**Comment by ankitguptaindia** [comment]
@chetansatasiya. 

Regression- 

> > **Security Issue_** BANNED user can Receive and Send Reply to Group Message. Albeit That user is not listing in member's archive page. https://prnt.sc/rcgi9t
> > Explanation-
> > https://www.loom.com/share/7d5bc315198349cab4c46f0e5914cc55
> 
> @ankitguptaindia This is fixed now 👍 Banned user will not access the group thread until unbanned.

This is again back as issue. Banned member getting group message notification/

https://www.loom.com/share/100779b4f0d841ae8d2c60fd743af8a6

**Comment by chetansatasiya** [comment]
> @chetansatasiya.
> 
> Regression-
> 
> > > **Security Issue_** BANNED user can Receive and Send Reply to Group Message. Albeit That user is not listing in member's archive page. https://prnt.sc/rcgi9t
> > > Explanation-
> > > https://www.loom.com/share/7d5bc315198349cab4c46f0e5914cc55
> > 
> > 
> > @ankitguptaindia This is fixed now 👍 Banned user will not access the group thread until unbanned.
> 
> This is again back as issue. Banned member getting group message notification/
> 
> 
> https://www.loom.com/share/100779b4f0d841ae8d2c60fd743af8a6

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-567766820

>Sending a message, confirmation is all messed up currently.

Working Fine.

---

> **Issue-** When every member of Group have left the group then Private Reply BCC conversation showing blank in thread. Some user has info like `ABC left the Group` but some user not.

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-595669196

Working fine.

---

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-595657064

>Issue- Can select members twice if using the Search feature.

Working Fine.

---
https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-594588894
>f message having Gif as an attachment and Sender of message want to delete his/her message then other content getting deleted but Gif still appears in the thread. (On the other hand, if message has Image and user deleting message then Image getting deleted )


working fine.

----

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-594538270
>Issue-
Negative Test Case - when accessing any other user message tab and both user having same mesage thread ID. then message sidebar showing some weird data

Wroking Fine..

---

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-594535205
>Issue- Inconsistency in same design on two different places of theme.

Working fine .
---

>Issue- User having delete message icon to delete own message. Although not having any message to delete.
https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-594323968

Workimg fine
---

https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-594303070
@chetansatasiya Another issue I can see from Ankit's video:

This is working. now.

------

>@chetansatasiya Another issue I can see from Ankit's video:

working fine.



https://github.com/buddyboss/buddyboss-platform/pull/189#issuecomment-569863638

>Logic for the text in the yellow box is not working either.

https://www.loom.com/share/fa08b68557f24813bc9fb447ffbdb580
Correct logic would be:

Sent from group {groupname} to all group members.

For group thread, to all group members

Sent from group {groupname} to the people in this conversation.

For group thread, to individually selected members

Sent from group {groupname} individually to all group members.

For private reply (BCC), to all group members

Sent from group {groupname} to individual members.

For private reply (BCC), to individually selected members

Working fine. 

------

**Comment by ankitguptaindia** [comment]
@chetansatasiya @eisenwasser 

There are so many cases that I reported in the above comments when worked on this task. 
Now as per discussion I am checking all commented issues after current fixes/change in code by developer.
There are so many cases so testing all again is taking too much time to re-check. 

I tested almost 50% cases again and found one issue which came again after current fixes. 
So I am assuming, we can pause retesting now for each and every case. So I can save time and work on other tasks.

Please share your thoughts or let me know if I need to test each case again.

Thanks

**Pull request merged**
