### PR TITLE
fix sql query for mysql version 8.0.22

### LINKED ISSUE #2072: When a user uploads a document inside a folder the privacy dropdown is broken in the activity feed
**Describe the bug**
When a user uploads a document inside a folder the privacy dropdown is broken in the activity feed and profile timeline page. Please refer to the screenshot: https://prnt.sc/x5e0nq
If upload a document outside of a folder then it is fine.

There is a mysql query in function `bp_document_get_root_parent_id` in the file `buddyboss-platform/bp-document/bp-document-functions.php` which is used to get the parent folder id of the uploaded file and that query showing different result for mysql latest version (the query return the correct folder ID for mysql version 5.7 but not for latest version)

**To Reproduce**
1. Go to user profile documents (activate media component and enable document upload for activity)
2. create a folder and upload a file into that folder
3. Go to user profile activity feed page
4. See broken activity item https://prnt.sc/x5e0nq

**Expected behavior**
User profile activity feed item should not be broken

**Screenshots**
- customer site issue: https://prnt.sc/x5e0nq
- results in old and latest mysql version: https://www.loom.com/share/3fdbf98589134226a6ca5ee3b577ccef

**Support ticket links**
https://secure.helpscout.net/conversation/1391932037/119086?folderId=4314898

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
There is a mysql query in function `bp_document_get_root_parent_id` in the file `buddyboss-platform/bp-document/bp-document-functions.php` which is used to get the parent folder id of the uploaded file and that query showing different result for mysql latest version (the query return the correct folder ID for mysql version 5.7 but not for latest version). I updated the SQL query to make it work for both versions.

Fixes #2072

### How to test the changes in this Pull Request:

1. Go to user profile documents (activate media component and enable document upload for activity)
2. Create a folder and upload a file into that folder
3. Go to user profile activity feed page
4. See activity item is not broken now, before it was broken for MySQL version 8.0.22

### Proof Screenshots or Video
https://www.loom.com/share/57ea4859856b4c04a0421d092a2c6357

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@sadrul LGTM 👍 

@mohit-buddyboss OR @sumitbuddyboss Need to test this in different mysql versions.

**Comment by chetansatasiya** [comment]
@sadrul Merge in dev and add in testing.

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss Merged in dev and ready for tesing

**Review by mehulkaklotar — APPROVED** [review]
@mohit-buddyboss @sumitbuddyboss please test this.

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

Fixed>
I have checked with a version of 8.0.16 / 8.0.23 / 5.7.28 and it's working as expected there is no any activity is broken for the proof please check the below video.


Videos
https://www.loom.com/share/d9bdb869e8b942b28459835043d47352
https://www.loom.com/share/d0457c8f49a84898941ed1509933b12f

Thank you for your help @sadrul 

@chetansatasiya 
Ready for release

**Pull request merged**
