### PR TITLE
Fixed - Cover photo is not showing after uploading while creating a group

### LINKED ISSUE #1726: Cover photo is not showing after uploading while creating a group
**Describe the bug**
The cover photo is not showing after uploading while creating a group. You need to refresh the page to see that.

**To Reproduce**
1. Upload a cover photo while creating a group
2. See error

**Expected behavior**
Cover photo should show immediately. 

**Screenshots**
https://prnt.sc/vccesv

**Support ticket links**
https://secure.helpscout.net/conversation/1326866096/106644/

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1726 

### How to test the changes in this Pull Request:

1. In Createa a Group Flow
2. Upload a Cover photo in Cover Photo tab
3. It should reflect instantly

### Proof Screenshots or Video
https://prnt.sc/vccvn7

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by amincdev** [comment]
@chetansatasiya Please review this

**Review by chetansatasiya — APPROVED** [review]
@amincdev Approved!!! Merge in dev and give it in testing

**Comment by amincdev** [comment]
@ankitguptaindia @mohit-buddyboss and @sumitbuddyboss  Merged in `dev` and ready for testing.

**Comment by sumitbuddyboss** [comment]
Hello @amincdev 

Fixed > I've tested in the dev branch and now the group cover photo reflects instantly. For proof please check the below video.

Video.
https://www.loom.com/share/b9c0549381a544038056d2c1a19c90bb

@chetansatasiya  Ready to release 🚀 

CC @ankitguptaindia

**Pull request merged**
