### PR TITLE
Who's online widget shows hidden users.

### LINKED ISSUE #679: Who's online widget shows hidden users.
**Describe the bug**
Created a profile type and enabled the option to hide the users from the member's directory. It hides the users on member's page but displays them on "Who's online widget". 

I am not sure if it is intended to work like that. 

**To Reproduce**
1. Go to BuddyBoss > Profiles > Profile Type
2. Create a profile type and enable "hide users from member's directory" 
3. Open a page where "Who's online" widget is added

**Expected behavior**
The hidden users should not be displayed on Who's online widget too. 

**Screenshots**
- https://i.imgur.com/fzprY3i.jpg
- https://i.imgur.com/de9vxao.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1114816861/63632/

### PR DESCRIPTION
**Pull request by manishpatolia**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #679 .

### How to test the changes in this Pull Request:

1. Go to BuddyBoss > Profiles > Profile Type
2. Create a profile type and enable "hide users from member's directory" 
3. Open a page where "Who's online" widget is added

### Proof Screenshots or Video
https://www.loom.com/share/760066938f4a47ed8ca3ce27ae73af2e

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@ankitguptaindia @mohit-buddyboss Please test this.

**Comment by mohit-buddyboss** [comment]
@manishpatolia 
FIXED. Tested this on a branch f`ix/679` . Tested related functionality for both connections as well as non-connected users. If the user profile type is hidden from the group directories page then that user is not appearing under who's online widget now. For Proof see this video: https://www.loom.com/share/356bad0eb4b9467db14f803d8926bed8

**Here I've one question:**
But I've noticed that because the Hide setting is for only members' directory page. Hidden Profile type members still appear on Group members listing and under the connection tab of user profile if that user is connected with Hidden Profile types members. So, it is basically creating a security concern that users are able to see Hidden Profile types on other tabs. @chetansatasiya can you please share your thoughts on it?

**Comment by mohit-buddyboss** [comment]
@chetansatasiya @sourabhmatolia 

These changes are for only 'Who online widget'  . If the user Profile type  is hidden from Members directory page then that profile type user will also not appear under 'Who's online widget' for both connections as well as for not connected users.

But I've notice that these members having hidden profile type also appears under Group 'Members' tab and user profile 'Connections' tab. So, basically other users can see Hidden Profile type members from these tabs. 

Kindly confirm if it is intended to work like that.

cc @ankitguptaindia

**Comment by ankitguptaindia** [comment]
> Hide all members of this type from Members Directory 

https://i.imgur.com/WK5Kibf.jpg

This setting provides option to hide only from Directory page. This is not hiding that profile type member from whole site. 
if we hide member from connection and group member listing then it will treat like a HIDDEN member from site.

So I thought,  it should not hide from Group Member tabs and Connection tab.

Let's wait for @sourabhmatolia feedback and then complete this PR.

Thanks.

**Pull request closed without merging**
