### PR TITLE
#662 - Topic Reply Pagination

### PR DESCRIPTION
**Pull request by chetansatasiya**
Theme PR https://github.com/buddyboss/buddyboss-theme/pull/1261
API PR: https://github.com/buddyboss/buddyboss-platform-api/pull/267

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by sourabhmatolia** [comment]
@chetansatasiya 

As discussed, Please have @dkvasani take over this task. Thanks.

**Comment by jitendrabanjara1991** [comment]
Hello @sourabhmatolia @chetansatasiya @mehulkaklotar 
I have fixed **Topic Reply Pagination**. For that, I have changed in the **buddyboss-theme** theme.  [https://github.com/buddyboss/buddyboss-theme/pull/1261](https://github.com/buddyboss/buddyboss-theme/pull/1261)

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya @mehulkaklotar 
Here is the video for the task update - [https://screencast-o-matic.com/watch/crVFb69IJV](https://screencast-o-matic.com/watch/crVFb69IJV)

**Comment by sourabhmatolia** [comment]
@jitendrabanjara1991 

I quickly tried to TEST this feature. It is not working for me.
Please check the video below for more details:
https://www.loom.com/share/1f16206ca9284b87b861f4335d3a7876

Thanks.

**Comment by jitendrabanjara1991** [comment]
Hello @sourabhmatolia 
I have fixed the issue. The issue was happening, when the reply threading option enabled, then it was redirecting to the wrong page.
Here is the video for the proof.  [https://screencast-o-matic.com/watch/crVvjsRbAx](https://screencast-o-matic.com/watch/crVvjsRbAx)
Please check it and let me know if anything else.
Thanks

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
@jitendrabanjara1991 This doesn't work for me as well. https://www.loom.com/share/e46cbcb0220145739707dd91d88a13eb

**Comment by jitendrabanjara1991** [comment]
@mehulkaklotar 
Thanks for review. I have checked this bug in my local and its working fine.
Please check it my attached video and let me know if I am missing anything steps or some thing else.
Reply Threading option enable - https://screencast-o-matic.com/watch/creobCVc5lA
Reply Threading option disable - https://screencast-o-matic.com/watch/creob7Vc5om 
Thanks

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 @KartikSuthar 

Please merge it to the dev branch.

Thank you

**Comment by jitendrabanjara1991** [comment]
@sumitbuddyboss 
Merged in dev and ready for testing.
Thanks

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

**Issue:**
If we edit the discussion first reply and again add a comment the old comment and last edit time is the display, It should be display updated content, also should not display modified time, for more detail please check the bug video.

**How to reproduce:**
1) Open any Group forum or forum with no group 
2) Edit the first discussion comment
3) Add another reply
4) See error

**Bug video**
https://www.loom.com/share/0c75e93d618844e4959d03104c6fd994
https://www.loom.com/share/1cbffd622eef4061aa79eea3a01f8e08

Thank you

**Comment by jitendrabanjara1991** [comment]
@sumitbuddyboss 
Fixed it. Please retest it.
Here is the video - https://screencast-o-matic.com/watch/cr1Ql3Vhdhq
Thanks.

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

**Issue**
If we edit any reply on page no-1 and post then it will redirect to the next page. This issue appears in group > forum reply and forum with no group.

Issue video:
https://www.loom.com/share/d92ad7aa0f234612a97c68ff59f5940e


Thank you

**Comment by KartikSuthar** [comment]
@jitendrabanjara1991 Please check with Topic Merge and Reply Split functionality, I see they have count issue into pagination,
http://prntscr.com/15kzvbn

**Comment by jitendrabanjara1991** [comment]
@KartikSuthar 
cc - @chetansatasiya 
Fixed - count is wrong on the last page.
image

Merge and split functionalities issues are in our release branch. I have created an issue for the same - https://github.com/buddyboss/buddyboss-platform/issues/2507
Please check it and let me know if anything else.
Thanks.

**Review by KartikSuthar — DISMISSED** [review]
@jitendrabanjara1991  Please merged to dev and pass to QA.

**Comment by jitendrabanjara1991** [comment]
Merged in dev and ready for testing.
Thanks.

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

Fixed > I have checked the pagination, and now reply on any page it will redirect to last past of pagination. Also, resolve all the issue which I've posted. For the proof please check the below video.

Video:
https://www.loom.com/share/b74070d5673f48468d780d164a9a878b
https://www.loom.com/share/e3a13af261bb4ef7992a4fc9106e71cc

Related theme PR:
https://github.com/buddyboss/buddyboss-theme/pull/1261

@sourabhmatolia @chetansatasiya 
Ready for release 🚀 


Thank you

**Pull request merged**
