### PR TITLE
#2586 - fix php warning for (BB) Latest Activities widget

### LINKED ISSUE #2586: WordPress 8.0 Compatibility CHECK
Check Platform compatibility with WordPress v5.8

All features: https://wordpress.org/news/2021/07/the-month-in-wordpress-june-2021/
Theme.json  : https://make.wordpress.org/test/2021/06/24/call-for-testing-thrive-with-theme-json/

IF we see issues specific to WP 8.0 then please note all issues here for someone to fix.

### Connected Issue in Platform Pro
https://github.com/buddyboss/buddyboss-platform-pro/issues/178

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
There was an additional serialize which breaks it and showing a warning. I removed that.

### Connected PR in Platform Pro
https://github.com/buddyboss/buddyboss-platform-pro/pull/179

Fixes #2586 .

### How to test the changes in this Pull Request:

1. Go to backend widget
2. Add (BB) Latest Activities widget and save
3. check frontend, the error gone

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]

**Comment by chetansatasiya** [comment]
@sadrul Merge in dev and put in testing.

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss merged in Dev and ready for testing
cc: @chetansatasiya @sourabhmatolia

**Comment by KartikSuthar** [comment]
@sadrul Please do the changes as we discussed.

**Review by KartikSuthar — APPROVED** [review]
@sadrul  Approved. Please merged to dev and pass to QA.

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss merged in Dev and ready for testing

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

Fixed > I have checked the Latest Activities widget and now it's working fine from my end.

Screenshot.
https://prnt.sc/1b0x0nn
https://prnt.sc/1b0xyw5

@sourabhmatolia @chetansatasiya 
Ready for release 🚀 

Thank you

**Pull request merged**
