### PR TITLE
Attachment Privacy Issue Fixes

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:
- Removed documents and medias from the WordPress media API, It's only accessible via platform API. `/wp-json/wp/v2/media`
- Setup a 404 page when the user views the media/document from the attachment URL here: http://prntscr.com/vh9369

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — COMMENTED** [review]
@KartikSuthar 🚀

**Comment by chetansatasiya** [comment]
@KartikSuthar Approved merge in dev and put in testing

**Comment by sumitbuddyboss** [comment]
Hello @KartikSuthar 

Fixed > 
I've checked below two points on the Dev branch and it's working as expected. For the proof please check the video.

1) Removed documents and media from the WordPress media API, It's only accessible via platform API. /wp-json/wp/v2/media
2) Setup a 404 page when the user views the media/document from the attachment URL

Video:
https://www.loom.com/share/9016a1f0a6e14550a70f54887982a697

 @chetansatasiya 
Ready for release 🚀 


CC @ankitguptaindia

**Comment by ExoGeek** [comment]
@KartikSuthar Maybe I'm wrong but I think that we can also have access to any medias through the default wordpress endpoint oembed.

See : [http://localhost/wp-json/oembed/1.0/embed/](http://localhost/wp-json/oembed/1.0/embed/)

**Review by mehulkaklotar — APPROVED** [review]

**Comment by KartikSuthar** [comment]
> @KartikSuthar Maybe I'm wrong but I think that we can also have access to any medias through the default wordpress endpoint oembed.
> 
> See : http://localhost/wp-json/oembed/1.0/embed/

@ExoGeek It's fixed on PR: #1794

**Pull request merged**
