### PR TITLE
Fixed - Date entry in repeatable field is getting changed after drag …

### LINKED ISSUE #1489: Date entry in repeatable field is getting changed after drag & drop
**Describe the bug**
When using the date fields in the repeater set, the date/year changes when the user drags the 2nd info to the 1st.

**To Reproduce**
Steps to reproduce the behavior: https://www.loom.com/share/3936e4203fb44597a71ff2875f6dbd0e

**Expected behavior**
Date should not be changed after dragging. 

**Support ticket links**
https://secure.helpscout.net/conversation/1280742864/98434

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1489.

### How to test the changes in this Pull Request:

1. Create new field set with Repeater option enable
2. Add two or more field with date
3. Front side - Profile -> Edit Profile -> Add two or More repeater field and change there orders

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crf1iyVnfn1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
Code LGTM 

@jitendrabanjara1991 merge in dev and put in testing

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya 
Merged in dev and ready for testing.
Thanks

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya 
cc - @KartikSuthar 
I have added doc comment on changes.
So, Please check it and let me know if anything else.
Thanks.

**Comment by sadrul** [comment]
@KartikSuthar I updated according to your feedback, could you please check now

**Review by KartikSuthar — DISMISSED** [review]
@sadrul Looks good to me. Please merged to dev and pass to QA.

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss Merged to dev and ready for testing
cc: @sourabhmatolia

**Review by chetansatasiya — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

Issue >
I'm getting the same issue if I add 3 fields, please check the below issue video.

Issue video.
https://www.loom.com/share/7caaf8cd5b6647aeb3aca0457b5ac116

cc @sourabhmatolia @chetansatasiya

**Review by KartikSuthar — APPROVED** [review]

**Comment by sadrul** [comment]
@sumitbuddyboss could you please test again, the reported issue is fixed

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

**Fixed >** 
The related issue is resolved now we can two or More repeater fields and change their orders for the proof please check the below video.

**Video:**
https://www.loom.com/share/3ee6cbfc4c4a4136a0caf1af0295bf88

Thank you

**Pull request merged**
