### PR TITLE
Photo more options hover, photo popup shows previous image for a while

### LINKED ISSUE #2082: Photo more options hover, photo popup shows previous image for a while
**Describe the bug**

1. Photos (...) ellipsis dropdown hover is not proper
2. Photos Popup behaving weird by showing last open image and then new select image.
3. View Group Photos in Popup as Organizer > Fix order here to show “Report” just before “delete” button: https://prnt.sc/xpffcs 

**Video**
https://www.loom.com/share/8a9e51400ce2466387ce520f31be768d

### PR DESCRIPTION
**Pull request by amincdev**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #2082 

### How to test the changes in this Pull Request:

1. Check photos (...) ellipsis dropdown hover
2. Photos Popup should not show the last opened image and then new select image.
3. View Group Photos in Popup as Organizer >Now order is: “Report” just before “delete” button

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by Felipemauah** [comment]
Hello! this problem has also happened in the Activity Feed! always before showing the image I clicked to see the previous one appears. :)

**Comment by amincdev** [comment]
> Hello! this problem has also happened in the Activity Feed! always before showing the image I clicked to see the previous one appears. :)

@Felipemauah Yes, It is also considered and will be fixed with this PR.

**Comment by Felipemauah** [comment]
> > Hello! this problem has also happened in the Activity Feed! always before showing the image I clicked to see the previous one appears. :)
> 
> @Felipemauah Yes, It is also considered and will be fixed with this PR.

Many thanks for the reply! You guys do an amazing job!

**Comment by amincdev** [comment]
@sourabhmatolia This is ready for review.

**Review by sourabhmatolia — APPROVED** [review]

**Pull request merged**
