### PR TITLE
Fixed #2946 Removed additional space after mention @name

### LINKED ISSUE #2946: Double spacing is been added after using @name in the mentions
**Describe the bug**
After mentioning someone with @ the platform inserts after the users name 2xspace.

**To Reproduce**
1. please go online https://demos.buddyboss.com/online-communities/ 
2. In the Activity Feed mention some member
3. after you write @ see the issue with extra space

**Expected behavior**
It should take only one space not two space.

**Screenshots**

**Environment**
client site as well on my deb site and on our demo site.

**Support ticket links**
https://secure.helpscout.net/conversation/1624690423/0/?folderId=3709082

### PR DESCRIPTION
**Pull request by bb-yudhisthir**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2946 .

### How to test the changes in this Pull Request:

1.Type the mention with the @ in the News Feed
2.Click on any name on the suggession list, you will see one space now after that mention

### Proof Screenshots or Video before/after fix

http://somup.com/cr6UQb3Ekx
http://somup.com/cr6UQO3Epb

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Removed additional space after mention @name

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

**Review by chetansatasiya — COMMENTED** [review]
We added these changes to fix the https://github.com/buddyboss/buddyboss-platform/issues/635 issue. So now if we removed this then again reopening this #635 issue again. Have you cross-checked after these changes it's working fine? @bb-yudhisthir

**Comment by bb-yudhisthir** [comment]
> We added these changes to fix the #635 issue. So now if we removed this then again reopening this #635 issue again. Have you cross-checked after these changes it's working fine? @bb-yudhisthir

@chetansatasiya Yes I have checked it the space was added for the case where earlier there were no spacing appearing in between after any mentions added and if we add the multiple mentions one by one in sequence it was causing the issue https://www.loom.com/share/a6875479db9f45d48b8ac0577af7b0d1is on timestamp 0:37 sec, but the issue now is its showing double space with one we added intentionally in #635 [commit](https://github.com/buddyboss/buddyboss-platform/commit/a6ae7858361d94bcdc0eedd37dbadd14111ae8fd) and the default space also working now, so the case is now the space we added not required
image

**Review by chetansatasiya — APPROVED** [review]

**Comment by joeytoribio** [comment]
Hi @bb-yudhisthir,

This has been tested in the qa-ongoing branch without any issues.

### Test Case#1
News Feed: Double spacing is been added after using @name in the mentions

**To Reproduce:** 

1. Go to News Feed then type the mention with the @name
2. Click on any name on the suggestion list, you will see one space now after that mention

**Result: PASSED**

### Test Case#2
Blog: Double spacing is been added after using @name in the mentions

**To Reproduce:** 

1. Go to Blog then type the mention with the @ in the Blog comment
2. Click on any name on the suggestion list, you will see one space now after that mention

**Result: PASSED**
### Test Case#3
Group: Double spacing is been added after using @name in the mentions

**To Reproduce:** 

1. Go to Group > Feed > Type the mention with the @name or Reply to any Previous Post with @name
2. Click on any name on the suggestion list, you will see one space now after that mention

**Result: PASSED**

### Test Case#4
Forum: Double spacing is been added after using @name in the mentions

**To Reproduce:** 

1. Go to Forum > New Discussion / Reply > Type the mention with the @name
2. Click on any name on the suggestion list, you will see one space now after that mention

**Result: PASSED**

**Video:**
https://www.loom.com/share/15a437072dd94115ab352abb973aec8c

Thank you!

**Comment by basil-buddyboss** [comment]
Hello @bb-yudhisthir 

This has been tested in the QA-approved branch including the four test cases and there were no issues encountered.

Result: Passed

**Pull request merged**
