### PR TITLE
Fixed DOMDocument class not found fatal error

### PR DESCRIPTION
**Pull request by shohel**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changelog entry

> Fixed DOMDocument class not found fatal error

### CODE REVIEW

**Comment by shohel** [comment]
cc @sourabhmatolia

**Review by mehulkaklotar — COMMENTED** [review]
@shohel why we include `composer.lock` file into this PR? is there any changes to composer.json?

**Comment by shohel** [comment]
No, nothing change, I've updated my local composer packages. that's why `composer.lock ` rewritten.

Let me delete it from the PR.

**Comment by shohel** [comment]
@mehulkaklotar Removed composer.lock from the PR

**Review by mehulkaklotar — APPROVED** [review]
looks good!

@shohel let's put it in testing.

**Pull request merged**
