### PR TITLE
Fix edit activity

### PR DESCRIPTION
**Pull request by mehulkaklotar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Group edit activity fixes - 

edit group activity then it just shows this dropdown:
https://prnt.sc/udsjuz

Profile vs Group (disabled dropdown)
Selected Group (disabled)

### Proof Screenshots or Video

https://prnt.sc/ueqj48
https://prnt.sc/ueqhbf
https://prnt.sc/ueqhyc

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@mehulkaklotar 👍 🚀 

@ankitguptaindia Need to test Edit Activity thorugly all the cases once and need to make sure nothing break.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

When editing group activity from site wide activty page then drop down options look like broken https://i.imgur.com/DREKpQe.jpg  And if edit same activity from group edit page then look fine
https://i.imgur.com/TpfGWnB.jpg

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar
> 
> When editing group activity from site wide activty page then drop down options look like broken https://i.imgur.com/DREKpQe.jpg And if edit same activity from group edit page then look fine
> https://i.imgur.com/TpfGWnB.jpg

@ankitguptaindia can you tag front end for this?

**Comment by ankitguptaindia** [comment]
> > @mehulkaklotar
> > When editing group activity from site wide activty page then drop down options look like broken https://i.imgur.com/DREKpQe.jpg And if edit same activity from group edit page then look fine
> > https://i.imgur.com/TpfGWnB.jpg
> 
> @ankitguptaindia can you tag front end for this?
> 
> also this issue ([buddyboss/buddyboss-theme#987](https://github.com/buddyboss/buddyboss-theme/issues/987)) from theme will be fixed here in this PR.

@amincdev 
Can you take over this issue.

**Comment by ankitguptaindia** [comment]
**Status-** Inprogress, testing privacy related cases with photos/documents and Documents/Files.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar Related to Issue mentioned here - https://github.com/buddyboss/buddyboss-theme/issues/987

>also this issue (buddyboss/buddyboss-theme#987) from theme will be fixed here in this PR. 

I noticed peculiar behaviour when editing activity which has Single Media/document. 

1. Sometimes it open the content in Popup and sometimes it open in single activity page.
2. When clicking Edit tab from Preview. it redirect to Single activity page and user has to click edit button again to edit the post. 

Refer -  https://www.loom.com/share/8062362732e44166ae0f7a93f0feb18e

-----------
-----------

The Tasks from this PR https://github.com/buddyboss/buddyboss-platform/pull/1469

Functionality related to photos/documents and Documents/Files in User Profile and Groups are working fine.
Tested with many use cases briefly.

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar Related to Issue mentioned here - [buddyboss/buddyboss-theme#987](https://github.com/buddyboss/buddyboss-theme/issues/987)
> 
> > also this issue ([buddyboss/buddyboss-theme#987](https://github.com/buddyboss/buddyboss-theme/issues/987)) from theme will be fixed here in this PR.
> 
> I noticed peculiar behaviour when editing activity which has Single Media/document.
> 
> 1. Sometimes it open the content in Popup and sometimes it open in single activity page.
> 2. When clicking Edit tab from Preview. it redirect to Single activity page and user has to click edit button again to edit the post.
> 
> Refer - https://www.loom.com/share/8062362732e44166ae0f7a93f0feb18e
> 
> The Tasks from this PR #1469

@ankitguptaindia this is fixed now.

**Comment by amincdev** [comment]
> @mehulkaklotar
> 
> When editing group activity from site wide activty page then drop down options look like broken https://i.imgur.com/DREKpQe.jpg And if edit same activity from group edit page then look fine
> https://i.imgur.com/TpfGWnB.jpg

@ankitguptaindia This is fixed now.

**Comment by ankitguptaindia** [comment]
> > @mehulkaklotar Related to Issue mentioned here - [buddyboss/buddyboss-theme#987](https://github.com/buddyboss/buddyboss-theme/issues/987)
> > > also this issue ([buddyboss/buddyboss-theme#987](https://github.com/buddyboss/buddyboss-theme/issues/987)) from theme will be fixed here in this PR.
> > 
> > 
> > I noticed peculiar behaviour when editing activity which has Single Media/document.
> > 
> > 1. Sometimes it open the content in Popup and sometimes it open in single activity page.
> > 2. When clicking Edit tab from Preview. it redirect to Single activity page and user has to click edit button again to edit the post.
> > 
> > Refer - https://www.loom.com/share/8062362732e44166ae0f7a93f0feb18e
> > The Tasks from this PR #1469
> 
> @ankitguptaindia this is fixed now.

@mehulkaklotar These issue have been fixed.  👍 

----


> > @mehulkaklotar
> > When editing group activity from site wide activty page then drop down options look like broken https://i.imgur.com/DREKpQe.jpg And if edit same activity from group edit page then look fine
> > https://i.imgur.com/TpfGWnB.jpg
> 
> @ankitguptaindia This is fixed now.

@amincdev These issues also have been fixed.

**Comment by ankitguptaindia** [comment]
@mehulkaklotar 

Strange behaviour: Critical-
When replacing media via editing post then whole post getting disappeared from site. This is happening for User activity and Group activity as well.

If you just add new media then post will work fine But when you delete previous image and add new image then whole post data will be lost.
Refer for more details - 

https://www.loom.com/share/e99e4f5869ca4acca30f46db08f8c51e

**Comment by ankitguptaindia** [comment]
FYI- Same happening with Documents Files as well.
https://github.com/buddyboss/buddyboss-platform/pull/1469#issuecomment-691922473

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar
> 
> Strange behaviour: Critical-
> When replacing media via editing post then whole post getting disappeared from site. This is happening for User activity and Group activity as well.
> 
> If you just add new media then post will work fine But when you delete previous image and add new image then whole post data will be lost.
> Refer for more details -
> 
> https://www.loom.com/share/e99e4f5869ca4acca30f46db08f8c51e

@ankitguptaindia this is fixed now.

> FYI- Same happening with Documents Files as well.
> [#1469 (comment)](https://github.com/buddyboss/buddyboss-platform/pull/1469#issuecomment-691922473)

@ankitguptaindia this also fixed now.

**Comment by ankitguptaindia** [comment]
> > @mehulkaklotar
> > Strange behaviour: Critical-
> > When replacing media via editing post then whole post getting disappeared from site. This is happening for User activity and Group activity as well.
> > If you just add new media then post will work fine But when you delete previous image and add new image then whole post data will be lost.
> > Refer for more details -
> > https://www.loom.com/share/e99e4f5869ca4acca30f46db08f8c51e
> 
> @ankitguptaindia this is fixed now.
> 
> > FYI- Same happening with Documents Files as well.
> > [#1469 (comment)](https://github.com/buddyboss/buddyboss-platform/pull/1469#issuecomment-691922473)
> 
> @ankitguptaindia this also fixed now.



These issues have been fixed. 👍  Cross tested.

**Review by ankitguptaindia — APPROVED** [review]
@sourabhmatolia @mehulkaklotar 

**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [x] Tested negative test scenario

- [x] Updated Labels as per current status

**Final Update-**  Ready to merge 🚀

**Pull request merged**
