### PR TITLE
#1665 - Fixed the issue Blog post video Embed is not working in activ…

### LINKED ISSUE #1665: Blog post's video Embed is not working in activity feed.
**Describe the bug**
When posting blog posts containing a video. The video doesn't embed on the activity feed. Videos are now displaying as URL instead of the video.
This all started happening after the latest update v1.5.3

**To Reproduce**
1. Go to 'Admin Dashboard >> Posts >> Add New' and add a post with a Youtube video
2. Navigate to the Activity Feed page on the frontend.
3. See Error.

**Expected behavior**
It should embed the video in the activity feed.

**Screenshots**
Backend:
https://prnt.sc/v3kzmw

Front End Activity Feed:
https://prnt.sc/v3kz3t

**Support ticket links**
https://secure.helpscout.net/conversation/1312707010/103861/

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
…ity feed

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1665  .

### How to test the changes in this Pull Request:
1. Go to 'Admin Dashboard >> Posts >> Add New' and add a post with a Youtube video
2. Navigate to the Activity Feed page on the frontend.
3. See Error.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]
@krunal-buddyboss Approved.

**Comment by chetansatasiya** [comment]
@ankitguptaindia This is ready for testing code is merged in dev.

**Comment by sumitbuddyboss** [comment]
@chetansatasiya 
Fixed > Tested this on the Dev branch and everything working as expected.

For the proof please check the video 
https://www.loom.com/share/aa15ee18958d4baab4a67ffcddbc2488
https://prnt.sc/va50l5

PR is ready to release 🚀 

CC @ankitguptaindia

**Review by mehulkaklotar — APPROVED** [review]
approved!

**Pull request merged**
